### ISSUE TITLE
Double event invitation through synchronization

### ISSUE THREAD

**Issue by kdoteu** [pimutils/vdirsyncer#1002]
I want to sync a calender between two different Nextcloud instances. Everything works fine so far. But there ist a slight problem with events with participants invited by e-mail.
When I create an event "best syncsolution" with a participant john@doe.tld in the first nextcloud instance and sync it to the second instance John gets two invintations from every instance.

Is there a way to prevent the double invintation? I'm fine with solutions like automatically removing participants and so on.

* Your vdirsyncer version : 0.18.0
* If applicable, which server software (and which version) you're using
  * Your Python version: 3.8.10
  * Your operating system: Ubuntu 20.04.4 LTS
  * Your config file
```
[general]
status_path = "~/.vdirsyncer/status/"

# CALDAV
[pair bob_calendar]
a = "bob_calendar_local"
b = "bob_calendar_remote"
collections = [["mytest", "entwicklung", "entwicklung-test"]]

# Calendars also have a color property
metadata = ["displayname", "color"]

[storage bob_calendar_local]
type = "caldav"
url = "https://first.nextcloud.tld/remote.php/dav/calendars/felix/entwicklung/"
username = "felix"
password = "ABCDE-FGHIJ-KLMNO-PQRST-UVWXY"


[storage bob_calendar_remote]
type = "caldav"
url = "https://second.nextcloud.tld/remote.php/dav/calendars/felix/entwicklung-test/"
username = "felix"
password = "ABCDE-FGHIJ-KLMNO-PQRST-UVWXY"
```

**Comment by WhyNotHugo** [comment]
The invitation is send by Nextcloud when the event is created. There is nothing in the CalDav protocol that gives us any control over this; this is a purely a server-specific behaviour after a new event is uploaded.

You'll need check the Nextcloud docs to see if you can configure the second instance to _not_ send invites.

Ideally, Nextcloud should add some extra parameter to the attendee once it sends an invite (e.g.: `X-INVITE-SENT=19980430T000000Z`, so that it is later possible to determine that an invite has already been sent. Again, this is something only they can implement.

**Comment by kdoteu** [comment]
Yes you're totally right. I'll open a ticket at their repo. 

But is there anything I/we can to from this site. Like ignoring participants (metadata) or something like this?

**Comment by WhyNotHugo** [comment]
Ignoring participants would be tricky. Vdirsyner mostly syncs items as-they-are without really filtering fields (with one exception which brings enough problems as it is) . Potentially we _could_ support applying a function when syncing in one direction, but that's a really big architectural change that won't happen anytime soon.

Essentially, vdirsyncer just reads the calendar entry from one calendar, and writes it into another. Nextcloud then sends an email, so your best bet is to try and fix it there.

**Comment by kdoteu** [comment]
I found out why the invitiations got sent twice ... Both users of both instances had the same E-Mail address. Changing one of them, solved the issue.
