### ISSUE TITLE
Google Sync 400: invalid_request

### ISSUE THREAD

**Issue by Bleala** [pimutils/vdirsyncer#1028]
Hello there,

Since Google Sync did not work for a long time i tried Vdirsyncer 0.19.0 but with this version i got the following error:
```
critical: Failed to initialize google
critical:   - google_contacts storage doesn't take the parameters: type
```

I found an issue where someone mentioned this problem and that it is already fixed, but not compiled yet.

So I tried to compile Vdirsyncer by myself, cloned the git repo and ran `make install-dev`.

This worked and the error disappeared, but now i have another error that the request is invalid --> `400: invalid_request`.

The correct APIs are activated in the Google API Manager and all dependencies for 0.19.0 are installed (`python-aiohttp-oauthlib`).

* Your vdirsyncer version: 0.19.1.dev5+g90b6ce1
* Your Python version: 3.10.9
* Your operating system: Ubuntu and Alpine
* Your config file
```
### General ###
[general]
status_path = "/vdirsyncer/status/"

### Pairs ###
# Google Oauth funktioniert aktuell nicht
[pair google_local_carddav]
a = "google"
b = "local"
collections = ["from a", "from b"]
conflict_resolution = "a wins"
metadata = ["color", "displayname", "description", "order"]

### Storage ###
[storage google]
type = "google_contacts"
token_file = "/vdirsyncer/google_contacts"
client_id = "<redacted>"
client_secret = "<redacted>"

[storage local]
type = "filesystem"
path = "/vdirsyncer/contacts/"
fileext = ".vcf"
```

* Google Login Error
![Google Login Error](https://user-images.githubusercontent.com/51357182/210237744-9a035a90-db6e-494e-a0c5-13268d8d0476.jpg)

Does anyone has an idea what's the problem here?

Greetings

**Comment by WhyNotHugo** [comment]
Does your same setup work with 0.18? I mostly want to understand if this is a regression or not.

**Comment by WhyNotHugo** [comment]
Have you tried deleting the token_file?

**Comment by verotheelf** [comment]
I have the same issue and I'm on 0.18. Happened after google wanted me to authenticate again so deleted the token_file and got the same error as above.

**Comment by Bleala** [comment]
@WhyNotHugo 
No also with 0.18 it does not work. And I deleted the token_file, this error shows up when I run `vdirsyncer discover` during the authentication, it's the same problem as @verotheelf does have.

**Comment by verotheelf** [comment]
Apparently it's because the program no longer complies with google's OAuth policy. There's a closed ticket on the issue (#975) that gives a temporary solution to the problem: https://github.com/pimutils/vdirsyncer/issues/975#issuecomment-1274381163

Worked for me

**Comment by WhyNotHugo** [comment]
Ah, darn, I closed that issue when merging https://github.com/pimutils/vdirsyncer/pull/985, but the documentation was never updated.

Indeed, the comment to which @verotheelf contains the correct solution here.

I'll leave this issue open to track updating the documentation --
and also mentioning it in the changelog just so everyone is aware of this.

**Comment by amcooper** [comment]
I've been using that workaround since v0.18. It stopped working for me—Google radomizes the port number for the authentication. Just dropping this in here in case someone else is having similar issues; it will be a while before I have time to have a detailed look at it.

**Comment by WhyNotHugo** [comment]
Google doesn't pick the port, it's defined by vdirsyncer when initiating the flow.

**Comment by WhyNotHugo** [comment]
Update for the docs in https://github.com/pimutils/vdirsyncer/pull/1035

**Comment by merzak274j** [comment]
I am not a computer programmer, so just to make sure I am understanding the implications correctly. 

If I was running vdirsyncer on my webhost, I can no longer sync with google because I am not running it locally and therefore cannot authenticate against the correct redirect URI ? 

I think so because when I use http://127.0.0.1:8088 and then try and authenticate against the URL vdirsyncer provides when reconnecting I receive an Error 400: redirect_uri_mismatch

**Comment by traycerb** [comment]
I'm having the same issue, the port number differs now, and getting a Error 400: redirect_uri_mismatch.  I'm using the updated steps in the Docs for Google calendar.

Before, the port could be fully assigned using [a hack]( https://github.com/pimutils/vdirsyncer/issues/975#issuecomment-1275698939).  I can't be sure if it's the port that causes the issue, but I have an older version of the google.py on my laptop and it worked fine.

I have no knowledge of what's happening, but I saw your comments that vdirsyncer creates a server as part of the workflow. can the port be set manually as part of this?

**Comment by traycerb** [comment]
@WhyNotHugo 

I can confirm that assigning a port in the credentials, and then assigning that port on the self-created server allows the credential process to move forward, at least until it fails in the same way as in the hack above.  

This is accomplished by changing the `local_server = wsgiref.simple_server.make_server` line in `google.py` from using a port number of 0, to instead the port number defined in the credentials, in my case 8088.

But as someone else reports, after extracting the code from the URL, there's no place to paste it, as the workflow has changed.

**Comment by WhyNotHugo** [comment]
Are you using the latest version? Please open a new issue with all the details (including vdirsyncer version), the bug originally reported here has been fixed; you're likely having a different problem.

**Comment by benasocj** [comment]
@WhyNotHugo, I can confirm that adding `http://127.0.0.1` in the "Authorised redirect URIs" section on the [Credentials web page](https://console.cloud.google.com/apis/credentials) is required in order to get rid of the `Error 400: redirect_uri_mismatch` error. It would be good to add this step to the manual.
