### ISSUE TITLE
vdirsyncer 0.19: auth_cert broken

### ISSUE THREAD

**Issue by Pikrass** [pimutils/vdirsyncer#1033]
So I was investigating why my calendar wasn't syncing anymore, with 401 responses. After seeing my client certificate wasn't being received on the server, I realized this was coming from vdirsyncer. A bit of digging and I found these lines in http.py:

```python
    # TODO: Support for client-side certifications.
    #...
    kwargs.pop("cert", None)  # TODO XXX FIXME!
```

So, yeah. A line in the changelog would have saved me a bit of time.  🥲
Since I need this I'll see what I can do.

**Comment by WhyNotHugo** [comment]
Whoops, sorry, that `TODO` should not have shipped in that state. :cry:

**Comment by WhyNotHugo** [comment]
I don't have a server set up with client certificates.

Do you have your own server? Is setting up a test user feasible?

**Comment by tom-kuca** [comment]
I found two errors in the patch:

##### It breaks server certificate verification 

A new blank SSL context is created. There might already be one with CA certifificate setup.
```diff
-ssl_context = create_default_context()
+ssl_context = kwargs.pop("ssl", create_default_context())
```

##### It doesn't support private key in a separate file.

From the documentation
> auth_cert – Optional. Either a path to a certificate with a client certificate and the key or a list of paths to the files with them. 

The list is converted to a tuple, `load_cert_chain` expects private key as a separate argument.

```diff
-ssl_context.load_cert_chain(cert)
+ssl_context.load_cert_chain(*cert) 
```
It works for both cases.

The complete snippet that works for me:

```python
    cert = kwargs.pop("cert", None)
    if cert is not None:
        ssl_context = kwargs.pop("ssl", create_default_context())
        ssl_context.load_cert_chain(*cert)
        kwargs['ssl'] = ssl_context

```

Tested on version 0.19.1.dev28+gdf14865

**Comment by WhyNotHugo** [comment]
Thanks for digging into this and sharing all the details!
