### ISSUE TITLE
start full new sync

### ISSUE THREAD

**Issue by GUNT0815** [pimutils/vdirsyncer#1045]
I am using the latest version of stable vdirsycner to sync my nextcloud calendars with external webcals. Everything looks like out of sync - many conflicts.

So I want to start from scratch. How should I proceed? Could not find anything in the forum so far.

**Comment by WhyNotHugo** [comment]
If you want to start from scratch entirely (e.g.: delete **everything** local), the easiest approach is to:

- delete local state files in `~/.local/share/vdirsyncer/`.
- delete everything in the local calendar directory.

I'll re-state the obvious just in case: you'll lose any local changes or any local files that have not been uploaded, and this cannot be undone.
