### ISSUE TITLE
Critical: Invalid value for verify (True), must be a path to a PEM-file.

### ISSUE THREAD

**Issue by blogdemoi** [pimutils/vdirsyncer#1047]
* Your vdirsyncer version: 0.19.0
* Your operating system: Manjaro Xfce
* Your config file:
[pair bics]
a = "bics_local"
b = "bics_remote"
collections = ["bicsics-import-1"]
conflict_resolution = "b wins"
metadata = ["displayname", "color"]
 
[storage bics_local]
type = "filesystem"
path = "~/.config/vdirsyncer/local/"
fileext = ".ics"
 
[storage bics_remote]
type = "caldav"
url = "https://xxx.org/nextcloud/remote.php/dav/calendars/arnauld/bicsics-import-1/"
verify_fingerprint = "xxxx"
verify = true
username = "xxxx"
password.fetch = ["prompt", "Password for CalDAV"]

Hello,

I installed vdirsyncer on a new laptop with Manjaro and receive this error when running: `vdirsyncer discover`

> ~ > vdirsyncer discover
> Password for CalDAV: 
> Discovering collections for pair bics
> bics_local:
>   - "bicsics-import-1"
>   - "bicsics-import"
> critical: Invalid value for verify (True), must be a path to a PEM-file.

What could be wrong?

Thank you.

**Comment by WhyNotHugo** [comment]
[Changed in 0.19.0](https://vdirsyncer.pimutils.org/en/stable/changelog.html#changes-to-ssl-configuration): 

> The verify parameter no longer takes boolean values, it is now optional and only takes a string to a custom CA for verification.

If you want to enforce verification of TLS certificates you don't need to do anything: that's the default.
