### ISSUE TITLE
Discover fails on sogo

### ISSUE THREAD

**Issue by cenktaskin** [pimutils/vdirsyncer#1049]
_My apologies for the issue, turned out to be a problem with the password.fetch which I could fix at the end._

**Comment by Tonus1** [comment]
On Sat, Mar 04, 2023 at 08:00:08AM -0800, Cenk Taskin wrote:
>Recently switched from my radicale setup to my university dav server due to problems related to DecSync, which was my solution to have sync to Android with Syncthing. Although I can't get to fetch my calendars which work finely enough with Thunderbird to vdirs via vdirsyncer.
>
> ...
>
>```
>[storage sogo_calendar_remote]
>type = "caldav"
>url = "https://sogo-url/SOGo/dav/"
>username = "my_id"
>password.fetch = ["command", "pass", "myuni", "-c"]
>```

Hi

I have no problem with SoGo with :
```
url = ***@***.***/Calendar/
username = ***@***.***
```

Regards,

Tonus

**Comment by cenktaskin** [comment]
> Hi I have no problem with SoGo with : ``` url = ***@***.***/Calendar/ username = ***@***.*** ``` Regards, Tonus

Hey expectedly we have different server configurations available to us, and the fault might be fully on mine.

As far as I can deduct from the censored config, yours requires e-mail adresses but on the server available to me I have a different username for accessing sogo.

Would appreciate if someone can show a way to debug the sitaution more to discover whether if I could work it out or somehow it is not available by server.

For example if I knew what is response expected from the server on request I could probe it further.

Cheers, C.

**Comment by Tonus1** [comment]
Do you have an access to a wen UI ?

**Comment by cenktaskin** [comment]
> Do you have an access to a wen UI ? 

If that was meant to be "web UI", I have access to it, without any admin
access. Otherwise I don't have an idea what that might be.

**Comment by Tonus1** [comment]
>If that was meant to be "web UI", I have access to it, without any admin
>access. Otherwise I don't have an idea what that might be.
>
>
Yes sorry, web UI.
In the 3 dots menus on the left you may have `links to agenda` to 
`access to authenticated users`.

**Comment by cenktaskin** [comment]
> In the 3 dots menus on the left you may have `links to agenda` to 
> `access to authenticated users`.
Although slightly different wording I can see we have the same UI
mostly. My left sidebar a list of my calendars, and each has a three
dots menu next to them. Where I have an option called "Links to this
Calendar", which leads to a pop-up window with "Authenticated User
Access" with three links listed below as CalDAV URL, WebDAV ICS URL,
WebDAV XML URL. 

But these are all the stuff that I already know. The CalDAV URL from
this popup is the URL in my config.
