### ISSUE TITLE
'make man' need vdirsyncer to be already installed

### ISSUE THREAD

**Issue by ghost** [pimutils/vdirsyncer#135]
Could it be possible to do the same kind of stuff that have been done for [khal](https://github.com/geier/khal/) in: https://github.com/geier/khal/issues/115 ?

It's also to simplify packaging.

In the mean time there are some missing spaces at the end of those lines: [here](https://github.com/untitaker/vdirsyncer/blob/master/docs/conf.py#L22) and the [next one](https://github.com/untitaker/vdirsyncer/blob/master/docs/conf.py#L23)

Thanks.

**Comment by untitaker** [comment]
This should not be necessary with the version in master.
