### ISSUE TITLE
Integrate iCloud into testsuite

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#149]
Although calendar sync seemed to work fine, there have been some problems with contacts synchronization to iCloud. They're all fixed, but testing against iCloud still would be nice.
##

**Comment by untitaker** [comment]
iCloud doesn't really support the way vdirsyncer currently does collection creation, neither standards-conforming extended MKCOL nor MKCALENDAR works.

iOS usees MKCALENDAR, and the request looks fairly similar to what I've tried.

**Comment by untitaker** [comment]
Trying to switch to MKCALENDAR to accommodate iCloud tripped up ownCloud, see https://bugs.php.net/bug.php?id=69655 and https://github.com/fruux/sabre-dav/issues/603

**Comment by untitaker** [comment]
@geier Somewhere in the khal issue tracker you talked about "Apple developer relations". How does this work?

**Comment by geier** [comment]
You file a bug in the shittest bug tracker the world has seen since the
early nineties and at some undefined time in the future your bug gets
marked as duplicate or won't fix.

Quoting Markus Unterwaditzer (2016-04-01 00:50:38)

**Comment by untitaker** [comment]
cool, cool.

I thought about having iCloud in CI, but without proper MKCOL it won't work.

**Comment by geier** [comment]
the url is http://bugreport.apple.com

Quoting Christian Geier (2016-04-01 00:57:10)

**Comment by untitaker** [comment]
That asscancer again! Everytime I try to log in it redirects me back to the login page.

**Comment by geier** [comment]
In the case of the ill-defined VTIMEZONE they actually claim to have
fixed the problem, as I have no icloud account I cannot test it though.

Quoting Christian Geier (2016-04-01 00:59:18)
