### ISSUE TITLE
WebDAV push notifications?

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#171]
We should keep track of this: http://tools.ietf.org/html/draft-pot-webdav-notifications-00
##

**Comment by untitaker** [comment]
@evert What's the status of that draft? Is there anything better out there?

**Comment by evert** [comment]
That's actually not for push. That draft is a small component for WebDAV / CalDAV / CardDAV sharing. There is some work done on actual Push but not sure what the status is.

**Comment by untitaker** [comment]
Do you have a link for that? I couldn't find anything, first search result is this issue.

**Comment by untitaker** [comment]
Closing this since there is no progress on push.
