### ISSUE TITLE
Discontinue Python 2 support

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#219]
## urlencoding

I used to think that Python 3 will be more daunting in Unicode support, but
I've been wrong: Both Python 2 and 3 have usually been equally hard to support.

Turns out that this was only the case until #218 and #215: urllib and urlparse
are completely broken under Python 2, they don't support unicode strings at
all:

    $ python2
    Python 2.7.10 (default, May 26 2015, 04:16:29) 
    [GCC 5.1.0] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from urllib import quote
    >>> quote(u'lolä')
    /usr/lib/python2.7/urllib.py:1303: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode
     - interpreting them as being unequal
      return ''.join(map(quoter, s))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/urllib.py", line 1303, in quote
        return ''.join(map(quoter, s))
    KeyError: u'\xe4'
    >>> quote('lolä')
    'lol%C3%A4'
    >>> 

Supporting URLs with unicode chars in them was (and is) a major pain in the
ass, on both versions. The stdlib on Python 2 doesn't help.

I'm not going to say that Python 3 is a strictly superior language: In fact I
think it will introduce severe performance regressions, and e.g. the string
model it uses for Unix filesystem APIs is oversimplifying things simply for the
sake of simplicity, not because that makes it more correct. This is wrong in
theory, in practice it would make things easier for me if I didn't have to
support Python 2.

~~I don't want to drop support for Python 2 in the next years, but perhaps stop
fixing unicode bugs on it.~~ FUCK IT

## other things

* threading and `^C`
* Semicolons in config values (found in #317): https://bugs.python.org/issue16374
* Duplicate sections are ignored in configs, see #163 

---

## plan

- [x] show warning... 0.8
- [x] require confirmation through config option... 0.11
- [ ] just crash, remove config option

---

fixes #315 
fixes #316

**Comment by hobarrera** [comment]
+1 for this.

A warning that unicode URLs (and other features) are only supported via python3 might be enough, and a sane approach

On a less conservative approach, I know several large distros *still* don't have python3 as the default python, but is it at least bundled by default? If that's the case, changing the hashbang to `python3` on `setup.py` and a few other places would make picking up python 3 the default (we just need to be sure it's commonly installed).

**Comment by untitaker** [comment]
Not sure that's going to affect anything, most direct installations do `python setup.py install` since `setup.py` is usually not executable.

**Comment by untitaker** [comment]
Another thing is that `^C` doesn't work properly on Python 2.

**Comment by untitaker** [comment]
I've edited the OP to add a few other py2-vs-3 problems that affect vdirsyncer.
