### ISSUE TITLE
Rename vdirsyncer?

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#234]
I wonder if it's too late. The current name is a tongue twister, but I don't know any better ones.

**Comment by dvzrv** [comment]
how about davsyncer?

**Comment by untitaker** [comment]
Would be a very good name, but it's too close to http://davton.co.uk/davsync/ IM=. If I google `davsyncer` it gets corrected to `davsync` automatically.

**Comment by dvzrv** [comment]
irks. wouldn't wanna be confused with that for sure ^^
Hmm... tough one

**Comment by hobarrera** [comment]
> The current name is a tongue twister

I've always pronounced this `v-dir-syncer`. The name does make sense to me, though this does look like a bike-sheding thread.

Maybe it's best to define a "proper" pronunciation?

**Comment by untitaker** [comment]
It does make sense, but I've seen people spell it `vsyncdir` or `vdirsync` before. Not sure the renaming will ever happen though.

**Comment by schachmat** [comment]
Maybe "offlinedav" in the style of offlineimap?

**Comment by slavkoja** [comment]
IMO, current name i OK.

**Comment by untitaker** [comment]
Screw this.
