### ISSUE TITLE
Abook storage backend

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#25]
Writing to the `abook.db` file. This basically would give us the nice CLI interface abook has and make pycarddav obsolete.

**Comment by tristan-k** [comment]
Can you please reopen the issue. I'm trying to use Trojita with Carddav. It currently [lacks](https://bugs.kde.org/show_bug.cgi?id=358485) support for it, but does read abooks adressbook in `~/.abook`. If vdirsyncer would be able to write to abooks storage backend, Trojita would be able use Carddav. Also see this [issue](https://github.com/dglent/vcf2addressbook/issues/1) for a workaround with another python script, which fails for some reason.

**Comment by untitaker** [comment]
Please open a new issue with the stated, more general, goal to integrate
Trojita. I would strongly recommend looking for alternative ways that don't
involve ~/.abook.
