### ISSUE TITLE
Document how to sync with Claws-mail

### ISSUE THREAD

**Issue by gour** [pimutils/vdirsyncer#314]
Hello,

although in the meantime I did switch from Claws-mail to Evolution which does nice job of syncing my calendars/contacts with my Android phone via ownCloud and I left [comment](http://www.thewildbeast.co.uk/claws-mail/bugzilla/show_bug.cgi?id=2658#c10) in Claws' bugzilla in regard, and due to @untitaker's comment on this [issue](https://github.com/scheibler/khard/issues/21), I'm filing submitting this issue if someone find it interesting to provide support for, syncing Claws-mail's contacts/calendars via vdirsyncer.

**Comment by untitaker** [comment]
Claws currently only allows read-only access to a vCard. This can be used in combination with the `singlefile` storage to use CardDAV contacts in Claws, but not edit them in Claws' UI.

**Comment by gour** [comment]
@untitaker hmm, does it mean one would be still able to e.g. edit them within khard and then still have proper syncing with Claws <---> ownCloud <--> Android phone?

**Comment by untitaker** [comment]
Yes, exactly.

The feature missing here is write-support for vCards in Claws-Mail. Everything else already works.

**Comment by gour** [comment]
Well, that would be something, at least...and possibly easier to add remaing support within Claws itself?

**Comment by untitaker** [comment]
Yes.
Native CardDAV support for Claws would be more userfriendly, but that's a major effort.

**Comment by untitaker** [comment]
Concretely:

    [storage foobar]
    type = singlefile
    path = /foo/bar.vcf

    [storage foobaz]
    type = carddav
    url = ...
    username = ...
    password = ...

    [pair asdf]
    a = foobar
    b = foobaz

In claws mail, click "Book -> New VCard", and add that path.

**Comment by gour** [comment]
> In claws mail, click "Book -> New VCard", and add that path.

I'll certainly try that, but wonder if you maybe tried it?

Have to re-create my old Claws setup...

**Comment by untitaker** [comment]
Yes, it works.

Actually since Claws doesn't write to the file, it doesn't matter whether it's open while vdirsyncer is syncing.

**Comment by gour** [comment]
> Yes, it works.

That sounds pretty good. Thank you for support and taking time to test which I'll do as well. ;)

Any hint in regard to calendar syncing support with Claws' vCalendar plugin?

**Comment by gour** [comment]
Of course, another option could be to e.g. use XFCE's Orage instead of Claws' plugin, but the point is not to be fully dependent on GNOME/Evolution...

**Comment by untitaker** [comment]
>Any hint in regard to calendar syncing support with Claws' vCalendar plugin?

Very similar vdirsyncer configuration, then "Subscribe to WebCal" and enter: "file:///foo/bar.ics". Not sure if this was an intended feature by the plugin authors.

I'd apprechiate if you could write a tutorial based on your experience, because I get related questions all the time via private email.

**Comment by untitaker** [comment]
On Thu, Dec 31, 2015 at 08:31:31AM -0800, Gour wrote:
> Of course, another option could be to e.g. use XFCE's Orage instead of Claws' plugin, but the point is not to be fully dependent on GNOME/Evolution...

Orage has no affiliation with GNOME/Evolution and is also very easy to set up.

In contrast to Claws it can also write to the ics files, so full two-way sync
is possible.

**Comment by gour** [comment]
>Very similar vdirsyncer configuration, then "Subscribe to WebCal" and enter: "file:///foo/bar.ics". Not sure if this was an intended feature by the plugin authors.

OK, I'll do some testing.

> I'd appreciate if you could write a tutorial based on your experience, because I get related questions all the time via private email.

OK. Will do. ;)

**Comment by gour** [comment]
> Native CardDAV support for Claws would be more userfriendly, but that's a major effort.

Btw, what do you think about establishing import/export between e.g. khard & Claws' addressbook which keeps contacts in XML file?

**Comment by untitaker** [comment]
I'd rather not mess with Claws' internal database unless one of their devs can
explain why it isn't dangerous.

**Comment by untitaker** [comment]
@gour Are you still interested in writing a tutorial? If not, I'd rather close this issue than keeping it stale and open.

**Comment by gour** [comment]
@untitaker I must admit that after not seeing much interest from the Claws' devs, that I did solve my problem my migrating to Emacs+Gnus where, besides org-mode, I can sync my calendars via org-caldav and importing contacts into org-contacts which I synced between my Android phone and ownCloud...so, Claws is, atm, past tense here. :-(

**Comment by untitaker** [comment]
Alright, I'll close this for now.

**Comment by beli3ver** [comment]
I can write a tutorial if you want

**Comment by untitaker** [comment]
That would be nice! Did you get it to run?

**Comment by beli3ver** [comment]
Yes I did runs perfect 

Von meinem iPhone gesendet

**Comment by untitaker** [comment]
Cool, I'd be happy to merge your PR

On 15 January 2017 15:54:47 CET, Malte Kiefer <notifications@github.com> wrote:
>Yes I did runs perfect 
>
>Von meinem iPhone gesendet
>
>> Am 15.01.2017 um 15:34 schrieb Markus Unterwaditzer
><notifications@github.com>:
>> 
>> That would be nice! Did you get it to run?
>> 
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
>
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/314#issuecomment-272700172

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by beli3ver** [comment]
Which file must I edit 

Von meinem iPhone gesendet

> Am 15.01.2017 um 16:35 schrieb Markus Unterwaditzer <notifications@github.com>:
> 
> Cool, I'd be happy to merge your PR
>

**Comment by untitaker** [comment]
There is no proper folder structure for tutorials yet.

I'd just create a new rst file in the docs folder until I make that. The rst format is similar to markdown, if you prefer markdown, you can write that and I'll convert to rst later

On 15 January 2017 16:43:36 CET, Malte Kiefer <notifications@github.com> wrote:
>Which file must I edit 
>
>Von meinem iPhone gesendet
>
>> Am 15.01.2017 um 16:35 schrieb Markus Unterwaditzer
><notifications@github.com>:
>> 
>> Cool, I'd be happy to merge your PR
>> 
>> On 15 January 2017 15:54:47 CET, Malte Kiefer
><notifications@github.com> wrote:
>> >Yes I did runs perfect 
>> >
>> >Von meinem iPhone gesendet
>> >
>> >> Am 15.01.2017 um 15:34 schrieb Markus Unterwaditzer
>> ><notifications@github.com>:
>> >> 
>> >> That would be nice! Did you get it to run?
>> >> 
>> >> —
>> >> You are receiving this because you commented.
>> >> Reply to this email directly, view it on GitHub, or mute the
>thread.
>> >> 
>> >
>> >
>> >-- 
>> >You are receiving this because you modified the open/close state.
>> >Reply to this email directly or view it on GitHub:
>>
>>https://github.com/pimutils/vdirsyncer/issues/314#issuecomment-272700172
>> 
>> -- 
>> Sent from my Android device with K-9 Mail. Please excuse my brevity.
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
>
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/314#issuecomment-272703097

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by beli3ver** [comment]
Ok I will make a markdown file 
But I think you must wait until tomorrow 

Von meinem iPhone gesendet

> Am 15.01.2017 um 16:51 schrieb Markus Unterwaditzer <notifications@github.com>:
> 
> There is no proper folder structure for tutorials yet.
> 
> I'd just create a new rst file in the docs folder until I make that. The rst format is similar to markdown, if you prefer markdown, you can write that and I'll convert to rst later
>

**Comment by untitaker** [comment]
No problem!

On 15 January 2017 16:54:43 CET, Malte Kiefer <notifications@github.com> wrote:
>Ok I will make a markdown file 
>But I think you must wait until tomorrow 
>
>Von meinem iPhone gesendet
>
>> Am 15.01.2017 um 16:51 schrieb Markus Unterwaditzer
><notifications@github.com>:
>> 
>> There is no proper folder structure for tutorials yet.
>> 
>> I'd just create a new rst file in the docs folder until I make that.
>The rst format is similar to markdown, if you prefer markdown, you can
>write that and I'll convert to rst later
>> 
>> On 15 January 2017 16:43:36 CET, Malte Kiefer
><notifications@github.com> wrote:
>> >Which file must I edit 
>> >
>> >Von meinem iPhone gesendet
>> >
>> >> Am 15.01.2017 um 16:35 schrieb Markus Unterwaditzer
>> ><notifications@github.com>:
>> >> 
>> >> Cool, I'd be happy to merge your PR
>> >> 
>> >> On 15 January 2017 15:54:47 CET, Malte Kiefer
>> ><notifications@github.com> wrote:
>> >> >Yes I did runs perfect 
>> >> >
>> >> >Von meinem iPhone gesendet
>> >> >
>> >> >> Am 15.01.2017 um 15:34 schrieb Markus Unterwaditzer
>> >> ><notifications@github.com>:
>> >> >> 
>> >> >> That would be nice! Did you get it to run?
>> >> >> 
>> >> >> —
>> >> >> You are receiving this because you commented.
>> >> >> Reply to this email directly, view it on GitHub, or mute the
>> >thread.
>> >> >> 
>> >> >
>> >> >
>> >> >-- 
>> >> >You are receiving this because you modified the open/close state.
>> >> >Reply to this email directly or view it on GitHub:
>> >>
>>
>>>https://github.com/pimutils/vdirsyncer/issues/314#issuecomment-272700172
>> >> 
>> >> -- 
>> >> Sent from my Android device with K-9 Mail. Please excuse my
>brevity.
>> >> —
>> >> You are receiving this because you commented.
>> >> Reply to this email directly, view it on GitHub, or mute the
>thread.
>> >> 
>> >
>> >
>> >-- 
>> >You are receiving this because you modified the open/close state.
>> >Reply to this email directly or view it on GitHub:
>>
>>https://github.com/pimutils/vdirsyncer/issues/314#issuecomment-272703097
>> 
>> -- 
>> Sent from my Android device with K-9 Mail. Please excuse my brevity.
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
>
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/314#issuecomment-272703782

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
