### ISSUE TITLE
store vcards by group

### ISSUE THREAD

**Issue by stweller** [pimutils/vdirsyncer#319]
Hi everyone,

first, let me thank for your great work. I am currently using vdirsyncer for khal and khard, but also claws-mail (got it running thanks to the coments in #314). I am now quite happy with one exception: I would like to be able to use the vcard group property (either KIND=group as in the [vCard 4 RFC](https://tools.ietf.org/html/rfc6350#section-6.1.4) or similarly with X-ADDRESSBOOKSERVER-KIND backported to vCard3, as used by e.g. Apple, fastmail, ...). In principle, these properties are in the vCards themselves, so grouping should be done in the client. However, as an intermediate solution for claws-mail, where vCard is not so well supported, I would like vdirsyncer to have the ability to use something like the "singlefile" type that stores the vCards not in one single file, but in one file per group instead. Then it would be relatively easy to set up claws-mail to respect these groups (automatic adding of new group would still not be possible, and support would of course be read-only, but at least the group information would be there).
Note that this kind of storage would have some degree of redundancy, as vCards are allowed to be part of more than one group.
I am willing to do the coding myself, but before I start hacking and initiate a pull request, I wanted to hear whether other users would be interested in this or whether the devs would oppose such a (admittedly not totally elegant) solution.
##

**Comment by untitaker** [comment]
I'm not sure whether it's a good idea to generally conflate addressbooks with categories and groups, so I'd think a special-purpose hack for Claws is the most elegant hack. I have a question though: How should the storage behave if the group property (of whichever variant) is changed? Will the contact be moved from one file to the other?

**Comment by stweller** [comment]
That sounds reasonable. You are right that it is not so straightforward to handle changes in group membership. As a first hack, I would probably just drop the files and then repopulate them. What do you think of the following approach: I am going to write a standalone script (it would probably not need to depend on vdirsyncer,  only vobject or something similar to parse the vCards) that people interested in the functionality can run after "vdirsyncer sync". When #314 is closed, you could include a link to that script for claws-mail users that want groups in their claws address book.

**Comment by untitaker** [comment]
Sounds fine to me.

**Comment by untitaker** [comment]
@stweller #314 is in the works, do you have a script that we can add?

cc @beliv3r

**Comment by untitaker** [comment]
cc @beli3ver

**Comment by stweller** [comment]
Unfortunately I don't have anything ready at the moment, but I will try to get something ready ASAP. Are there any big changes to be expected in python-vdir soon? Because I want to use that to avoid duplicating parsing code.

**Comment by untitaker** [comment]
It is unlikely to change because nobody relies on it. I rather recommend copypasting a stripped-down version of it into your script though and editing it according to your usecase. It is not a very clean abstraction.

**Comment by untitaker** [comment]
@stweller: Are there any updates on this? I am considering closing it.

**Comment by stweller** [comment]
Feel free to close it. I do have a working version for myself, but am not really happy with it, mostly because of the missing vdir library support. If anyone else is interested, I'm willing to help and we can repoen.
