### ISSUE TITLE
Put Katana into CI

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#332]
https://github.com/fruux/sabre-katana
##

**Comment by hobarrera** [comment]
Would a remote server running katana be okay or would you rather set up one locally on-demand?

**Comment by untitaker** [comment]
I'd always prefer local servers. In the case of Davical I took the easier route
because it requires postgres, which is not light on resources. Katana OTOH
seems to be happy with Sqlite, like ownCloud and Baikal.

**Comment by untitaker** [comment]
@evert What is the status on Katana? Is it intended to develop it further?

**Comment by evert** [comment]
I have no intention to develop it further. I pretty much halted work on all projects, but if I werent, the end-goal was to get katana features merged into Baikal.

**Comment by untitaker** [comment]
Okay.
