### ISSUE TITLE
Caldav to Caldav

### ISSUE THREAD

**Issue by rjclutt** [pimutils/vdirsyncer#341]
Im trying to sync one caldav server to another. I can get the initial sync to work, but subsequent sync attempts say file not found. Should I be using local storage as an intermediate step? Here is my config file:

    [general]
    status_path = ~/.vdirsyncer/status/

    # CALDAV
    [pair my_cals]
    a = my_cal_zulu
    b = my_cal_kerio
    collections = ["from a"]
    conflict_resolution = a wins
    metadata = ["displayname"]

    [storage my_cal_zulu]
    type = caldav
    url = http://*****************/zulu/calendars/eSam2016/
    username = ******
    password = ******

    [storage my_cal_kerio]
    type = caldav
    url = https://****************/caldav/users/iowacubs.com/ryanc/
    username = ******
    password = ******

**Comment by untitaker** [comment]
Could you post the full traceback? There doesn't seem to be anything wrong with your config, it should work

**Comment by rjclutt** [comment]
Let me clarify after more testing. sync works fine untill I metasync, then on the next sync I get:

Unhandled exception occured for my_cals/BDD1A693-D148-4350-B6EE-44004043B3A7.
Traceback (most recent call last):
  File "/root/.local/venvs/vdirsyncer/local/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 66, in sync_collection
    force_delete=force_delete
  File "/root/.local/venvs/vdirsyncer/local/lib/python2.7/site-packages/vdirsyncer/sync.py", line 209, in sync
    b_info.prepare_idents()
  File "/root/.local/venvs/vdirsyncer/local/lib/python2.7/site-packages/vdirsyncer/sync.py", line 104, in prepare_idents
    for href, etag in self.storage.list():
  File "/root/.local/venvs/vdirsyncer/local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 756, in list
    for x in DavStorage.list(self):
  File "/root/.local/venvs/vdirsyncer/local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 565, in list
    headers=headers)
  File "/root/.local/venvs/vdirsyncer/local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 322, in request
    return utils.http.request(method, url, session=self._session, **more)
  File "/root/.local/venvs/vdirsyncer/local/lib/python2.7/site-packages/vdirsyncer/utils/http.py", line 96, in request
    raise exceptions.NotFoundError(r.reason)
NotFoundError: Not found

**Comment by untitaker** [comment]
Ok, please paste the full output of `vdirsyncer -vdebug sync` (when it crashes) into a [gist](http://gist.github.com/).

**Comment by untitaker** [comment]
That said I suspect a bug in the server.

Also could I know the vdirsyncer version you're using?

**Comment by rjclutt** [comment]
I will send all this info I the morning. Thanks!

**Comment by rjclutt** [comment]
vdirsyncer --version
vdirsyncer, version 0.9.0

**Comment by rjclutt** [comment]
[https://gist.github.com/rjclutt/021109db8d225bd3c837](url)

**Comment by untitaker** [comment]
Hmm, could you post the output of `vdirsyncer -vdebug discover`?

**Comment by rjclutt** [comment]
vdirsyncer -vdebug discover &> out2.txt

hangs so I stopped it and ran without the redirection. It is prompting to create the cal on b. If I say yes it creates an other cal BDD1A693-D148-4350-B6EE-44004043B3A7 with out the displayname that is empty. I'm posting the output for you as well.

**Comment by rjclutt** [comment]
[https://gist.github.com/rjclutt/7274b1ee5c0ad5ff5fac](url)

**Comment by untitaker** [comment]
(you don't need to use markdown, just post the links. I've edited for you, they were pointing to `github.com/url`)

**Comment by untitaker** [comment]
After `discover`, sync should work?

Do you have any existing collections on side b?

**Comment by rjclutt** [comment]
After discover, sync runs without errors (just warnings), but then I have two cal on the b side. one empty and one with the events minus any new events.

**Comment by rjclutt** [comment]
It is possible to use local storage as an intermediate step? Sync a to local then sync local to b? or will that create more issues?

**Comment by rjclutt** [comment]
Oh and yes there is one existing Cal on the b side.

**Comment by untitaker** [comment]
>It is possible to use local storage as an intermediate step? Sync a to local then sync local to b? or will that create more issues? 

I don't think that would solve anything, but it will/should work.

**Comment by untitaker** [comment]
I guess we can close this? I'm still not sure how this error started. I suspect there *is* a bug in vdirsyncer's discovery, but I'm unsure where to look.

**Comment by rjclutt** [comment]
Any suggestions on alternative methods? to sync once caldav cal to another caldav server?

**Comment by untitaker** [comment]
Sorry, didn't see the other bugs.

**Comment by untitaker** [comment]
I don't think there's another way. This is probably the best one.

Could you list the calendars you have on each side? And how they behave?

**Comment by untitaker** [comment]
Also:

* Are all syncs now finishing without crash?
* please send me `~/.vdirsyncer/status/my_cals.collections`

I wonder if vdirsyncer is syncing the wrong calendars with each other.

**Comment by rjclutt** [comment]
side a "Cub Club Events"
Side b "Cub Club Events" and "Ryan Clutter" and "BDD1A693-D148-4350-B6EE-44004043B3A7" 

yes they finish, but "BDD1A693-D148-4350-B6EE-44004043B3A7" is empty and new events to dont make it over to either cal on b. 


more .vdirsyncer/status/my_cals.collections 
{"cache_key": "a9bd2518ec9a699bd57552e4969571800b1fc5ccfeec5347621db0300188bfbe", "collections": [["BDD1A693-D148-4350-B6EE-44004043B3A7", [{"url": "htt
p://esam.iowacubs.com/zulu/calendars/eSam2016/BDD1A693-D148-4350-B6EE-44004043B3A7/", "collection": "BDD1A693-D148-4350-B6EE-44004043B3A7"}, {"url": "ht
tps://mail.iowacubs.com/full-calendars/iowacubs.com/ryanc/BDD1A693-D148-4350-B6EE-44004043B3A7", "collection": "BDD1A693-D148-4350-B6EE-44004043B3A7"}]]
]}

**Comment by rjclutt** [comment]
sorry I was wrong, each subseqant run of sync wants to create a new BDD1A693-D148-4350-B6EE-44004043B3A7 on b.

**Comment by untitaker** [comment]
For some reason, the server on side B always deletes the calendar that vdirsyncer is trying to create. There's little I can do about that.

Please try creating an event in BDD1A693-D148-4350-B6EE-44004043B3A7 on side B via some other method. Then sync.

If you could make me a test account on side B, I'd be happy to test vdirsyncer against it.

**Comment by untitaker** [comment]
@rjclutt any update on this?

**Comment by rjclutt** [comment]
no update, I have been side tracked on an other project. I will get back to
this next week. I have not given up!
thanks for the follow up.

**Comment by untitaker** [comment]
I will close this due to inactivity. Feel free to post updates whenever you have time though.
