### ISSUE TITLE
An invalid vcf fails the entire sync and cannot be trivially debugged

### ISSUE THREAD

**Issue by hobarrera** [pimutils/vdirsyncer#343]
An invalid vcf is rejected by the CardDav server with a 403 (it's a horrible standard, as we discussed):

```
Unhandled exception occured for contacts_fastmail.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/tasks.py", line 66, in sync_collection
    force_delete=force_delete
  File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 221, in sync
    action(a_info, b_info, conflict_resolution)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 241, in inner
    dest_href, dest_etag = dest.storage.upload(item)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/base.py", line 17, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/base.py", line 17, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line 485, in upload
    return self._put(href, item, None)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line 463, in _put
    headers=headers
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line 322, in request
    return utils.http.request(method, url, session=self._session, **more)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/utils/http.py", line 98, in request
    r.raise_for_status()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url:
https://carddav.messagingengine.com/dav/addressbooks/user/hobarrera@fastmail.com/Default/284327e4-d6dd-487b-866f-113aef5a42d8.vcf
```

This presents two issues

 * Other cards aren't sync'd
 * I can't tell which one is broken

As a solution, I think it's best to:

 * Skip this one and keep trying the rest.
 * Print the name of an offending card when one fails to upload.

**Comment by untitaker** [comment]
Agreed. This should be trivial to implement as a try-except around this loop's body: https://github.com/untitaker/vdirsyncer/blob/d1d4725/vdirsyncer/sync.py#L225-L226

**Comment by untitaker** [comment]
Actually this isn't easy at all.

The try-except block will have to call handle_cli_error, which is unfortunately contained in `vdirsyncer.cli`, which IMO no other non-CLI subpackage/module should rely on.

We'd have to move `handle_cli_error` into `vdirsyncer.exceptions`, and maybe refactor it in the process such that it's possible for `vdirsyncer.sync` to define its own error types without having `handle_cli_error` know about them.

**Comment by untitaker** [comment]
Hmm, this is actually partially solved. The offending item's UID is printed right before trying to upload it ("Copying item {} to {}"). To make this easier to see, do you think it'd be useful if we move tracebacks into the debug log and only show `str(e)`?

And while I think that trying other cards is important, it makes the code so much uglier :(

**Comment by untitaker** [comment]
@hobarrera Is it important to you that other items are uploaded? @sboehringer voiced a similar complaint at https://github.com/pimutils/vdirsyncer/issues/491#issuecomment-242709450, see my reasoning there. I do want to show better error messages for failed uploads though.

**Comment by hobarrera** [comment]
Yes, I'd still want other items to be sync'd (since I'll probably want to deal with the failing one later on, but don't want other to stay out-of-sync). But the error regarding the failed one should still be clearly visible, of course.

**Comment by sboehringer** [comment]
Would it be reasonable to introduce an option to allow, both, the "transactional" and a more lenient sync what's possible behavior? My usage scenario is to sync in the background and the "transactional" behavior has the disadvantage that it could take me days to realize the failure. IMO there is something to be said for both behaviors.

**Comment by untitaker** [comment]
Makes sense, although I would make the fail-fast behavior the default. Is that
fine?

**Comment by sboehringer** [comment]
Absolutely.

**Comment by untitaker** [comment]
I decided to just carry on with sync if uploads fail.
