### ISSUE TITLE
Investigate how tox can be integrated

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#363]
The problem is that we have a lot of possible build combinations (product of all variable values defined in Makefile), and tox doesn't seem to have a versatile enough config format for that purpose. In the past I've always ended up explicitly defining all possible environments (similar to how travis.yml looks now).
##

**Comment by untitaker** [comment]
tox can't do anything here

**Comment by WhyNotHugo** [comment]
Agreed. I think that dockerizing services is as good as it gets for vdirsyncer's tests.

If you manage to also run `vdirsyncer` inside a docker container, it's easy to just use a different base image (eg: python:3.5, python:3.6, etc) for each job.
