### ISSUE TITLE
Syncing http feeds into caldav breaks with collections

### ISSUE THREAD

**Issue by thomwiggers** [pimutils/vdirsyncer#390]
I've got several http feeds I sync into caldav using owncloud. However, since the collections structure has been extended with the release of 0.9, I'm having trouble syncing the ical feeds into caldav. Because the `type=http` storages do not support collections,  synchronisation breaks. Trying to use intermediate local storages (http -> local -> caldav) also fails, since the local storages try to use collections when talking to caldav, but don't when using http. This results in the caldav folders being in `path/collection` while the http-sourced `.ics` files are in `path/`.

I do understand this setup is a bit funky, but it used to work great.

**Comment by untitaker** [comment]
I only removed the default of `null` -- if you set `collections = null` where you didn't have `collections` set, everything should work exactly as before.

**Comment by untitaker** [comment]
@thomwiggers bump

**Comment by thomwiggers** [comment]
Hmm I'm unsure what broke it in the first place, as I'm currently getting things working again... strange.
