### ISSUE TITLE
OwnCloud Bug(?) aborts vdirsyncer

### ISSUE THREAD

**Issue by matthiasbeyer** [pimutils/vdirsyncer#397]
* Your vdirsyncer version: 0.9.3
* Your Python version: 3.4
* Your operating system: NixOS Linux

I get this output on sync:

```
error: m_calendar/contact_birthdays: Storage "m_calendar_remote/contact_birthdays" contains multiple items with the same UID or even content. Vdirsyncer will now abort the synchronization of this collection, because the fix for this is not clear; It could be the result of a badly behaving server. You can try running:
error: 
error:     vdirsyncer repair m_calendar_remote/contact_birthdays
error: 
error: But make sure to have a backup of your data in some form. The offending hrefs are:
error: 
error: '/oc/remote.php/caldav/calendars/m/contact_birthdays/local::3::11.ics'
error: '/oc/remote.php/caldav/calendars/m/contact_birthdays/local::3::88.ics'
```

isn't there a way to continue sync with the other collections but only abort sync for only this collection, as owncloud seems to be buggy here?

**Comment by untitaker** [comment]
This should already be the case, that other collections get synced.

What is your ownCloud version?

On 30 March 2016 09:55:39 CEST, Matthias Beyer <notifications@github.com> wrote:
>* Your vdirsyncer version: 0.9.3
>* Your Python version: 3.4
>* Your operating system: NixOS Linux
>
>I get this output on sync:
>
>```
>error: m_calendar/contact_birthdays: Storage
>"m_calendar_remote/contact_birthdays" contains multiple items with the
>same UID or even content. Vdirsyncer will now abort the synchronization
>of this collection, because the fix for this is not clear; It could be
>the result of a badly behaving server. You can try running:
>error: 
>error:     vdirsyncer repair m_calendar_remote/contact_birthdays
>error: 
>error: But make sure to have a backup of your data in some form. The
>offending hrefs are:
>error: 
>error:
>'/oc/remote.php/caldav/calendars/m/contact_birthdays/local::3::11.ics'
>error:
>'/oc/remote.php/caldav/calendars/m/contact_birthdays/local::3::88.ics'
>```
>
>isn't there a way to continue sync with the other collections but only
>abort sync for only this collection, as owncloud seems to be buggy
>here?
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/397

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by matthiasbeyer** [comment]
owncloud 8.1

**Comment by matthiasbeyer** [comment]
If it is the case: It is not clear from the commandline output, so I'd suggest adding a note that other collections have been synced.

**Comment by untitaker** [comment]
I agree. I'd like to revamp entire output sometime.

ownCloud 9.0 contains a lot of bugfixes, might be worth checking out.

**Comment by untitaker** [comment]
Continuing UI bikeshedding at https://github.com/pimutils/vdirsyncer/issues/398
