### ISSUE TITLE
Show exit status of task

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#398]
The current sync output looks like this:

    Syncing pair/a
    Syncing pair/b
    Syncing pair/c
    error: a crashed

as described in #397, it's unclear whether `pair/b` and `pair/c` got synchronized.

Proposal:

    Syncing pair/a
    Syncing pair/b
    Syncing pair/c
    error: a crashed
    Syncing pair/a: Failure
    Syncing pair/b: Success
    Syncing pair/c: Success

I'm unsure whether this solves the issue. We might as well just document it in the docs.

This is a successor of #96.

**Comment by untitaker** [comment]
@matthiasbeyer @geier @hobarrera Any opinion?

**Comment by matthiasbeyer** [comment]
I like the idea.

**Comment by geier** [comment]
it's not perfect (but I have no better suggestion), but it's probably better than before.

**Comment by hobarrera** [comment]
Slight difference:

```
Syncing pair/a
Syncing pair/b
Syncing pair/c
error: a crashed: <traceback for a here>
Syncing pair/a: Failure
Syncing pair/b: Success
Syncing pair/c: Success
```

What about the exit code? Do we care enough to make a difference between partial failure and complete failure?

**Comment by untitaker** [comment]
>error: a crashed: <traceback for a here>

Whether the error contains the traceback or not depends on the kind of error, so I ommitted it here.

>Do we care enough to make a difference between partial failure and complete failure?

Not at all.

**Comment by untitaker** [comment]
Hmm... this might become really verbose.

What about:

    Syncing pair/a
    Syncing pair/b
    Syncing pair/c
    error: <error for a>
    error: 1 out of 3 tasks failed.

**Comment by untitaker** [comment]
Also note that the lines might get mixed in arbitrary ways, in every case. E.g.:

    Syncing pair/a
    Syncing pair/b
    error: a crashed: <traceback for a here>
    Syncing pair/a: Failure
    Syncing pair/b: Success
    Syncing pair/c
    Syncing pair/c: Success

**Comment by matthiasbeyer** [comment]
mixed lines would be a bit annyoing, though.

**Comment by untitaker** [comment]
@matthiasbeyer In principle I can't do anything about that, but I believe with the last proposal in https://github.com/pimutils/vdirsyncer/issues/398#issuecomment-204154795 it would be the least annoying and least verbose.
