### ISSUE TITLE
Authentication of two Google storages at once will mix lines

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#404]
When syncing both Google calendar and contacts for the first time, it will open both auth urls at the same time, and also prompt for both codes serially.

This needs changes in click-threading.

**Comment by marmarek** [comment]
What about adding documentation like "when syncing google for the first time, sync one pair at the time"?

**Comment by untitaker** [comment]
I guess that's the workaround, but I think it is easy enough to fix this properly.

**Comment by untitaker** [comment]
I'm unsure about the API I want to expose in click-threading. I think I'll have to properly document it before fixing this issue, so others can help :(

**Comment by untitaker** [comment]
Related: https://github.com/click-contrib/click-threading/issues/3
