### ISSUE TITLE
Hardcoded credentials for Google storage type

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#407]
Currently there are hardcoded OAuth credentials for the Google storage type. The precedent for this is [gcalcli](https://github.com/insanum/gcalcli). I wonder though how this is going to fly with packaging.

--

Seeking feedback from

* @hobarrera @eolianoe (ArchLinux)
* @0-wiz-0 (pkgsrc)
* @mbaldessari @mathstuf (Fedora)
* @damiencassou @matthiasbeyer (nix)
* @benjaminfrank (Homebrew)
* @lfam (GNU + Guix)

(could have used the new packaging team for this CC, but at the moment invites are still pending)

**Comment by untitaker** [comment]
[Oops](https://developers.google.com/terms/?hl=th#b-confidential-matters):

>Developer credentials (such as passwords, keys, and client IDs) are intended to be used by you and identify your API Client. You will keep your credentials confidential and make reasonable efforts to prevent and discourage other API Clients from using your credentials. Developer credentials may not be embedded in open source projects.

**Comment by mathstuf** [comment]
I think the normal way to do this is to code it up so that the user can grab their own API client key for use locally. If that means they need to sign up to be a Google Developer themselves, Google needs to figure out a better way…

**Comment by hobarrera** [comment]
> I think the normal way to do this is to code it up so that the user can grab their own API client key for use locally. If that means they need to sign up to be a Google Developer themselves, Google needs to figure out a better way…

I'd much rather embed a code (even if it's against the recommendations), than force users to register as google developers and grab a key just to use this.

We can, of course, have a distro-specific key if upstream would rather not provide one.

**Comment by untitaker** [comment]
That's not a recommendation, it's the ToS.

On 6 April 2016 17:24:16 CEST, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>> I think the normal way to do this is to code it up so that the user
>can grab their own API client key for use locally. If that means they
>need to sign up to be a Google Developer themselves, Google needs to
>figure out a better way…
>
>I'd much rather embed a code (even if it's against the
>recommendations), than force users to register as google developers and
>grab a key just to use this.
>
>We can, of course, have a distro-specific key if upstream would rather
>not provide one.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/407#issuecomment-206425882

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hobarrera** [comment]
> That's not a recommendation, it's the ToS.

Given that the ToS forbid including a credential, do they explain how users are supposed to deal with this?

**Comment by mathstuf** [comment]
Not use FOSS. Obviously.

More seriously, OAuth really doesn't have a FOSS-friendly workflow (AFAIK). If the key is found in the open, Google is likely to just disable it, blocking everyone's access with vdirsyncer. The only ToS-compatible way I've heard of for OAuth is to add code for users to fetch their own client API key.

**Comment by geier** [comment]
well, we could always XOR our API key in the source code, that makes the `credentials confidential` and is a `reasonable efforts to prevent and discourage other API Clients from using your credentials`.
