### ISSUE TITLE
google_calendar client_id using fetch gets a `+` appended to the end

### ISSUE THREAD

**Issue by terlar** [pimutils/vdirsyncer#417]
* vdirsyncer version: 0.9.4.dev35+ng777eb35
* Python version: 3.5.1
* OS: Linux 4.4.5-1-ARCH

config:
```ini
[general]
status_path = ~/.vdirsyncer/status/

# Calendar
[pair work_calendar]
conflict_resolution = b wins
a = work_calendar_local
b = work_calendar_remote
collections = ["from a", "from b"]
metadata = ["color", "displayname"]

[storage work_calendar_local]
type = filesystem
path = ~/.calendars/work/
fileext = .ics

[storage work_calendar_remote]
type = google_calendar
token_file = ~/.google-token-work
client_id.fetch = ["command", "secret", "mail/work", "client_id"]
client_secret.fetch = ["command", "secret", "mail/work", "client_secret"]
```

When I do the sync I will get Error 401 (OAuth2 Error) with message: `Error: invalid_client`

When I inspect the parameters sent I see that there is a `+` appended to my client_id parameter at the very end. Removing this makes the URL work correctly and I can generate a key. However then it still seems the vdirsyncer uses the wrong client_id internally, because then it will complain about the oauth client.

output:
```
$ vdirsyncer sync
Detected change in config file, discovering collections for work_calendar
Discovering collections for pair work_calendar
Opening https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=XXX.apps.googleusercontent.com+&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar&state=XXX&approval_prompt=force&access_type=offline ...
Follow the instructions on the page.
Paste obtained code: XXX
Unhandled exception occured.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/utils.py", line 452, in _worker
    func(wq=self)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/tasks.py", line 20, in prepare_pair
    status_path=config.general['status_path'], pair=pair
  File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/utils.py", line 185, in collections_for_pair
    rv = list(_collections_for_pair_impl(status_path, pair))
  File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/utils.py", line 277, in _collections_for_pair_impl
    b_discovered = _discover_from_config(pair.config_b)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/utils.py", line 236, in _discover_from_config
    return handle_storage_init_error(cls, config)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/utils.py", line 228, in _discover_from_config
    discovered = list(cls.discover(**config))
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line 383, in discover
    session, _ = cls.session_class.init_and_remaining_args(**kwargs)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line 301, in init_and_remaining_args
    return cls(**self_args), remainder
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/google.py", line 81, in __init__
    client_secret=client_secret,
  File "/usr/lib/python3.5/site-packages/requests_oauthlib/oauth2_session.py", line 236, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 409, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 376, in parse_token_response
    validate_token_parameters(params)
  File "/usr/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 383, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 271, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientError: (invalid_client) The OAuth client was not found.
```

When I enter the `client_id` and `client_secret` without the eval this procedure works. However it fails with another error, but that is unrelated.

**Comment by terlar** [comment]
On a second thought that + might be an extra space included from my eval converted to URL encoding. Still a trim would be nice.

**Comment by terlar** [comment]
Still seems the `+` gets appended even I have made sure my input is not generating any whitespace or newline at the end, so my theory was wrong.

**Comment by untitaker** [comment]
We already strip all whitespace from the end. How does your `secret` command look like?

**Comment by terlar** [comment]
I have gotten this to work now, I think I might have had some white-space or new-line at the end. The `secret` command is a wrapper around `pass` (https://github.com/terlar/dotfiles/blob/master/bin/.local/bin/secret). It will output a string without space or newline in the end. It might be that it was fixed after I added that `tr` stripping away the newline.

Currently it is working. I also had an issue where I was using the same `client_id` and `client_secret` for offlineimap causing them to conflict, it could only be used by one at a time, since both will generate different tokens.

I will close this as I have gotten this to work.

**Comment by untitaker** [comment]
Glad you got it to work! I'm unsure how OfflineIMAP could interfere, did you use the same token_file for both?

**Comment by terlar** [comment]
I were using the same `client_id` and `client_secret` for both of them, so then I requested a `refresh_token` and an `access_token`. It tried to copy this from the one I used with OfflineIMAP into the token JSON files and also the other way around, but I guess the tokens gave access to different things, since vdirsyncer requested accessing the calendars and contacts, while the OfflineIMAP requested to have access to IMAP things. So it is not that strange that I could not share these credentials when you think about it like that.

And everytime I generate one for OfflineIMAP, the one for Vdirsyncer got deactivated and vice versa, since it seems you can only have one `refresh_token`/`access_token` active per client id/secret pair. The solution was to use two different client id/secret pairs.

This in conjunction with my `secret` command outputing something that caused the addition of `+` had me confused for quite some time.

Thank you for your help and great software. :smile:
