### ISSUE TITLE
Better documentation for metasync

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#422]
`metasync` is barely documented. We should elaborate on it in the main tutorial.

**Comment by geier** [comment]
Agree! 

Am 9. April 2016 15:43:50 MESZ, schrieb Markus Unterwaditzer <notifications@github.com>:
>`metasync` is barely documented. We should elaborate on it in the main
>tutorial.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/422

-- 
Sent from my phone. Please excuse my brevity.

**Comment by untitaker** [comment]
Patches welcome :)
