### ISSUE TITLE
Collection names have to be guessed by the user

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#424]
The concept of a "collection name" is not exposed through UIs outside of vdirsyncer. Consequently the user doesn't know a thing about them, and when wanting to explicitly define them (i.e. not just use `["from a", "from b"]`), they are left guessing.

#421 was an attempt at fixing this, but I think we could do better:

## Select by displayname

    [pair foo]
    # both mean the same thing
    collections = ["displayname/Marco's work calendar"]
    collections = ["work"]
   
## Have a command for listing collections

`vdirsyncer discover --list foo` would list all collection names including displayname. Then you can just copypaste them into the config

**Comment by untitaker** [comment]
Any opinions on which option to choose? I only want to implement either the new command or the new config syntax.

**Comment by marmarek** [comment]
The second one would be more unambiguous (for example in case of creating new calendars later).

**Comment by untitaker** [comment]
Do you mean the command or config syntax? (I swapped order in my comment)

**Comment by marmarek** [comment]
The command.

**Comment by hobarrera** [comment]
+1 to a new command. This can also grow in future to some set of commands "interactively" configure vdirsyncer, maybe.

**Comment by untitaker** [comment]
@hobarrera Interactive configuration was a first thought for implementing #420, but it would pull in urwid and be hard to test.

**Comment by hobarrera** [comment]
I was actually thinking about something like:

```
Enter a collection URL:
 <prompt>
Enter the collections local path:
 <prompt>
(etc)
```

So subcommands can do (partial) reconfiguration.

**Comment by untitaker** [comment]
Yeah... maybe another time... :sweat_smile:
