### ISSUE TITLE
Test against pypy Python 3 in CI

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#429]
I want vdirsyncer to be able to run on some version of Pypy. If we're going to kill support for Python 2, we should activate the pypy3 Python version in Travis.

**Comment by hobarrera** [comment]
pypy3 support python 3.2.5, but I believe we need python3.3 for vdirsyncer.

While testing this locally, building `lxml` fails locally on pypy3.

**Comment by untitaker** [comment]
Once we go Python 3 only, it might be doable to support Python 3.2. We'll see.

**Comment by untitaker** [comment]
Nvm supporting Python 3.2 is absolutely impossible because every 2-3-compatible dependency doesn't support it.

**Comment by untitaker** [comment]
Actually this is possible, because even though PyPy3 supports only Python 3.2, it also has support for https://www.python.org/dev/peps/pep-0414/ (which was introduced in CPython 3.3). Regarding LXML, see https://github.com/pimutils/vdirsyncer/issues/433

**Comment by untitaker** [comment]
As of http://doc.pypy.org/en/latest/release-pypy3.3-v5.5.0.html this should be possible now.
