### ISSUE TITLE
macos launchd .plist

### ISSUE THREAD

**Issue by benjaminfrank** [pimutils/vdirsyncer#430]
I created a vdirsyncer.plist (somewhat like a cronjob) to have vdirsyncer run every minute. would something like this qualify for inclusion into mainline? I am asking because of https://github.com/Homebrew/homebrew-core/pull/348
maybe the default values should be a bit more conservative as well...

**Comment by benjaminfrank** [comment]
I can easily ceate a PR. where would I put such a crontrib script? make a new contrib folder or something?

**Comment by hobarrera** [comment]
What's the difference between a plain-old crontab entry and a plist file? (not an OS X user, so I simply don't know).

**Comment by benjaminfrank** [comment]
crontab is deprecated on mac and its functionality included in launchd (the thing that runs those .plist files). launchd also autostarts & keeps daemons alive and all this fancy stuff

**Comment by untitaker** [comment]
What happens if vdirsyncer itself takes longer than a minute? Is a second job spawned?

In principle I wouldn't run two sync processes on the same collection, although the race condition created by it seems to be extremely unlikely.

In principle I'd happily merge configuration files that could be reused between distros (systemd files come to mind), but I'm somewhat reluctant about cronjobs because of the uncertainity above. I'd much rather solve #24 but that one has a long way to go.

**Comment by benjaminfrank** [comment]
Yes, a second one is run. Maybe launchd has some facility to prevent this, I need to check.
On vdirsyncer side a pid file could alleviate this issue, although #24 sounds good as well.
maybe I'll check into the pid file thing, that should be reasonably easy to implement

**Comment by untitaker** [comment]
Ideally one would have one PID file per collection, stored in the status directory in a similar scheme to .items files

On 18 April 2016 08:46:52 CEST, benjaminfrank <notifications@github.com> wrote:
>Yes, a second one is run. Maybe launchd has some facility to prevent
>this, I need to check.
>On vdirsyncer side a pid file could alleviate this issue, although #24
>sounds good as well.
>maybe I'll check into the pid file thing, that should be reasonably
>easy to implement
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/430#issuecomment-211229427

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by benjaminfrank** [comment]
Ok, launchd already prevents a second instance of vdirsyncer to be run if execution takes longer than the time intervall: http://apple.stackexchange.com/questions/94803/does-launchagent-prevent-repetitive-execution-of-jobs

**Comment by untitaker** [comment]
Excellent, feel free to open a PR! I'd like to have a subfolder (misc?) containing files like this.

**Comment by untitaker** [comment]
Fixed by #435
