### ISSUE TITLE
pypi 0.10.0 missing?

### ISSUE THREAD

**Issue by mbaldessari** [pimutils/vdirsyncer#442]
I used to download vdirsyncer from pypi for my rpm packaging. I just noticed 0.10.0 is missing:
https://pypi.python.org/pypi?%3Aaction=search&term=vdirsyncer&submit=search

Is pypi deprecated or was it just an oversight?

Cheers,
Michele

**Comment by mbaldessari** [comment]
My browser (or me) is drunk. Sorry for the noise

**Comment by untitaker** [comment]
Pypi crashed during the upload (but the release seemed to have succeeded anyway), it might be that it is drunk, not you.

On 3 May 2016 10:16:04 CEST, Michele Baldessari <notifications@github.com> wrote:
>I used to download vdirsyncer from pypi for my rpm packaging. I just
>noticed 0.10.0 is missing:
>https://pypi.python.org/pypi?%3Aaction=search&term=vdirsyncer&submit=search
>
>Is pypi deprecated or was it just an oversight?
>
>Cheers,
>Michele
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/442

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
