### ISSUE TITLE
Getting 200 instead of 207 status code. Partially invalid XML response.

### ISSUE THREAD

**Issue by ploth** [pimutils/vdirsyncer#452]
* Your vdirsyncer version 0.7.3
* Your Python version 3.5.1
* Your operating system Arch Linux
* Your config file

```
[pair DualPersonalCalendar]
a = DualPersonalCalendarLocal
b = DualPersonalCalendarRemote
metadata = ["DualPersonal", "blue"]

[storage DualPersonalCalendarLocal]
type = filesystem
path = ~/.calendars/DualPersonal/
fileext = .ics

[storage DualPersonalCalendarRemote]
type = caldav
url = https://hulks.dual.tu-harburg.de/groupware/calendars/f64215a788cfbafd736a1c8e105fe811cd04a4
username = 
password =
```

* Use `vdirsyncer -vdebug` for debug output.

```
debug: Loaded status for DualPersonalCalendar
debug: PROPFIND https://hulks.dual.tu-harburg.de/groupware/calendars/f64215a788cfbafd736a1c8e105fe811cd04a49a/45/
debug: {'Depth': 1, 'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8'}
debug: <?xml version="1.0" encoding="utf-8" ?>
debug:             <D:propfind xmlns:D="DAV:">
debug:                 <D:prop>
debug:                     <D:resourcetype/>
debug:                     <D:getcontenttype/>
debug:                     <D:getetag/>
debug:                 </D:prop>
debug:             </D:propfind>
debug:             
debug: Sending request...
debug: 200
debug: {'Keep-Alive': 'timeout=5, max=99', 'Connection': 'Keep-Alive', 'Date': 'Wed, 18 May 2016 20:54:08 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Content-Length': '158', 'Vary': 'Accept-Encoding', 'Server': 'Apache/2.4.10 (Debian)', 'Content-Encoding': 'gzip', 'X-API': 'http://www.tine20.org/apidocs/tine20/'}
debug: b"<br />\n<b>Fatal error</b>:  Class 'Calendar_Convert_Event_VCalendar_BusyCal' not found in <b>/var/www/html/groupware/Calendar/Convert/Event/VCalendar/Factory.php</b> on line <b>114</b><br />\n"
warning: Partially invalid XML response, some of your items may be corrupted. Check the debug log and consider switching servers. (<string>:2:1:FATAL:PARSER:ERR_DOCUMENT_END: Extra content at the end of the document)
```

- I tried another calendar on the same server without any appointments and I'm getting the same error.
- I have changed the password and I still get the error.
- The first difference is the status code of 200 instead of 207 compared to another working calendar (EDIT: On a different server).
- I've searched for any part of the error messages and got no results.

Do you have any hints? :(

**Comment by untitaker** [comment]
This server response (from your paste) seems really problematic:

    <br />
    <b>Fatal error</b>:  Class 'Calendar_Convert_Event_VCalendar_BusyCal' not found in <b>/var/www/html/groupware/Calendar/Convert/Event/VCalendar/Factory.php</b> on line <b>114</b><br />

If you hadn't said that other calendars worked, I would've guessed that e.g. an update of your server crashed halfway through. It's particularly interesting that it responds with a status code of 200 OK, since not finding your class definitions is pretty far from OK.

Those working calendars -- do they really work in the sense that vdirsyncer is able to download all of their events? What does the debug output of a full sync look like for those?

**Comment by ploth** [comment]
Oh sorry, vague explanation. The "another working calendar" is on a different server and just working flawless.

The status code 200 is indeed very weird.

**Comment by untitaker** [comment]
Is there any calendar on that server that works, with any DAV client?

If not, I suspect the server is just completely broken (and not just buggy). As said, a update/installation gone wrong is a possibility. I don't have any experience with that particular software, but it really does seem like one or two PHP files are missing.

**Comment by ploth** [comment]
As far as I know around 10 people set up exactly this calendar on their DAV clients.

I'm not informed about any update/installation errors.

**Comment by untitaker** [comment]
I'm currently digging into [Tine's](http://www.tine20.com/willkommen-community/) sourcecode. They appear to [detect a lot of clients by useragent, applying special rules for no documented reason](https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/tree/master/tine20/Calendar/Convert/Event/VCalendar).

The error message you posted contains a line number that doesn't match with the sourcecode from that repository. Which version of Tine are you running? Is this the community or business edition?

**Comment by ploth** [comment]
Wow, I am very impressed. Tine 2.0 Version: Egon (2016.03.2). I think it is the community version. There seems no difference around line 114 between the master and 2016.03 branch.

**Comment by ploth** [comment]
The server reports correctly that there is no _Calendar_Convert_Event_VCalendar_BusyCal_

**Comment by untitaker** [comment]
I have no idea why BusyCal is even mentioned in your Tine installation, since it's nowhere in the sourcecode.

Do you have access to your server? Can you do `grep -ri busycal` on the root directory?

**Comment by ploth** [comment]
Yeah, I checked their repo also. I will open up an issue over there. Cause I have to access to the server I will ask the admin. Thank you very much!

**Comment by untitaker** [comment]
Regarding the server access: The Tine people might have a complete answer that might make server access unnecessary.

**Comment by ploth** [comment]
Just for reference: [https://forge.tine20.org/view.php?id=11874](url)

**Comment by untitaker** [comment]
Your markdown formatting in that post is broken, you mixed label with URL. Alternatively just paste the URL without any formatting.

On 19 May 2016 01:16:31 CEST, Pascal Loth <notifications@github.com> wrote:
>Just for reference: [https://forge.tine20.org/view.php?id=11874](url)
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/452#issuecomment-220185926

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
I'll close this issue for now since there's no indication that this is a bug in vdirsyncer.
