### ISSUE TITLE
vdirsyncer fails with `vdirsyncer.exceptions.NotFoundError`

### ISSUE THREAD

**Issue by protist** [pimutils/vdirsyncer#454]
* Your vdirsyncer version: 0.10.0
* Your Python version: 3.5.1
* Your operating system: (Arch) Linux
* Server: Raspbian (Debian) Raspberry Pi running OwnCloud 8.1.7-12.1. 
Config as per issue #443.
```
$ vdirsyncer -vdebug sync
...
Unhandled exception occured for owncloud_contacts/contacts.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/tasks.py", line 66, in sync_collection
    force_delete=force_delete
  File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 216, in sync
    b_info.prepare_idents()
  File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 124, in prepare_idents
    if prefetch else ()):
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line 450, in get_multi
    raise exceptions.NotFoundError(href)
vdirsyncer.exceptions.NotFoundError: /owncloud/remote.php/carddav/addressbooks/protist/contacts/20140720T112939.e604e456d0@foo.dynu.com.vcf
error: 1 out of 2 tasks failed.
```
This often aborts on different contact IDs when run again. I'm not really sure how to get the raw vcf data from OwnCloud, but I checked the contact IDs from pycardsyncer. The only obvious unifying factor in these contacts is the presence of the field:
```
X-MOZILLA-HTML:FALSE
```
I'm happy to troubleshoot from the OwnCloud end (i.e. by testing removal of this field), but I'm not sure how to manually remove this field (it's not exposed via the web interface).

**Comment by untitaker** [comment]
Could you post the debug log again?

On 24 May 2016 03:42:21 CEST, protist <notifications@github.com> wrote:
>* Your vdirsyncer version: 0.10.0
>* Your Python version: 3.5.1
>* Your operating system: (Arch) Linux
>* Server: Raspbian (Debian) Raspberry Pi running OwnCloud 8.1.7-12.1. 
>Config as per issue #443.
>```
>$ vdirsyncer -vdebug sync
>...
>Unhandled exception occured for owncloud_contacts/contacts.
>Traceback (most recent call last):
>File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/tasks.py", line
>66, in sync_collection
>    force_delete=force_delete
>File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 216,
>in sync
>    b_info.prepare_idents()
>File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 124,
>in prepare_idents
>    if prefetch else ()):
>File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line
>450, in get_multi
>    raise exceptions.NotFoundError(href)
>vdirsyncer.exceptions.NotFoundError:
>/owncloud/remote.php/carddav/addressbooks/protist/contacts/20140720T112939.e604e456d0@foo.dynu.com.vcf
>error: 1 out of 2 tasks failed.
>```
>This often aborts on different contact IDs when run again. I'm not
>really sure how to get the raw vcf data from OwnCloud, but I checked
>the contact IDs from pycardsyncer. The only obvious unifying factor in
>these contacts is the presence of the field:
>```
>X-MOZILLA-HTML:FALSE
>```
>I'm happy to troubleshoot from the OwnCloud end (i.e. by testing
>removal of this field), but I'm not sure how to manually remove this
>field (it's not exposed via the web interface).
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/454

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by protist** [comment]
I originally didn't post the whole log because the vast majority of it was personal information. It seems to dump all of my contacts to standard out. However, here is the full standard error.
```
warning: Skipping '/owncloud/remote.php/carddav/addressbooks/protist/contacts/', etag property is missing.
warning: Server sent unsolicited item: /owncloud/remote.php/carddav/addressbooks/protist/contacts/
Unhandled exception occured for owncloud_contacts/contacts.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/tasks.py", line 66, in sync_collection
    force_delete=force_delete
  File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 216, in sync
    b_info.prepare_idents()
  File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 124, in prepare_idents
    if prefetch else ()):
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line 450, in get_multi
    raise exceptions.NotFoundError(href)
vdirsyncer.exceptions.NotFoundError: /owncloud/remote.php/carddav/addressbooks/protist/contacts/20140720T112824.608094278c@smog.dynu.com.vcf
error: 1 out of 2 tasks failed.
```
I've sanitised the standard out, but I may have missed something, so I'll just email it to you. Thank you again for your assistance.

**Comment by protist** [comment]
This was probably some issue with OwnCloud. I updated to the latest 9.0.2, which did not fix it. However, when I exported my contacts then re-imported them, vdirsyncer worked fine.
