### ISSUE TITLE
google_calendar implementation adds junk data to token files

### ISSUE THREAD

**Issue by terlar** [pimutils/vdirsyncer#456]
At some point vdirsyncer appends extra data to the end of the generated token
file. It seems it is based of the original string, but it gets some extra
chars. Currently it has appended an extra `}` at the end which means it doesn't
parse as proper JSON. I have had other instances with some other characters of
the end of the string repeated at the very end.

I have a script that runs `vdirsyncer sync` as a background task, so I am not
sure at what point this happens. If I fix the token file manually it will work
for the several next runs and I will end up noticing this error a few days
later when I start wondering why my calendar is not synced. Then when I
run `vdirsyncer sync` I see this issue.

This might be related to running two accounts using `google_calendar` with token files. But I have not verified this.

* vdirsyncer version 0.10.1.dev48+ng139182e
* Linux 4.5.4-1-ARCH
* Python 3.5.1

config file:
```ini
[general]
status_path = ~/.vdirsyncer/status/

[pair work_calendar]
conflict_resolution = b wins
a = work_calendar_local
b = work_calendar_remote
collections = ["from a", "from b"]
metadata = ["color", "displayname"]

[storage work_calendar_local]
type = filesystem
path = ~/.calendars/work/
fileext = .ics

[storage work_calendar_remote]
type = google_calendar
token_file = ~/.vdirsyncer/google-token-work
client_id = ***
client_secret = ***

[pair personal_calendar]
conflict_resolution = b wins
a = personal_calendar_local
b = personal_calendar_remote
collections = ["from a", "from b"]
metadata = ["color", "displayname"]

[storage personal_calendar_local]
type = filesystem
path = ~/.calendars/personal/
fileext = .ics

[storage personal_calendar_remote]
type = google_calendar
token_file = ~/.vdirsyncer/google-token-personal
client_id = ***
client_secret = ***
```

output:
```
$ vdirsyncer -vdebug sync
debug: Using 1 maximal workers.
Syncing personal_calendar/***
debug: Loaded status for personal_calendar/***
Unhandled exception occured for personal_calendar/***.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/tasks.py", line 62, in sync_collection
    b = storage_instance_from_config(collection.config_b)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/utils.py", line 431, in storage_instance_from_config
    return handle_storage_init_error(cls, new_config)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/utils.py", line 422, in storage_instance_from_config
    return cls(**new_config)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/google.py", line 123, in __init__
    **kwargs
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line 697, in __init__
    super(CaldavStorage, self).__init__(**kwargs)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line 370, in __init__
    self.session_class.init_and_remaining_args(**kwargs)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line 297, in init_and_remaining_args
    return cls(**self_args), remainder
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/google.py", line 41, in __init__
    token = json.load(f)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 240 (char 239)
```

token file:
```json
{"expires_at": 1464265889.161628, "expires_in": 3600, "access_token": "***", "refresh_token": "***", "token_type": "Bearer"}}
```

As you can see in the token file above there is an extra `}`.

**Comment by untitaker** [comment]
I already have a suspicion. Could you see if this problem also happens if you run `vdirsyncer sync` with the `--max-workers=1` option?

**Comment by terlar** [comment]
Thank you for the hint, I will try out with this option. One of the two token files were broken now when I checked, so I will try out to change my scheduled sync to use the `--max-workers=1` and let it run for a while, if the issue is gone I guess we can assume it is working. Unfortunately I don't know about the timeline for the verification as I am not sure when this happens, it is deffinately not every time.

**Comment by untitaker** [comment]
JFTR/"inner monologue": I suspect that multiple worker threads try to refresh the OAuth access tokens at the same time, and therefore write to the same file at the same time. Ideally we would try to refresh the token only once, but I'm not sure how easy that is to coordinate without polluting internal APIs.

**Comment by terlar** [comment]
Follow-up, so I have been using the `--max-workers=1` for two days now and haven't experienced this issue during this time. So I'd say your suspicions seemed to be head on. Let me know if I can help in further debugging.

**Comment by untitaker** [comment]
@terlar please try out #460 (again for a few days, now with `--max-workers` removed).

**Comment by untitaker** [comment]
Argh, nevermind. I'll find a different solution.

**Comment by untitaker** [comment]
I realized that this can be solved by an optimal solution for https://github.com/pimutils/vdirsyncer/issues/404. However, an optimal solution for that issue takes a while...

**Comment by untitaker** [comment]
@terlar: Now it's ready! Please try #460

**Comment by terlar** [comment]
I have switched to use the commit from this branch and running without `max-workers` options. Will run it for a few days from now on and see how it goes. Thanks for the fix.

**Comment by untitaker** [comment]
@terlar any news?

**Comment by terlar** [comment]
@untitaker Yes, I have been running this for 4 days now and running the sync about every 15 minutes without any issues (without `max-workers`). So I would consider this to be working. :+1:

**Comment by untitaker** [comment]
To verify, what is your version of the `click-threading` package?

**Comment by terlar** [comment]
`python-click-threading` version: `0.4.0`

**Comment by untitaker** [comment]
Yay!
