### ISSUE TITLE
apple calendar server discover issue

### ISSUE THREAD

**Issue by c-schwamborn** [pimutils/vdirsyncer#457]
server:
apple calendarserver 4.2-1~tree.se on debian wheezy
(this is not by choice, I have to get it working - somehow)

client:
debian jessie
vdirsyncer 0.11.0
clientpython 2.7.9-2

config:
[general]
status_path = ~/.vdirsyncer/status/
python2 = true

[pair muman_contacts]
a = muman_contacts_local
b = muman_contacts_remote
collections = ["from a", "from b"]
metadata = ["displayname"]
conflict_resolution = "b wins"

[storage muman_contacts_local]
type = filesystem
path = ~/dav-sync/contacts/
fileext = .vcf

[storage muman_contacts_remote]
type = carddav
#url = https://agenda.architektur.tu-darmstadt.de/
#or
url = https://agenda.architektur.tu-darmstadt.de
#same result
username = muman
password = password

[pair muman_calendar]
a = muman_calendar_local
b = muman_calendar_remote
collections = ["from a", "from b"]
metadata = ["displayname", "color"]
conflict_resolution = "b wins"

[storage muman_calendar_local]
type = filesystem
path = ~/dav-sync/calendars/
fileext = .ics

[storage muman_calendar_remote]
type = caldav
#url = https://agenda.architektur.tu-darmstadt.de/
#or
url = https://agenda.architektur.tu-darmstadt.de
#same result
username = muman
password = password

[vdirsyncer_debug-log.txt](https://github.com/pimutils/vdirsyncer/files/289566/vdirsyncer_debug-log.txt)

The issue seems to be those '200 - permanently moved' answers. Several client libs I tried can not handle this server behavior.

**Comment by untitaker** [comment]
The server appears to think you're unauthenticated. Could you try setting `auth = basic` in your DAV section?

**Comment by c-schwamborn** [comment]
Hello Markus,

that worked for me, you can close the ticket, except you want to 
implement a more meaningful error message.

Thank you
Christian

**Comment by untitaker** [comment]
We might change the default to `auth = basic`. If that is not happening, we might want to improve the error message.
