### ISSUE TITLE
Make auth = basic the default again

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#461]
`auth = guess`, as implemented in #57 (#33), was a bad idea to have as default:

* It causes performance issues and confusing server logs, as in #293, #446 
* Apparently Darwin Calendar Server breaks with anything but preemptive auth, see #457 

@geier I'm not sure if I ever asked you this, but is there a particular server you know of that doesn't support preemptive basic auth?

I plan to ask on the CalConnect mailing list on what the best client behavior is.

**Comment by geier** [comment]
no, I know of no servers that don't support basic auth.

Quoting Markus Unterwaditzer (2016-06-07 13:06:38)
