### ISSUE TITLE
Filesystem `update` race condition

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#462]
This has been spooking around in my head since at least a year. I have no idea how to solve it, but if nothing else, we need to document it.
## Introduction

The vdirsyncer storage API has two operations for writing events/contacts ("items"): `upload` and `update`. 

(The following is a simplified representation that ignores the differences between hrefs and UIDs, and asserts that hrefs are always directly derived from UIDs)
- `upload(item) -> etag`: If an item doesn't already exist with that UID, add `item` to the storage. Otherwise raise an error.
- `update(item, etag) -> new_etag`: If an item with the given `item`'s UID already exists and its etag is `etag`, replace it with `item`. Otherwise raise an error.

All of this is supposed to happen "atomically" (depending on the exact storage type):
- It must be impossible to call `upload(item)` rapidly at the same time with items that have the same UID, and get more than one success (=no errors).
- It must be impossible to call `update(item, etag)` rapidly at the same time with the same etag and get more than one success.

For the storage types `*dav`, `remotestorage`, `google_*`, we basically rely on the server to fullfill this guarantee.
## Problem

`filesystem` storage is tricker in that regard. Assuming that each item is called `<UID>.txt` in the folder `V`:
- `upload`:
  1. Create a temporary file in `V`, write the entire item to it.
  2. Call `link()` to create a second hardlink for the temporary file under the correct filename. This will fail if the target file already exists.
  3. To clean up (both in case of success or error), `unlink` the file from the temporary filename.
  
  Also the temporary file has the file extension `.tmp`, such that it is ignored when listing items, should it be left over for some reason (power loss).
  
  This implementation fullfills the above requirement for `upload`: It is impossible to `link` two files to the same filepath at the same time.
- `update`: Complete trashfire.
  1. Read `etag` from existing file. If the file doesn't exist, error. If the `etag` doesn't match, error.
  2. Create temporary file.
  3. Write to temporary file.
  4. `rename()` temporary filename to correct filename. This removes the previously existing file.
  
  Directly after Step 1, anything can happen. For example, two `update` operations from two clients could happen at the same time. Both clients read the etag, and see that it matches. Then they both overwrite the existing file. Both operations succeed, but only one item actually gets written. The other item is lost.

To be honest I doubt anything of this matters. As far as I can tell, no vdir-software other than vdirsyncer actually checks the etags before writing items.

Awaiting your comments. In hindsight this reads like rambling.

**Comment by geier** [comment]
`.lock` files? :smiling_imp:

**Comment by untitaker** [comment]
Lockfiles, POSIX advisory file locks, etc. would require that each program supports and respects them. At least under POSIX it's an opt-in thing rather than enforcable.

**Comment by untitaker** [comment]
I'm closing this, I'm content with this being only documented in the issue tracker,
