### ISSUE TITLE
fails syncing google calendar with vdirsyncer.exceptions.NotFoundError

### ISSUE THREAD

**Issue by waynew** [pimutils/vdirsyncer#467]
vdirsyncer, version 0.11.0 (installed via `pip install --user vdirsyncer`)
Python 3.5.1
Arch Linux
Google Calendar

config (sanitized):
```
[general]
status_path = ~/.config/vdirsyncer/status


[pair google_calendar]
a = google_calendar_remote
b = google_calendar_local
collections = ["me@gmail.com"]
conflict_resolution = "a wins"

[storage google_calendar_remote]
type = google_calendar
token_file = ~/.config/vdirsyncer/nothing_to_see_here
client_id = "fake"
client_secret = "fake"

[storage google_calendar_local]
type = filesystem
path = ~/.calendar/google/
fileext = .ics
```

vdirsyncer *used* to work, but it has since stopped because it can't find properties for an event. I guess perhaps Google says the event exists, even though it can't be found anywhere?

```
warning: Skipping '/caldav/v2/me@gmail.com/events/040000008200E00074C5B7101A82E008000000001077418DC88CD00100000000000
00000100000009BA262E5883C8A4D92C776A69D335B54.ics', properties are missing.
warning: Skipping '/caldav/v2/me@gmail.com/events/040000008200E00074C5B7101A82E00800000000E07AC2CEADA6D10100000000000
000001000000058D4CDDDE31B724291B814040BBD19A6.ics', properties are missing.
Unhandled exception occured for google_calendar/me@gmail.com.
Traceback (most recent call last):
  File "/home/wayne/.local/lib/python3.5/site-packages/vdirsyncer/cli/tasks.py", line 66, in sync_collection
    force_delete=force_delete
  File "/home/wayne/.local/lib/python3.5/site-packages/vdirsyncer/sync.py", line 215, in sync
    a_info.prepare_idents()
  File "/home/wayne/.local/lib/python3.5/site-packages/vdirsyncer/sync.py", line 124, in prepare_idents
    if prefetch else ()):
  File "/home/wayne/.local/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line 450, in get_multi
    raise exceptions.NotFoundError(href)
vdirsyncer.exceptions.NotFoundError: /caldav/v2/me@gmail.com/events/040000008200E00074C5B7101A82E008000000001077418DC
88CD0010000000000000000100000009BA262E5883C8A4D92C776A69D335B54.ics
error: 1 out of 2 tasks failed.
```

I have a sneaking suspicion that the event itself actually exists, there's just nothing in it.

Is there any way that I can fix this? I know it would be a lot better if there was some nicer error message.

**Comment by untitaker** [comment]
Could you post `vdirsyncer -vdebug sync`?

**Comment by waynew** [comment]
https://gist.github.com/waynew/57d9c0e094461278f40dc8d09c4b734e

**Comment by waynew** [comment]
````````

**Comment by untitaker** [comment]
You might want to take that link down immediately because it contains all your events! Sorry, should've warned you about the sensitive nature of debug output.

As for the response itself, regardless of whether the event is broken/empty, the server's behavior is a bug. I'd rather fix that than include a workaround in vdirsyncer (will try to contact)

**Comment by waynew** [comment]
I wasn't sure if I had completely sanitized it :P

It certainly seemed like it was a server-side bug - since it appeared to be providing events that don't exist, presumably.

I'm fairly certain that the wonky events in question I *added* via vdirsyncer (by way of khal). At some point I ended out deleting them, I think. But it appears that something in that chain broke. I dug into the vdirsyncer code to see if I could find exactly what was going on and maybe hack around it myself, but I wasn't able to do anything terribly worthwhile. I even went to the google calendar API explorer to try and find/fix things that way, to no avail.

**Comment by untitaker** [comment]
Do you remember what you did in khal to create that event? Was it recurrent or otherwise "special"?

**Comment by waynew** [comment]
It's fairly likely that it was a recurring event. Unfortunately I couldn't tell you much more than that, because I'm sure I overwrote the .ics file. I just did `khal import /tmp/<appointment>.ics`. Worked fine, imported to the calendar.

Oh that's an interesting thought - If the .ics file was for deleting an event, could that have caused this craziness?

**Comment by untitaker** [comment]
I'll test this out and get back to you eventually.

>If the .ics file was for deleting an event, could that have caused this craziness?

I don't know what you mean by that, `.ics` files only contain events (not "instructions" to delete/modify a calendar)

**Comment by waynew** [comment]
I believe I have sufficiently anonymized this event: https://gist.github.com/e9bcae54d36d84559877e149aaea0052

That's an example of what I'm talking about.

**Comment by untitaker** [comment]
I can't upload this item to Google Calendar. Is that the one vdirsyncer can't download for you?

**Comment by waynew** [comment]
I don't know. That's part of the problem - if I knew what the event *was*, I'd just delete it in google calendar and figure something else out.

**Comment by untitaker** [comment]
Could you try fetching this event via `calendar.events.list` and `calendar.events.get`? The `"id"` field should be `040000008200E00074C5B7101A82E008000000001077418DC
88CD0010000000000000000100000009BA262E5883C8A4D92C776A69D335B54` (ctrl-f on the page).

**Comment by waynew** [comment]
I went to this page https://developers.google.com/apis-explorer/#p/calendar/v3/calendar.events.list  authorized, and executed.

`040000008200E00074C5B7101A82E008000000001077418DC88CD0010000000000000000100000009BA262E5883C8A4D92C776A69D335B54`

Was not on the page. 

https://developers.google.com/apis-explorer/#p/calendar/v3/calendar.events.get?calendarId=me%2540gmail.com&eventId=040000008200E00074C5B7101A82E008000000001077418DC88CD0010000000000000000100000009BA262E5883C8A4D92C776A69D335B54&_h=4&

Also does not exist.

**Comment by waynew** [comment]
I thought I replied to this issue, but apparently not 📦 
Neither of those succeeded - list didn't have it and get didn't return it (using the api explorer).

**Comment by untitaker** [comment]
@waynew Any update on this? Unfortunately I still have no idea what could be wrong. :(

**Comment by waynew** [comment]
I went to Google calendar, then selected the dropdown next to my primary calendar and went to calendar settings. There I clicked 'export calendar' and downloaded the zip file. The zip file contained one `.ics` file that looked like it contained all of the events on my calendar. Then I changed the config line from

```
collections = ["me@gmail.com"]
```

to 

```
collections = ["some_random_id@gmail.com"]
```

then ran

```
vdirsyncer discover
```

Then I copied the `.ics` file to `~/.calendar/google/some_random_id/me@gmail.com.ics` then ran `vdirsyncer sync`.

This failed with:

```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://apidata.googleusercontent.com/caldav/v2/some_random_id@group.calendar.google.com/events/bfab507ec98b44e09a79089e8182c1fd.ics
```

Then I went to the `Other calendars` link in google calendar and clicked import, and imported the .ics file to my new calendar. Then I removed the `.ics` file and everything seems to sync fine.

I just deleted all the events from my main calendar, and then changed the config line back, ran `vdirsyncer discover` followed by `vdirsyncer sync`. That seems to work.

However, simply copying the .ics files from my random calendar directory to my `me@gmail.com` directory doesn't seem to work. It appears to have random problems with events. 

So I tried importing to my main calendar instead of a new one and I get this error:

```
Failed to import events: Could not upload your events because you do not have sufficient access on the target calendar..
```

(that's from Google)

I've just spent a really weird amount of time/effort that led me to [this discusssion](https://productforums.google.com/d/msg/calendar/cBuwVCddO3U/YbU8GEnE9yQJ)

> Google support advised that "Clearing your Primary Calendar" no longer works. As of a few months ago the tool changed the way items are "deleted". Previously if you were to delete and item or use the web to clear your primary calendar it would simply trash all the items. Now however, when you delete an item or clear your calendar it simply "cancels" the event and hides from view. 
> ...

> The fix is quite simple, open the exported ics file in your favorite text editor (I like Notepad++, also I'd make a backup copy first) do a find/search and replace.
search for "UID:" (no need to be case sensitive, and make sure you have appended the colon)
replace with "UID:X" (Replace X with any non-special character [a-z,0-9])

> Save the ics file and re-import.

> Since all items are now unique there will be no conflicts and you should have no problems. 

This time, after deleting everything on my primary calendar I *also* went and emptied the trash on the calendar. *now* it gives me the same error, but it *does* pull in 513/522 events. Unfortunately it doesn't tell me which events are borked up.

I do, however, still have the .ics file, so if there's any kind of reasonable-ish way to compare, I'd be totally happy to do that. It seems like this really really hackish workaround worked(ish), though.

**Comment by untitaker** [comment]
>Then I copied the .ics file to ~/.calendar/google/some_random_id/me@gmail.com.ics then ran vdirsyncer sync.

Here's the problem, since your file contains more than one event, it fails to upload. I'd advise using `khal import` instead of copying the file directly.

**Comment by untitaker** [comment]
(To clarify, it is expected that one file contains one event each. Vdirsyncer doesn't check for this and just passes it on)

**Comment by waynew** [comment]
That makes sense. So interestingly enough, I ran a quick little script to extract the `UID` lines from all the `me@gmail.com/*.ics` files. Turns out:

```
print(len(uids), len(set(uids)))
# 290 266
```

Is that something *normal*?

**Comment by untitaker** [comment]
@waynew Yes, if you have recurring events.

**Comment by waynew** [comment]
Interesting. My `me@gmail.com.ics` file actually has `578 543`. I can't help but notice that neither of those numbers are the 513/522 that Google reported :suspect:

**Comment by waynew** [comment]
After running a `khal import --batch me@gmail.com.ics` Here's one offending appointment that fails to sync:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//CALENDARSERVER.ORG//NONSGML Version 1//EN
BEGIN:VEVENT
SUMMARY:Windows Forms Programming (TRNG-DOTNT4_17)
DTSTART:20110620T131500Z
DTEND:20110620T220000Z
DTSTAMP:20160815T131143Z
UID:040000008200E00074C5B7101A82E00800000000C06081740921CC0100000000000000
 0010000000B045C6C3067BB043962A944EF83BBE5E
SEQUENCE:1
ATTENDEE;CN=fake@example.com;CUTYPE=INDIVIDUAL;PARTSTAT=ACCEPTED;
 ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:fake@example.com
ATTENDEE;CN="Fake Person";CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACTION;ROLE
 =REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:fakeperson@example.com.com
ATTENDEE;CN="Fake Two";CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACTION;ROLE=
 REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:fake2@example.com
ATTENDEE;CN="Fake Three";CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACTION;ROLE
 =REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:fake3@example.com.com
ATTENDEE;CN="Fake Four";CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACTION;ROLE=RE
 Q-PARTICIPANT;X-NUM-GUESTS=0:mailto:fake4@example.com
ATTENDEE;CN="Fake Five";CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACTION;ROLE
 =REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:fake5@example.com
ATTENDEE;CN="Fake Six";CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACTION;ROLE=RE
 Q-PARTICIPANT;X-NUM-GUESTS=0:mailto:fake6@example.com
ATTENDEE;CN="Fake Seven";CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACTION;ROLE=REQ-
 PARTICIPANT;X-NUM-GUESTS=0:mailto:fake7@example.com
ATTENDEE;CN="Fake Eight";CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACTION;ROLE=RE
 Q-PARTICIPANT;X-NUM-GUESTS=0:mailto:fake8@example.com
ATTENDEE;CN="Fake 9";CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACTION;ROLE=REQ-
 PARTICIPANT;X-NUM-GUESTS=0:mailto:fake9@example.com
ATTENDEE;CN="Fake 10";CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACTION;ROL
 E=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:fake10@example.com
ATTENDEE;CN="Fake 11";CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACTION;ROLE=REQ
 -PARTICIPANT;X-NUM-GUESTS=0:mailto:fake11@example.com
ATTENDEE;CN="Fake me";CUTYPE=INDIVIDUAL;PARTSTAT=ACCEPTED;ROLE=REQ-PA
 RTICIPANT;X-NUM-GUESTS=0:mailto:me@gmail.com
ATTENDEE;CN="Fake 12";CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACTION;ROLE=
 REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:fake12@example.com
ATTENDEE;CN="Fake 13";CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACTION;ROLE=R
 EQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:fake13@example.com
CREATED:20110615T130106Z
DESCRIPTION:When: Monday\, June 20\, 2011 8:15 AM-5:00 PM (UTC-06:00) Cent
 ral Time (US & Canada).\nWhere: 2W.50\n\nNote: The GMT offset above does n
 ot reflect daylight saving time adjustments.\n\n*~*~*~*~*~*~*~*~*~*
LAST-MODIFIED:20110620T145844Z
LOCATION:2W.50
ORGANIZER;CN=fake@example.com:mailto:fake@example.com
STATUS:CONFIRMED
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
```

And here's a bit of the log:

```
debug: Sending request...
debug: 403
debug: {'Content-Type': 'text/xml; charset=UTF-8', 'Cache-Control': 'private, max-age=0', 'Alternate-Protocol': '443:quic', 'Vary': 'Origin, X-Origin', 'Expires': 'Mon, 15 Aug 2016 14:39:50 GMT', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Server': 'GSE', 'Date': 'Mon, 15 Aug 2016 14:39:50 GMT', 'Alt-Svc': 'quic=":443"; ma=2592000; v="36,35,34,33,32,31,30"', 'X-XSS-Protection': '1; mode=block', 'X-Frame-Options': 'SAMEORIGIN', 'X-Content-Type-Options': 'nosniff'}
debug: b'<?xml version="1.0" encoding="UTF-8"?>\n<D:error xmlns:D="DAV:"/>\n'
error: Unknown error occured for google_calendar/waynejwerner@gmail.com: 403 Client Error: Forbidden for url: https://apidata.googleusercontent.com/caldav/v2/me@gmail.com/events/040000008200E00074C5B7101A82E00800000000E0D7F12BC721CC01000000000000000010000000D94FBE2A1099EE4FA53275D2406F720A.ics
```

**Comment by untitaker** [comment]
Is this the only one that fails? Did other events succeed to upload?

**Comment by waynew** [comment]
At least one event uploaded, but that failure stops the whole train

**Comment by untitaker** [comment]
I can't really see what is wrong with this event. If you move/remove it, does the train continue?

**Comment by waynew** [comment]
I'm currently adding `42` to the end of the UID and filename and things appear to be moving forward. Another item from that same environment failed.

**Comment by waynew** [comment]
It looks like there's definitely something weird on the google backend along the lines mentioned in that Google Groups thread - I have an event with this description:

    LINQ with Query Expressions (TRNG-ADVDN10_1)

When I search my calendar, it says there are no events matching that. Going to the google API, i.e. 

```
https://www.googleapis.com/calendar/v3/calendars/me%40gmail.com/events/040000008200E00074C5B7101A82E00800000000D0ECB8AA0921CC010000000000000000100000009406361562616E4781829022036D7997?key={YOUR_API_KEY}
```

Returns a 404. So I'm suspecting that using your primary calendar on Google Calendar can produce a weird state where you have deleted events that are invisible on the calendar - you can't get them, they're not in the trash, they don't appear to exist in the API, and yet they can still cause conflicts.

I would be interested if there's any way to possibly recover these events and then update/actually delete them, but it does appear that this is the root cause of the issue.

**Comment by waynew** [comment]
As an update, it looks like I can get things uploaded. But I also think I've got repro instructions.

Using your primary Google Calendar, create some `appointment.ics` file and put this in it:

```BEGIN:VCALENDAR
METHOD:REQUEST
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Central Standard Time
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETFROM:-0500
TZOFFSETTO:-0600
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=1SU;BYMONTH=11
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:-0600
TZOFFSETTO:-0500
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=2SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ORGANIZER;CN=Ronald Frobnitz;SENT-BY="MAILTO:fnord@example.com":MAILTO:fnord
 @example.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=Wayne
 :MAILTO:fnordw@example.com
DESCRIPTION;LANGUAGE=en-US:\n\n\n\nFrom: Fnord<mailto:fnord
 @example.com>\nWhen: 3:00 PM - 4:00 PM May 6\, 2016\nSubject: Do the thing
 Okay? \nLocation: 555-555-5555\;1234562\n\n\n\n\n\n\n
RRULE:FREQ=WEEKLY;INTERVAL=1;BYDAY=FR;WKST=MO
UID:040000008200E00074C5B7101A82E0080000000020DAB6EAADA6D101000000000000000
 010000000D361272127CA00489E962C63F3D74E24ABCD
SUMMARY;LANGUAGE=en-US:FW: Do the thing
DTSTART;TZID=Central Standard Time:20160506T140000
DTEND;TZID=Central Standard Time:20160506T150000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20160716T075648Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:5
LOCATION;LANGUAGE=en-US:555-555-5555\;1234123
X-MICROSOFT-CDO-APPT-SEQUENCE:5
X-MICROSOFT-CDO-OWNERAPPTID:1422219232
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:1
X-MICROSOFT-DISALLOW-COUNTER:FALSE
BEGIN:VALARM
DESCRIPTION:REMINDER
TRIGGER;RELATED=START:-PT15M
ACTION:DISPLAY
END:VALARM
END:VEVENT
END:VCALENDAR
```

- Import it with `khal import appointment.ics`
- Run `vdirsyncer sync`, it should upload to your google calendar
- Use `ikhal` or `khal interactive` and delete the appointment.
- Run `vdirsyncer sync` again.
- Import the appointment again with `khal import appointment.ics`. It will ask you if you want to update, say `y`es.
- Run `vdirsyncer sync` again
- It should fail with "unknown error occurred".

**Comment by untitaker** [comment]
There is a line "BEGIN:VCALENDAR" missing at the top. Is this intentional?

On 15 August 2016 17:46:29 CEST, Wayne Werner <notifications@github.com> wrote:
>As an update, it looks like I can get things uploaded. But I also think
>I've got repro instructions.
>
>Using your primary Google Calendar, create some `appointment.ics` file
>and put this in it:
>
>```BEGIN:VCALENDAR
>METHOD:REQUEST
>PRODID:Microsoft Exchange Server 2010
>VERSION:2.0
>BEGIN:VTIMEZONE
>TZID:Central Standard Time
>BEGIN:STANDARD
>DTSTART:16010101T020000
>TZOFFSETFROM:-0500
>TZOFFSETTO:-0600
>RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=1SU;BYMONTH=11
>END:STANDARD
>BEGIN:DAYLIGHT
>DTSTART:16010101T020000
>TZOFFSETFROM:-0600
>TZOFFSETTO:-0500
>RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=2SU;BYMONTH=3
>END:DAYLIGHT
>END:VTIMEZONE
>BEGIN:VEVENT
>ORGANIZER;CN=Ronald
>Frobnitz;SENT-BY="MAILTO:fnord@example.com":MAILTO:fnord
> @example.com
>ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=Wayne
> :MAILTO:fnordw@example.com
>DESCRIPTION;LANGUAGE=en-US:\n\n\n\nFrom: Fnord<mailto:fnord
>@example.com>\nWhen: 3:00 PM - 4:00 PM May 6\, 2016\nSubject: Do the
>thing
> Okay? \nLocation: 555-555-5555\;1234562\n\n\n\n\n\n\n
>RRULE:FREQ=WEEKLY;INTERVAL=1;BYDAY=FR;WKST=MO
>UID:040000008200E00074C5B7101A82E0080000000020DAB6EAADA6D101000000000000000
> 010000000D361272127CA00489E962C63F3D74E24ABCD
>SUMMARY;LANGUAGE=en-US:FW: Do the thing
>DTSTART;TZID=Central Standard Time:20160506T140000
>DTEND;TZID=Central Standard Time:20160506T150000
>CLASS:PUBLIC
>PRIORITY:5
>DTSTAMP:20160716T075648Z
>TRANSP:OPAQUE
>STATUS:CONFIRMED
>SEQUENCE:5
>LOCATION;LANGUAGE=en-US:555-555-5555\;1234123
>X-MICROSOFT-CDO-APPT-SEQUENCE:5
>X-MICROSOFT-CDO-OWNERAPPTID:1422219232
>X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
>X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
>X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
>X-MICROSOFT-CDO-IMPORTANCE:1
>X-MICROSOFT-CDO-INSTTYPE:1
>X-MICROSOFT-DISALLOW-COUNTER:FALSE
>BEGIN:VALARM
>DESCRIPTION:REMINDER
>TRIGGER;RELATED=START:-PT15M
>ACTION:DISPLAY
>END:VALARM
>END:VEVENT
>END:VCALENDAR
>```
>
>- Import it with `khal import appointment.ics`
>- Run `vdirsyncer sync`, it should upload to your google calendar
>- Use `ikhal` or `khal interactive` and delete the appointment.
>- Run `vdirsyncer sync` again.
>- Import the appointment again with `khal import appointment.ics`. It
>will ask you if you want to update, say `y`es.
>- Run `vdirsyncer sync` again
>- It should fail with "unknown error occurred".
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/467#issuecomment-239838640

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by waynew** [comment]
Ah, it wasn't missing per se - just apparently in the place/format for a code format comment. It's fixed :)

**Comment by untitaker** [comment]
Okay, that's a bug in vdirsyncer, see #492.

**Comment by waynew** [comment]
Looks like that was merged in to master - has there been a new release associated with that? Alternatively, I can pull from the repo and install/test using that.

**Comment by untitaker** [comment]
Yes, please try it out. It appears there are a few bugreports open already.

**Comment by untitaker** [comment]
0.12.1 is out anyway, please ping if not fixed then.
