### ISSUE TITLE
Special codepath for `collections = null`

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#469]
Just a reminder for me to resume working on this.

This doesn't work for now because `collections = null` is special cased (as opposed to `null` being generically handled):

    collections = [["a", null, "a"]]

**Comment by untitaker** [comment]
@drzraf #470 should fix this. You can install it with:


    pip install git+https://github.com/pimutils/vdirsyncer@collections-null-fix

**Comment by drzraf** [comment]
this command tries to recursively clone more than 170 MB
(I run out of tmpfs disk space above this limit)

**Comment by untitaker** [comment]
Oh, I didn't realize pip clones submodules. In that case I guess you'll have to manually clone the repo or just wait for the next release.
