### ISSUE TITLE
bump click_threading version in setup.py

### ISSUE THREAD

**Issue by mbaldessari** [pimutils/vdirsyncer#478]
With commit https://github.com/pimutils/vdirsyncer/commit/3cb03a55e4e8a0b30f36148a20eacb03c5054fd5
we added from "click_threading import get_ui_worker" which was introduced in click-threading 0.2.0
So let's bump the current require from >= 0.1.2 to at least 0.2.0

**Comment by untitaker** [comment]
Thanks, completely missed that.
