### ISSUE TITLE
local single file storage per remote collection

### ISSUE THREAD

**Issue by gour** [pimutils/vdirsyncer#479]
Hello,

I'm back to vdirsyncer/khal/khard and Claws... :-)

On the remote side ownCloud, I have single user with several calendars and/or contacts files:

- one for myself

- one for my wife

- one for some common dates

- one for contact birthdays

- ...

and I'd like to keep ability to work (add/edit/rm events) with each one separately and have such configuration in my khal.conf.

When I run 'discover', vdirsyncer finds all the calendars in remote collection and then 'sync' them by putting relevant entries in my local filesystem-based storage:

```
[storage all_calendar_local]
type = filesystem
path = ~/prj/vf/vdir/calendars/
fileext = .ics
```

and each calendars has its own folder under:

```
~/prj/vf/vdir/calendars/
```

what I'd like to achieve is if vdirsyncer could put all the entries into **single** *.ics file like:

```
~/prj/vf/vdir/calendars/calendar1/cal1.ics
~/prj/vf/vdir/calendars/calendar2/cal2.ics
~/prj/vf/vdir/calendars/calendar3/cal3.ics
~/prj/vf/vdir/calendars/calendar4/cal4.ics
```

What would be the benefit?

Well, at the moment one cannot subscribe to the ownCloud calendars and this feature would allow me to subscribe from within Claws-mail to my local *.ics calendar files and have them automatically synced with the ownCloud (phone). ;)

What do you think? Is it feasible?

Sincerely,
Gour

**Comment by untitaker** [comment]
You can do this with the "singlefile" storage type (as opposed to "filesystem", see "configuration" docs) but I'm unsure if it supports collections as you wish. It might need a bit more love to become easily usable.

On 28 June 2016 16:23:33 EEST, Gour <notifications@github.com> wrote:
>Hello,
>
>I'm back to vdirsyncer/khal/khard and Claws... :-)
>
>On the remote side ownCloud, I have single user with several calendars
>and/or contacts files:
>
>- one for myself
>
>- one for my wife
>
>- one for some common dates
>
>- one for contact birthdays
>
>- ...
>
>and I'd like to keep ability to work (add/edit/rm events) with each one
>separately and have such configuration in my khal.conf.
>
>When I run 'discover', vdirsyncer finds all the calendars in remote
>collection and then 'sync' them by putting relevant entries in my local
>filesystem-based storage:
>
>```
>[storage all_calendar_local]
>type = filesystem
>path = ~/prj/vf/vdir/calendars/
>fileext = .ics
>```
>
>and each calendars has its own folder under:
>
>```
>~/prj/vf/vdir/calendars/
>```
>
>what I'd like to achieve is if vdirsyncer could put all the entries
>into **single** *.ics file like:
>
>```
>~/prj/vf/vdir/calendars/calendar1/cal1.ics
>~/prj/vf/vdir/calendars/calendar2/cal2.ics
>~/prj/vf/vdir/calendars/calendar3/cal3.ics
>~/prj/vf/vdir/calendars/calendar4/cal4.ics
>```
>
>What would be the benefit?
>
>Well, at the moment one cannot subscribe to the ownCloud calendars and
>this feature would allow me to subscribe from within Claws-mail to my
>local *.ics calendar files and have them automatically synced with the
>ownCloud (phone). ;)
>
>What do you think? Is it feasible?
>
>
>Sincerely,
>Gour
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/479

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gour** [comment]
> You can do this with the "singlefile" storage type (as opposed to "filesystem", see "configuration" docs) 

I did look the docs - that's the why I'm asking about it. ;)

> but I'm unsure if it supports collections as you wish.

It does not:

```
critical: The storage atmarama_calendar_local (type singlefile) doesn't support collection discovery. You can only use `collections = null` with it.
```

so I'll check whether I can manually create setup with

``` 
collections = null
```

**Comment by gour** [comment]
The setup with:

```
collections = null
```

and using _singlefile_ storage along with manually configuring each pair separately instead of using collections does work in theory, iow. 'discovery' founds each calendar - I've tried with the two, but syncing does not work. 

Actually, even using just a single calendar and syncing produces wrong results which differ if I just manually import single *.ics file downloaded from my ownCloud instance. It looks there is some parsing problem.

Should I open another ticket for it?

**Comment by untitaker** [comment]
We've discussed this on IRC, but I'd actually prefer Github:

The first issue is a usability bug in vdirsyncer, but I can't find the time for hacking on vdirsyncer right now. I presume you'd expect vdirsyncer to create several files with the collection's name as filename?

Your two ICS files posted on IRC don't look different to me, although the ordering of the properties is not the same. This is not important for the meaning of the content.

On 29 June 2016 13:30:15 EEST, Gour <notifications@github.com> wrote:
>The setup with:
>
>```
>collections = null
>```
>
>and using _singlefile_ storage along with manually configuring each
>pair separately instead of using collections does work in theory, iow.
>'discovery' founds each calendar - I've tried with the two, but syncing
>does not work. 
>
>Actually, even using just a single calendar and syncing produces wrong
>results which differ if I just manually import single *.ics file
>downloaded from my ownCloud instance. It looks there is some parsing
>problem.
>
>Should I open another ticket for it?
>
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/479#issuecomment-229319043

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gour** [comment]
> I presume you'd expect vdirsyncer to create several files with the collection's name as filename?

Well, I do not mind having setup for each of my contact/calendar file(s), but the problem is that the created *.ics file when using 'singlefile' is not correct.

>Your two ICS files posted on IRC don't look different to me, although the ordering of the properties is > not the same. This is not important for the meaning of the content.

But, have you tried to compare calendar after vdirsyncing calendar with 'singlefile' with the calendar created when importing ownCloud-exported *.ics?

That is the problem that 'singlefile'-created calendar gets confused and does not provide correct calendar.

**Comment by untitaker** [comment]
I don't have the facilities to import them into some application right now, could you describe how they are different? A plain file diff doesn't necessarily mean anything.

On 6 July 2016 18:16:56 CEST, Gour <notifications@github.com> wrote:
>> I presume you'd expect vdirsyncer to create several files with the
>collection's name as filename?
>
>Well, I do not mind having setup for each of my contact/calendar
>file(s), but the problem is that the created *.ics file when using
>'singlefile' is not correct.
>
>>Your two ICS files posted on IRC don't look different to me, although
>the ordering of the properties is > not the same. This is not important
>for the meaning of the content.
>
>But, have you tried to compare calendar after vdirsyncing calendar with
>'singlefile' with the calendar created when importing ownCloud-exported
>*.ics?
>
>That is the problem that 'singlefile'-created calendar gets confused
>and does not provide correct calendar.
>
>
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/479#issuecomment-230823923

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gour** [comment]
> I don't have the facilities to import them into some application right now, could you describe how they are different? 

Just use khal...or I'm going to create a new test setup tomorrow.

**Comment by gour** [comment]
Hello,

in the attachment I do include two files:

1. _gour-vd.ics_ which is created by vdirsyncer's "single storage" setup and

1. _gour-oc.ics_  is downloaded as exported calendar from my own instance of ownCloud server.

Try to load both files into khal and compare entries.

My (wild) guess is that there is problem with handling recurring events...


Sincerely,
Gour


[test.zip](https://github.com/pimutils/vdirsyncer/files/385823/test.zip)

**Comment by untitaker** [comment]
Gist: https://gist.github.com/untitaker/a601904a4c54664e2c7751a34448b2d5

    khal import gour-vd.ics -a cal1 --batch -r
    khal import gour-oc.ics -a cal2 --batch -r

Those two calendars look completely identical in khal to me. Please be more specific.

![2016-07-27-143106_551x526_scrot](https://cloud.githubusercontent.com/assets/837573/17175265/ca4e374a-5406-11e6-9b0b-31bd6deeaad8.png)

**Comment by untitaker** [comment]
The bugs were resolved in IRC: singlefile storage has been used for khal instead of filesystem.

The lack of `collection` support for `singlefile` is still real though.

**Comment by untitaker** [comment]
Continuing in https://github.com/pimutils/vdirsyncer/issues/485 since this thread is a bit cluttered.
