### ISSUE TITLE
Issues doing discovery against Google Calendar

### ISSUE THREAD

**Issue by duck** [pimutils/vdirsyncer#484]
* vdirsyncer, version 0.11.3.dev16+ng707c824
  * Python 3.5.2
  * ArchLinux (Linux 4.6.4-1-ARCH # 1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux)

```
[general]
status_path = ~/.vdirsyncer/status/

[pair google_calendar]
a = google_calendar_remote
b = google_calendar_local
collections = ["from a", "from b"]
conflict_resolution = "a wins"

[storage google_calendar_remote]
type = google_calendar
token_file = /home/don/.vdirsyncer/token
client_id = "my-api-key.apps.googleusercontent.com"
client_secret = "MySecret"

[storage google_calendar_local]
type = filesystem
path = ~/.calendar/google/
fileext = .ics
```

When I try to do a `vdirsyncer discover google_calendar`, I get the following error:
https://gist.github.com/duck/891bbabbaa0601b05d95a63aa8506053

I have read all the issues I can find, and it seems like I have the config right, but it looks like I am missing something simple.  Any suggestions?

Thanks!

don

**Comment by duck** [comment]
Oh, forgot to mention, I have set up a google project, enabled the CalDAV API, and set up an OAuth2 token.

**Comment by untitaker** [comment]
First time I see this... could you try deleting the token file (if it exists)?

**Comment by duck** [comment]
No difference.  It brings up a browser window, I authorize it, and it fails with the same error.

If someone has a working config and steps to enure I got the Google side set up correctly, it might help me out....

**Comment by untitaker** [comment]
Your config is absolutely correct, I am testing with a similar one. I have no idea what's wrong...

However, I am seeing that your logfile is not directly from the invocation where you pasted the token. Maybe there's some additional information in such one?

1.  Delete the token file
2.  `vdirsyncer -vdebug discover`, paste the token and also get the output from the same invocation

**Comment by duck** [comment]
Sure...here, and same issue.
Edited for key
[log.txt](https://github.com/pimutils/vdirsyncer/files/389382/log.txt)

**Comment by untitaker** [comment]
Could you dump `pip freeze`? I wonder if this is caused by an old/weird dependency.

**Comment by duck** [comment]
Sure:
[pip.freeze.txt](https://github.com/pimutils/vdirsyncer/files/389414/pip.freeze.txt)

**Comment by untitaker** [comment]
I suspected that you might be running an old buggy version of oauthlib or something like that, but you're on the same version as me.

**Comment by duck** [comment]
bummer...
So, it looks like the code is correct, and the config is correct....that leads me to think the Google API side is bad on my end.  Does anyone have a guide written (or could be quickly written :) on what needs to be done so I can check myself?

Thanks!

**Comment by untitaker** [comment]
Just came to my mind: Try exporting your calendar to a different (new) Google account and see if the problem occurs there too.

**Comment by untitaker** [comment]
@waynew Any update on this?

**Comment by duck** [comment]
sorry for the dely, life. :)

Anyway, I tried with a completely new Google account, and I got the same error, so it seems that I am not setting up the Google side correctly. :(

If any kind soul has a guide to follow, because it seems this is something I have not the clue about.

Thanks!

**Comment by duck** [comment]
And just tested against v0.12.1, and it still does not work, so I am fairly certain it is the Google side...

**Comment by untitaker** [comment]
Hmm. Could you send me that newly created Google Account's credentials so I can take a look myself? (provided it doesn't contain sensitive data)

**Comment by duck** [comment]
Found that, and sent the info along.

Thanks!

**Comment by untitaker** [comment]
Ugh, it appears that my provider currently blocks traffic from the US due to an ongoing DDoS. I'll get back to you after that.

**Comment by duck** [comment]
So, after trying many things, and having @untitaker take a look at my accoutn settings (Thanks!), I decided to try on a different distro than my ArchLinux.  I tried on Ubuntu, and lo and behold, my config works. :(  So, I am closing this, as the problem is not with vdirsyncer, but rather python on ArchLinux.
