### ISSUE TITLE
Crash with collections and singlefile backend

### ISSUE THREAD

**Issue by dmacvicar** [pimutils/vdirsyncer#490]
I am trying to sync a remote caldav storage to both a `filesystem` (for khal) and a `singlefile` backend (for Thunderbird) using two pairs.

`singlefile` backend crashes after asking to create the non-existing collection:

```
error: No collection "Calendar" found for storage my_calendar_local_single.
Should vdirsyncer attempt to create it? [y/N]: y
error: Unknown error occured: collection is not a valid argument for SingleFileStorage
error: Use `-vdebug` to see the full traceback.
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/utils.py", line 510, in _worker
debug:     func(wq=self)
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/tasks.py", line 77, in discover_collections
debug:     rv = collections_for_pair(pair=pair, **kwargs)
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/utils.py", line 212, in collections_for_pair
debug:     list_collections=list_collections))
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/utils.py", line 350, in _collections_for_pair_impl
debug:     pair.config_a)
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/utils.py", line 367, in _collection_from_discovered
debug:     return _handle_collection_not_found(config, collection)
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/utils.py", line 281, in _handle_collection_not_found
debug:     args = cls.create_collection(**config)
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/singlefile.py", line 95, in create_collection
debug:     .format(cls.__name__))
error: 1 out of 1 tasks failed.
```

Configuration file

```
[pair my_calendar]
a = my_calendar_local
b = my_calendar_remote
collections = ["from b"]
conflict_resolution = "b wins"
metadata = ["displayname", "color"]

[pair my_calendar_thunderbird]
a = my_calendar_local_single
b = my_calendar_remote
collections = ["from b"]
conflict_resolution = "b wins"
metadata = ["displayname", "color"]

[storage my_calendar_local]
type = filesystem
path = ~/.calendars/my
fileext = .ics

[storage my_calendar_local_single]
type = singlefile
path = ~/.calendars/my-%s.ics

[storage my_calendar_remote]
type = caldav
url = https://myserver/principals/users/username/calendars/Calendar
username = myusername
password = XXXX
verify = false
verify_fingerprint = ...
start_date = datetime.now() - timedelta(days=10)
end_date = datetime.now() + timedelta(days=365)
read_only = true
item_types = ["VEVENT", "VJOURNAL"]
```

* vdirsyncer version: 0.11.3 
* Novell GroupWise//14.2.0 Beta CalDav endpoint
* Python 3.5.1
* openSUSE Tumbleweed

**Comment by untitaker** [comment]
This got recently fixed via #485, please try the master branch.

**Comment by dmacvicar** [comment]
Thanks. I thought this was in 0.11.3 already. I backported the patch to our package.

**Comment by untitaker** [comment]
If this is the official openSUSE package, please just ask for a release rather
than patching this on top of the latest one.

**Comment by dmacvicar** [comment]
It is not the package in the distribution but the official python3 community project:

https://build.opensuse.org/package/show/devel:languages:python3/vdirsyncer

And I requested to add the patch on top (https://build.opensuse.org/request/show/420296) . If you make a new release, I would gladly update it and drop the patch.

One question, does vdirsyncer work with python 2.x too?

**Comment by untitaker** [comment]
If you're packaging software and publish those packages for others to consume, please do not apply random patches on top of existing versions. In the worst case, these kind of modifications bounce back to me as users report bugs that don't exist in official releases (which has actually happened multiple times for one dependency of vdirsyncer and some unrelated projects). I'd rather add a few other changes before releasing 0.12.

Vdirsyncer still works on Python 2 but that support will soon be dropped, see #219.

**Comment by dmacvicar** [comment]
I have revoked the request to submit my patched `home:dmacvicar:branches:devel:languages:python3/vdirsyncer` to `devel:languages:python3/vdirsyncer` .

Note that I do intend to point people to my own branch, as is the only way to sync from our corporate calendar to Thunderbird/.ics without it crashing (which is why you got this bugreport even if the bug was fixed in master).

**Comment by untitaker** [comment]
I will release 0.12 shortly, thanks for your cooperation.

On 19 August 2016 12:31:31 CEST, "Duncan Mac-Vicar P." <notifications@github.com> wrote:
>I have revoked the request to submit my patched
>`home:dmacvicar:branches:devel:languages:python3/vdirsyncer` to
>`devel:languages:python3/vdirsyncer` .
>
>Note that I do intend to point people to my own branch, as is the only
>way to sync from our corporate calendar to Thunderbird/.ics without it
>crashing (which is why you got this bugreport even if the bug was fixed
>in master).
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/490#issuecomment-240984556

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
0.12.0 is released. If I understand correctly this means that you just have to
wait for an update of the openSUSE packagers?

**Comment by untitaker** [comment]
Okay thank you.
