### ISSUE TITLE
Accept vCard 4.0 in DAV storage

### ISSUE THREAD

**Issue by citrin** [pimutils/vdirsyncer#503]
Please add support of syncing vCard 4.0 files.

I use:
- vdirsyncer 0.12.1 with python 2.7.12
- Baïkal 0.4.6 as CardDAV server

When I try to sync vCard 4.0 file it converted to vCard 3.0 (by Baïkal).

According to RFC 6352 client can indicate supported version via Accept header in HTTP request, e. g.
`Accept: text/xml, text/vcard; version=4.0`

Adding this header should be configurable (per storage?), because there are a lot of software with only vCard 3.0 support.

**Comment by untitaker** [comment]
Does Baikal store its data in VCard v4 and would this therefore be a performance improvement?

**Comment by citrin** [comment]
As I can see Baikal stores data in same version as the was uploaded by client without conversion. For reading requests Baikal converts all vCards to version supported by client (3.0 by default, 4.0 if indicated in `Accept`).

My test sequence was:

1. Put vCard 4.0 file in the vdir
2. Run `vdirsyncer sync` (two times to rename file to uuid.vcf)
3. At this point vCard stored as 4.0 on server and 3.0 on client (vdir)
4. Edit data local vCard file
5. `vdirsyncer sync`
6. Now vCard stored as 3.0 on both client and server.

**Comment by untitaker** [comment]
If you changed the config value between syncs, would you expect that vdirsyncer downloads all items again, with the new `Accept`-value?

E.g. if I sync with `accept=3.0`, then change the parameter to `accept=4.0`, should vdirsyncer delete all local items and download all items in VCard 4.0 format?

**Comment by citrin** [comment]
When DAV server URL is changed `vdirsyncer` asks to run `vdirsyncer discover`. In this case I will expect similar behavior (but only because I know what happens after URL change).

For me both options are acceptable:
- delete local 3.0 files and download 4.0 (and print message about version change)
- issue warning and keep local 3.0 files unchanged, delete and re-download only if `vdirsyncer sync --force` is used

First option is better when `vdirsyncer` is started from cron.

**Comment by untitaker** [comment]
There are really only two options easily implementable:

* Delete 3.0 files and download 4.0 without warning
* Replace 4.0 with 3.0 within normal sync, creating a mix of 4.0 and 3.0 that eventually converges to 4.0.

**Comment by citrin** [comment]
I prefer second option. To force convert to 4.0 user can delete local files and re-download all from CardDAV server.

**Comment by untitaker** [comment]
Would it make sense to allow for configuration of `Accept: */*` to avoid costly conversions?

**Comment by citrin** [comment]
As I remember with `Accept: */*` baikal will return 3.0.

**Comment by untitaker** [comment]
FWIW, if anybody wants to push this, we need investigation on what happens with various values for `Accept`.

**Comment by choreutes** [comment]
A little over a year ago I did do some investigation concerning this topic over at nextcloud/server#12878. Maybe this can be of some help for this issue, so I'm mentioning it here for reference. I don't know if I can help implementing it but I would also like being able to download vCard v4.0 since I'm using some of its features in my addressbook.

**Comment by de-es** [comment]
Baikal and Nextcloud use both the sabre/dav framework. If you don't explicitly request 4.0 cards, it will always send 3.0 ones.

See this patch to force 4.0 cards only: https://github.com/de-es/vdirsyncer/commit/bdbf7378e6c0d62ba1b67b1222737bf9a6115fde
