### ISSUE TITLE
missing collections on HTTP ICS

### ISSUE THREAD

**Issue by monperrus** [pimutils/vdirsyncer#504]
I have two storages: ICS and Google as follows

```
[storage cce_iirr]
type = http
url = https://example.com/basic.ics

[storage google]
type = google_calendar
```

The first one has no collection, the second one two collections.

```
cce_iir:
iagl_google:
  - "js4kr6vb9lt9c5eqdqsd@group.calendar.google.com" ("Foo Bar")
  - "martin.monperrus@gmail.com" ("Monperrus")
```

if I put `collections = null`, it fails with 
```
error: One or more storages don't support `collections = null`. You probably want to set `collections = ["from a", "from b"]`.
```

if I put `collections = ['ics', 'js4kr6vb9lt9c5eqdqsd@group.calendar.google.com']`, it fails with 
```
error: No collection "ics" found for storage cce_iir_xavier.
Should vdirsyncer attempt to create it? [y/N]: y
critical: Unable to find or create collection "ics" for storage "cce_iir_xavier". Please create the collection yourself.
```

What is the solution?

**Comment by untitaker** [comment]
What are you trying to do?

**Comment by monperrus** [comment]
Found the solution, add a sublist to the collection list: `collections = [["cce_iirr", null, "martin.monperrus@gmail.com"]]`

**Comment by untitaker** [comment]
Okay cool. I wasn't sure which calendar on the Google side you were trying to sync to.

On 16 September 2016 09:12:56 CEST, Martin Monperrus <notifications@github.com> wrote:
>Found the solution, add a sublist to the collection list: `collections
>= [["cce_iirr", null, "martin.monperrus@gmail.com"]]`
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/504#issuecomment-247533653

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
