### ISSUE TITLE
InvalidXMLResponse('Invalid XML encountered [...] 

### ISSUE THREAD

**Issue by migtavares** [pimutils/vdirsyncer#506]
* vdirsync version: 0.11.2 
  * server: owncloud 9.1.0
  * python version: 3.4.3
  * OS: gentoo
  * config: [vdirsync_config.txt](https://github.com/pimutils/vdirsyncer/files/478751/vdirsync_config.txt)

The debug output is massive and contains private data that I don't feel comfortable with sharing. :( So this is more a request for help in identifying the issue. I tried to check the XML response from the debug output but fails to detect anything amiss.
pyCardDAV,  DavDROID thunderbird SOGO connector seem to work OK.

Is it possible to fetch each contact and processed one by one ? Then it might be possible to figure out what is making vdirsync hiccup on the response.
Or any other ideas on how to find out what the issue is?

**Comment by untitaker** [comment]
The debug output is *the* thing I need though :)

Try the master version, it contains a fix such that an InvalidXMLResponse is swallowed rather than propagated.

**Comment by migtavares** [comment]
Tried with the master branch and it still fails:
```
error: The server returned something vdirsyncer doesn't understand. Error message: InvalidXMLResponse('Invalid XML encountered: not well-formed (invalid token): line 1874, column 20\nDouble-check the URLs in your config.',)
error: While this is most likely a serverside problem, the vdirsyncer devs are generally interested in such bugs. Please report it in the issue tracker at https://github.com/pimutils/vdirsyncer/issues
error: The server returned something vdirsyncer doesn't understand. Error message: InvalidXMLResponse('Invalid XML encountered: not well-formed (invalid token): line 7596, column 42\nDouble-check the URLs in your config.',)
error: While this is most likely a serverside problem, the vdirsyncer devs are generally interested in such bugs. Please report it in the issue tracker at https://github.com/pimutils/vdirsyncer/issues
error: 2 out of 7 tasks failed.
```
Sharing the entire response as seen in the logs is something I cannot do. :( Sorry. 
If find some time I'll dig into the code to see if I can pinpoint what part of the XML is invalid. If I do find it I'll try to replicate it with some fake contact data.

**Comment by migtavares** [comment]
Ok, that went better than I expected.
The problem was a field that had strange characters encoded in _deity_ knows that encoding.
Deleting the offending contact (recreated later by hand) fixed it.
The VCARD property was "X-UNKNOWN-ELEMENT;TYPE=ÿþName:" with some value with some random chars. Notice that weird chars after the equal sign. I'm guessing some dav client added that with some weird encoding.
Maybe it would be nice for vsyncdir to survive such errors (specially as the property is a proprietary of some other tool).
Thx for vdirsync. :)

**Comment by untitaker** [comment]
Unfortunately I don't think it's possible to survive this error, because the underlying XML library is very strict.

Glad you solved your problem.

On 18 September 2016 21:50:11 CEST, "José Miguel Pereira Tavares" <notifications@github.com> wrote:
>Ok, that went better than I expected.
>The problem was a field that had strange characters encoded in _deity_
>knows that encoding.
>Deleting the offending contact (recreated later by hand) fixed it.
>The VCARD property was "X-UNKNOWN-ELEMENT;TYPE=ÿþName:" with some value
>with some random chars. Notice that weird chars after the equal sign.
>I'm guessing some dav client added that with some weird encoding.
>Maybe it would be nice for vsyncdir to survive such errors (specially
>as the property is a proprietary of some other tool).
>Thx for vdirsync. :)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/506#issuecomment-247870549

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
