### ISSUE TITLE
syncing the wrong calendar

### ISSUE THREAD

**Issue by kaffeeknecht** [pimutils/vdirsyncer#509]
This is the Setup:
vdirsyncer 0.12.1
python 2.7.12 and 3.5.2 (both tested with that config) on ubuntu 16.04

We got some Oracle CalDAV running here. In my config, there is one pair configured for my own user's calendar and one for my colleague's calendar for which I have read access.
I have to authenticate for both calendars with my own credentials.

My own calendar is discovered and synced correctly.
But when I run a vdirsyncer discover calendar_colleague on that setup, my calendar is dicovered (and of course synced later). So in the and, I got two directories for my events and my colleagues events which both contain my events and nothing else.

[config.vdirsyncer.txt](https://github.com/pimutils/vdirsyncer/files/497250/config.vdirsyncer.txt)
[log.vdirsyncer.txt](https://github.com/pimutils/vdirsyncer/files/497251/log.vdirsyncer.txt)

**Comment by untitaker** [comment]
If you use `collections != null`, vdirsyncer will always try to discover all of your collections regardless of the path you provide. Usually this is an advantage, but in this case it isn't...

I wonder how to deal with this. I could indeed modify vdirsyncer to try to use the given URL as home collection before falling back to the current routine, but for now I recommend to figure out the full path to the calendar you want to sync (probably something like `url = https://calendar.xxx.de/dav/home/colleague@xxx.de/calendar`), and use `collections = null` in the pair section.

How do other clients handle this?

**Comment by untitaker** [comment]
Also if you want better docs on the `collections` parameter, I recommend using [https://vdirsyncer.readthedocs.io/en/master/tutorial.html](the tutorial from master), I added a section at the end that should be useful whenever situations like this arise.

**Comment by kaffeeknecht** [comment]
collections = null worked for me.
Thank you!

**Comment by untitaker** [comment]
Cool.

Can you point me to a client that discovers your colleague's collection? Preferrably one that doesn't require iOS or OS X.

**Comment by kaffeeknecht** [comment]
Thunderbird/Lightning seems to discover correctly.

**Comment by untitaker** [comment]
I'm working on this in #511, could you try that PR out?

**Comment by untitaker** [comment]
I just released 0.13.0, Python 2 should definetly not work anymore but Python 3 should, even with your own config.
