### ISSUE TITLE
Cannot build vdirsyncer 0.14.0 with python-urllib3 1.19

### ISSUE THREAD

**Issue by protist** [pimutils/vdirsyncer#518]
Before you submit bug reports: https://vdirsyncer.pimutils.org/en/stable/contributing.html

Things to include in your bugreport:

* Your vdirsyncer version: 0.13.1 and 0.14.0 (see below)
* If applicable, which server software (and which version) you're using: ownCloud 9.1.0 (stable)
* Your Python version: 3.5.2
* Your operating system: Arch Linux
* Your config file: N/A (see below)
* Use `vdirsyncer -vdebug` for debug output. The output is sensitive, but
  please attach at least the last few lines before the error (if applicable),
  censored as necessary. This is almost always the most useful information.

Probably the most consistent problem and easiest to diagnose for you is that vdirsyncer won't build with python-urllib3 1.19. However, I had some other problems that I'll briefly list first.

`vdirsyncer sync` (for vdirsyncer 0.13.1-1) fails with the update today of python-urllib3 to 1.19-1.
```
$ vdirsyncer -vdebug sync
debug: Fetching value for password.fetch with command strategy.
debug: Using 1 maximal workers.
Syncing owncloud_contacts/Contacts
debug: Loaded status for owncloud_contacts/Contacts
error: Unknown error occured for owncloud_contacts/Contacts: `verify_fingerprint` can only be used with requests-toolbelt versions >= 0.4.0
error: Use `-vdebug` to see the full traceback.
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/tasks.py", line 62, in sync_collection
debug:     force_delete=force_delete
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 270, in sync
debug:     b_info.prepare_new_status()
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 111, in prepare_new_status
debug:     for href, etag in self.storage.list():
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line 597, in list
debug:     headers=headers)
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line 346, in request
debug:     return utils.http.request(method, url, session=self._session, **more)
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/utils/http.py", line 47, in request
debug:     _install_fingerprint_adapter(session, verify_fingerprint)
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/utils/http.py", line 18, in _install_fingerprint_adapter
debug:     raise RuntimeError('`verify_fingerprint` can only be used with '
error: 1 out of 2 tasks failed.
```
Reverting to python-urllib3 1.18.1-1 fixes it.

I tried to upgrade to vdirsyncer 0.14.0 for this bug report. However, bumping the Arch Linux PKGBUILD to 0.14.0 fails to build, as does installing the `vdirsyncer-git` version. The output for building the former is [here](https://gist.github.com/protist/b8f758dad19c859dce2ec76408f0b443). I again reverted to python-urllib3 1.18.1-1, and this allowed me to build 0.14.0.

**Comment by untitaker** [comment]
I'll investigate but at first sight this seems like a packaging issue with ArchLinux rather than anything else.

**Comment by quite** [comment]
The problem seems to be up in urllib3, imported by requests-toolbelt, imported by vdirsyncer :) https://github.com/shazow/urllib3/pull/1025

**Comment by untitaker** [comment]
I'm still very dubious about this being the issue, as vdirsyncer works fine for me with the latest versions of requests-toolbelt and requests.

**Comment by hobarrera** [comment]
Works fine for me with urllib3 1.19:

Here's the full dependency tree:
```
$ pacman -Q $(pactree -l vdirsyncer) | sort | uniq
bash 4.3.046-1
bzip2 1.0.6-5
db 5.3.28-3
expat 2.2.0-2
filesystem 2015.09-1
gcc-libs-multilib 6.2.1-1
gdbm 1.12-2
glibc 2.24-2
iana-etc 20160927-1
lib32-gcc-libs 6.2.1-1
lib32-glibc 2.24-2
libffi 3.2.1-2
linux-api-headers 4.7-1
ncurses 6.0-4
openssl 1.0.2.j-1
perl 5.24.0-3
python 3.5.2-1
python-appdirs 1.4.0-4
python-atomicwrites 1.1.5-1
python-chardet 2.3.0-2
python-click 6.6-1
python-click-log 0.1.4-1
python-click-threading 0.4.0-2
python-packaging 16.8-1
python-pyparsing 2.1.10-1
python-requests 2.11.1-1
python-requests-toolbelt 0.7.0-1
python-setuptools 1:28.7.1-1
python-six 1.10.0-2
python-urllib3 1.19-1
readline 6.3.008-4
tzdata 2016i-1
vdirsyncer 0.14.0-1
zlib 1.2.8-4
```

**Comment by protist** [comment]
Thank you all. On my system, updating to the latest commit from urllib3 fixes this for me (thanks @quite!). I can now build vdirsyncer, and it runs fine, without error.

(For reference, building urllib3 was quite difficult. The check() step of the PKGBUILD took >6 hours. Eventually I got bored and just commented out the lines. It appeared to install fine.)
