### ISSUE TITLE
vdirsyncer does not find config at ~/.config/vdirsyncer/conf

### ISSUE THREAD

**Issue by TheRojam** [pimutils/vdirsyncer#524]
Before you submit bug reports: https://vdirsyncer.pimutils.org/en/stable/contributing.html

Things to include in your bugreport:

* Your vdirsyncer version version 0.14.0

* If applicable, which server software (and which version) you're using
* Your Python version 3.5.2
* Your operating system Linux AntonsArchBook 4.8.10-1-ARCH #1 SMP PREEMPT Mon Nov 21 11:55:43 CET 2016 x86_64 GNU/Linux
* Your config file
```
[general]
status_path = ~/.config/vdirsyncer/status


[pair google_calendar]
a = google_calendar_remote
b = google_calendar_local
collections = ["admin.amueller@gmail.com"]
conflict_resolution = "a wins"

[storage google_calendar_remote]
type = google_calendar
client_id = " ClientID.apps.googleusercontent.com "
client_secret = "secret"
token_file = ~/.config/vdirsyncer/tokens

[storage google_calendar_local]
type = filesystem
path = "~/.calendars/"
fileext = .ics
```

* critical: Error during reading config /home/therojam/.config/vdirsyncer/config: [Errno 2] No such file or directory: '/home/therojam/.config/vdirsyncer/config'

**Comment by geier** [comment]
Make sure the file is named config, not conf

Am 24. November 2016 22:31:50 MEZ, schrieb Anton <notifications@github.com>:
>Before you submit bug reports:
>https://vdirsyncer.pimutils.org/en/stable/contributing.html
>
>Things to include in your bugreport:
>
>* Your vdirsyncer version version 0.14.0
>
>* If applicable, which server software (and which version) you're using
>* Your Python version 3.5.2
>* Your operating system Linux AntonsArchBook 4.8.10-1-ARCH #1 SMP
>PREEMPT Mon Nov 21 11:55:43 CET 2016 x86_64 GNU/Linux
>* Your config file
>`[general]
>status_path = ~/.config/vdirsyncer/status
>
>
>[pair google_calendar]
>a = google_calendar_remote
>b = google_calendar_local
>collections = ["admin.amueller@gmail.com"]
>conflict_resolution = "a wins"
>
>[storage google_calendar_remote]
>type = google_calendar
>client_id = " ClientID.apps.googleusercontent.com "
>client_secret = "secret"
>token_file = ~/.config/vdirsyncer/tokens
>
>[storage google_calendar_local]
>type = filesystem
>path = "~/.calendars/"
>fileext = .ics
>`
>* critical: Error during reading config
>/home/therojam/.config/vdirsyncer/config: [Errno 2] No such file or
>directory: '/home/therojam/.config/vdirsyncer/config'
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/524

-- 
Sent from my phone. Please excuse my brevity.

**Comment by TheRojam** [comment]
> Make sure the file is named config, not conf
_Thanks for the hint :)_
now vsdirsyncer does not find the pair google_calender :(

**Comment by geier** [comment]
Does it not find the pair in the config or on the server? Please paste the error message.

**Comment by TheRojam** [comment]
I think the was misconfiguration.

**Comment by geier** [comment]
Does that mean it is working now?

**Comment by TheRojam** [comment]
@geier jep.
