### ISSUE TITLE
Problems with @ in UID

### ISSUE THREAD

**Issue by rohieb** [pimutils/vdirsyncer#526]
* Your vdirsyncer version
0.14.0
* If applicable, which server software (and which version) you're using
calypso 1.3
* Your Python version
2.7.12+
* Your operating system
Debian testing/unstable
* Your config file
basic caldav to filesystem syncing, not important here.

One of my calendar items has the UID `recentTopics-2015-12-01T09-45-00-9@ibr.cs.tu-bs.de`, and if I try to sync it, I get a `NotFoundError`:

```
debug: working on /calendar/rohieb/uni/recentTopics-2015-12-01T09-45-00-9@ibr.cs.tu-bs.de.ics
debug: Already normalized: '/calendar/rohieb/uni/recentTopics-2015-12-01T09-45-00-9@ibr.cs.tu-bs.de.ics'
debug: data = <?xml version="1.0" encoding="utf-8" ?>
debug:         <C:calendar-multiget xmlns:D="DAV:"
debug:             xmlns:C="urn:ietf:params:xml:ns:caldav">
debug:             <D:prop>
debug:                 <D:getetag/>
debug:                 <C:calendar-data/>
debug:             </D:prop>
debug:             <D:href>/calendar/rohieb/uni/recentTopics-2015-12-01T09-45-00-9@ibr.cs.tu-bs.de.ics</D:href>
debug:         </C:calendar-multiget>
debug: REPORT https://rohieb.name:5233/calendar/rohieb/uni/
debug: {'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8'}
debug: b'<?xml version="1.0" encoding="utf-8" ?>\n        <C:calendar-multiget xmlns:D="DAV:"\n            xmlns:C="urn:ietf:params:xml:ns:caldav">\n            <D:prop>\n                <D:getetag/>\n                <C:calendar-data/>\n            </D:prop>\n            <D:href>/calendar/rohieb/uni/recentTopics-2015-12-01T09-45-00-9@ibr.cs.tu-bs.de.ics</D:href>\n        </C:calendar-multiget>'
debug: Sending request...
debug: 207
debug: {'Server': 'Calypso/1.3 Python/2.7.9', 'Content-Length': '36', 'Date': 'Sun, 27 Nov 2016 04:32:17 GMT', 'Connection': 'Keep-Alive', 'Content-Type': 'text/xml'}
debug: b'<ns0:multistatus xmlns:ns0="DAV:" />'
error: Unknown error occured for neptun_uni: /calendar/rohieb/uni/recentTopics-2015-12-01T09-45-00-9@ibr.cs.tu-bs.de.ics
error: Use `-vdebug` to see the full traceback.
debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/cli/tasks.py", line 72, in sync_collection
debug:     partial_sync=pair.partial_sync
debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/sync.py", line 241, in sync
debug:     a_info.prepare_new_status()
debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/sync.py", line 134, in prepare_new_status
debug:     if prefetch else ()):
debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/storage/dav.py", line 477, in get_multi
debug:     raise exceptions.NotFoundError(href)
error: 1 out of 2 tasks failed.
```

If I change the UID on the server so it doesn't include an `@`, everything syncs fine :)

While debugging, I added some additional log output to `get_multi`, that's why you can see the contents of `data` above, which is sent to the server. It includes the literal `@` instead of the escaped `%40`, however, according to the respective RFCs, it should be escaped when part of a filename. But according to `storage/dav.py`, line 53, this behaviour is apparently by design to work around bugs in Radicale and OwnCloud:

 * https://github.com/owncloud/contacts/issues/581
 * https://github.com/Kozea/Radicale/issues/298

Any ideas how to solve this? The fault here is clearly at their side, but it seems we have to work with both variants, until they get their bugs fixed. Maybe try fetching both variants of the URL, with the literal `@` and with the escaped `%40`, and if one of them succeeds, don't fail?

**Comment by untitaker** [comment]
>The fault here is clearly at their side, but it seems we have to work with both variants, until they get their bugs fixed.

That ownCloud link is for the old contacts app, the new (maintained!) one doesn't have this problem. I sincerely stopped caring about Radicale's bugs, you can't work around all of them without breaking other servers.

>according to the respective RFCs, it should be escaped when part of a filename

`@` in URI paths don't have to be escaped. See definition of `pchar` in the URI RFC. So this isn't even a workaround that violates any RFC.
