### ISSUE TITLE
owncloud URL example is not correct

### ISSUE THREAD

**Issue by jdpipe** [pimutils/vdirsyncer#532]
Using vdirsyncer 0.14.0 installed via pip3 on Ubuntu 16.04 with Python 3.5.2.

I followed the documentation at 
https://vdirsyncer.pimutils.org/en/stable/tutorial.html#configuration
and
https://vdirsyncer.pimutils.org/en/stable/supported.html#owncloud

In both cases a URL of the form ".../owncloud/remote.php/caldav/" is suggested. This type of URL is similar to the one found in ownCloud web user interface itself (the 'primary CalDAV address' ends with /dav/ instead of /caldav in my ownCloud instance), but that, too, but didn't work for me.

Instead, I had to use a URL of the form ".../owncloud/remote.php/dav/calendars/USERNAME/CALENDARNAME" where USERNAME and CALENDARNAME were replaced with my own particular stuff. This URL is obtained in ownCloud under the [...] menu "Link" option for my particular calendar in the Calendar app.

The problem was that when using the earlier URL type, there was no error message; as I recall, I simply received an empty calendar. The problem was fixed when I switched to the second URL form.

**Comment by untitaker** [comment]
You are most likely setting `collections = null`, but in the tutorial there's a different value.

**Comment by jdpipe** [comment]
I had ["from a"] in the collections.

**Comment by untitaker** [comment]
Ah, ownCloud changed from `/remote.php/caldav/` to `/remote.php/dav/`, but I didn't update the docs. Fixed now, thanks!
