### ISSUE TITLE
verify_fingerprint doesn't work with self-signed certs

### ISSUE THREAD

**Issue by jdpipe** [pimutils/vdirsyncer#533]
Using vdirsyncer 0.14.0 on Ubuntu 16.04, installed with pip3 install and Python 3.5.2.

Documentation should be updated to show that the 'verify_fingerprint' option doesn't work with self-signed certificates. The only option for that case is to copy the certificate and key from the server (using 'make-ssl-cert' on the server gave me a single file which worked fine with the 'verify' option in vdirsyncer.

It would be great if the 'verify_fingerprint' option could be modified/expanded so that self-signed certificates are allowed. This would require passing the 'verify=False' option to Python Requests, but then somehow still obtaining the SSL fingerprint and checking that it's right. I think that forcing the user of a server with a self-signed certificate to obtain the .crt file is a bit excessive (but maybe there's a good reason for that, which I didn't see explained anywhere).

Apart from this rather major stumbling block (many new users are likely to be using self-signed certificates, after all, because that's what you always start with), I found the software to be very nice and well designed.

**Comment by untitaker** [comment]
You are supposed to set `verify = false` in combination with `verify_fingerprint` as shown in https://vdirsyncer.pimutils.org/en/stable/ssl-tutorial.html

**Comment by untitaker** [comment]
>many new users are likely to be using self-signed certificates, after all, because that's what you always start with

I seriously hope this changes with letsencrypt. Self-signed certs are IMO a non-solution. Certificate pinning is there for extra security, and to work around irreparably broken setups.

**Comment by jdpipe** [comment]
Thanks for the heads-up on 'letsencrypt'. It was pretty easy to set up, even on a 14.04 LTS server. Perhaps I can suggest that you emphasis it in your documentation as an easy alternative for people who have been using self-signed certificates up to now?

**Comment by untitaker** [comment]
>Perhaps I can suggest that you emphasise it in your documentation as an easy alternative for people who have been using self-signed certificates up to now?

Done!

>Having said this, what does a 'letsencrypt' certificate really verify?

Nothing in the sense you think of. The goal is to deploy HTTPS that can't be mitmed when attacking the wire, and letsencrypt does a good job there.

**Comment by a-t-0** [comment]
For those reading this, a working configuration for self-signed certificates was found and is included below.  [untitaker](https://github.com/pimutils/vdirsyncer/issues/533#issuecomment-269909892) suggested a method,  and [this documentation](https://vdirsyncer.pimutils.org/en/stable/ssl-tutorial.html#custom-root-cas) shows another under "Custom Root CA;s).

I used self-signed certificates for https for a self-hosted Nextcloud server over tor. So to connect to that (locally), I had to add the Root CA I used for that https to vdirsyncer. That can be done as follows:

```
[general]
status_path = "~/.config/vdirsyncer/status/"

[pair my_contacts]
a = "my_contacts_local"
b = "my_contacts_remote"
collections = ["from a", "from b"]
conflict_resolution = "b wins"

[storage my_contacts_local]
type = "filesystem"
path = "~/Documents/Contacts/"
fileext = ".vcf"

[storage my_contacts_remote]
type = "carddav"
verify = "/home/name/git/Hiveminds/Collabora-Online/ca.pem"

# We can simplify this URL here as well. In theory it shouldn't matter.
url = "https://localhost"
username = "your_username
password = "your_password"

[pair my_calendar]
a = "my_calendar_local"
b = "my_calendar_remote"
collections = ["from a", "from b"]
conflict_resolution = "b wins"

[storage my_calendar_local]
type = "filesystem"
path = "~/Documents/Calendar/"
fileext = ".ics"

[storage my_calendar_remote]
type = "caldav"
verify = "/home/name/git/Hiveminds/Collabora-Online/ca.pem"

# We can simplify this URL here as well. In theory it shouldn't matter.
url = "https://localhost"
username = "your_username"
password = "your_password"
```

Note that the extension of the Root CA should be `.pem` and not `.crt`. Next one can initiate the sync with:
```
vdirsyncer discover my_calendar
```
And that creates multiple collections, one per calendar that you have in your Nextcloud server.


Hope it helps someone!
