### ISSUE TITLE
Switch status format to sqlite

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#546]
This should've been obvious from the beginning (given offlineimap's development), but I guess it's never too late: We should switch to sqlite for storing the status metadata in `<statusfolder>/<pair>/<collection>.items`.

* `.collections` files should still be JSON, only the format for `.items` changes. At least I see no reason to do otherwise.
* The codebase for loading and saving `.collections` and `.items` files is weirdly entangled. We need to fix that.
* `sync` should take subclass of a `Status` interface. Requirement to remove coupling to either in-memory dict or sqlite as status storage, because otherwise we can't write decent unit tests. 

Goal: Ability to modify status in-place (instead of having "load" and "save" steps) opens the door to optimizing memory-efficiency of sync. I played with this once and it's not easy. We'll see.

**Comment by hobarrera** [comment]
Any reason for the collections file to still be json (rather than sql)? I feel like having a single caching format might simplify code with no real downside (though I may be generalizing a bit).

**Comment by untitaker** [comment]
I don't particularly care to be honest. Whatever turns out the easiest.

**Comment by untitaker** [comment]
Setting this to blocker since I pushed a half-assed implementation to master.
