### ISSUE TITLE
Add explicit documentation for Google storage `token_file` setting

### ISSUE THREAD

**Issue by teddywing** [pimutils/vdirsyncer#549]
version 0.14.1
Python 3.5.0
OS X

When trying to configure vdirsyncer for the first time using the `google_calendar` storage, I didn't set the `token_file` setting because I couldn't figure out what its value was meant to be.

I ended up doing an OAuth handshake manually to get an access token, which worked at first, until the token expired some time later.

After looking through the code, I realised that vdirsyncer actually does do the OAuth dance, but it was completely not obvious to me beforehand that I should just set `token_file` to an empty file and have the program do the work.

Can some extra documentation be added to https://github.com/pimutils/vdirsyncer/commit/12c22f19c0f92640cebaa497832e56d04ad8a6b0#diff-fd40cf2be7711772de9d8316da038cceR136 (or to the program itself) to clearly explain what to set `token_file` to?

**Comment by untitaker** [comment]
Sure! I think it would make sense to append this to the prose at https://github.com/pimutils/vdirsyncer/blob/cc8fe7f7737598d7a63cb4887c5a31b55d7975b4/docs/config.rst#google.

**Comment by teddywing** [comment]
Cool, thanks! I'll plan to draft a pull request this weekend.

**Comment by untitaker** [comment]
Great!

**Comment by untitaker** [comment]
Hey @teddywing any update on this?

**Comment by teddywing** [comment]
Sorry I never got back to you on this. I've been a little overwhelmed with work and life recently. Thanks for picking this up and adding the docs!
