### ISSUE TITLE
Lock pair during sync

### ISSUE THREAD

**Issue by madduck** [pimutils/vdirsyncer#561]
I erroneously filed this at first as https://github.com/pimutils/khal/issues/590.

I just noticed that I can accidentally run sync from cron and from the terminal at the same time. I have not actually produced a problem from this, but unless synchronous write access is part of the design (which I doubt), this is going to burn someone.

Please lock a collection while it's being processed. It'd be great if this could be done per-pair, rather than for the entire run.

This is quite possibly related to #462, but also not the same, I think.

**Comment by untitaker** [comment]
#462 is specific to filesystem storage, unless you're running into a race condition there (which can happen with vdirsyncer + another program too), it is not a big deal if two syncs overlap.

Locking per-pair is going to come anyway when the status format is switched to sqlite.

**Comment by untitaker** [comment]
FWIW #546 is the issue about switching status format to sqlite.

**Comment by untitaker** [comment]
#611 implements per-pair locks using exclusive transactions in sqlite. The error message is not pretty, but it'll do for now.
