### ISSUE TITLE
Problem with syncing and handling a non-color value as color metadata for a calendar

### ISSUE THREAD

**Issue by samdmarshall** [pimutils/vdirsyncer#565]
This is linked to https://github.com/pimutils/khal/issues/596.

## Description:
When setting up a new iCloud hosted calendar with vdirsyncer, I had the experience of it syncing down a metadata file for the calendar's color with the string contents of "`None`". I have since not been able to reproduce this behavior, but based on the debug log (posted below), this value still seems to exist server-side at least. The syncing of this value caused a crash in `ikhal` (see issue mentioned at beginning of this post) due to not being able to parse the value of "`None`" from the color metadata file. 

Steps (this is as precise as I can recall):
1. This calendar was created in [Fantastical 2 on OS X](http://flexibits.com/fantastical), and was assigned a color when it was created. 
2. I closed Fantastical and then went to modify the configuration file for `vdirsyncer` for it to discover and start syncing this calendar. The initial `vdirsyncer discover` and `vdirsyncer sync` worked successfully.
3. At this point I was able to view the calendar in `ikhal` without issue but it lacked a color.
4. I created the file `color` locally in this calendar's directory to give it color metadata and gave it a **different** custom color.
5. After this point I ran `vdirsyncer metasync` and was still able to view it in `ikhal`.
6. I then deleted the color metadata file and ran `vdirsyncer metasync` again, to ensure that there was a different color being used on the server-side.
7. I got back a file with the contents of "None", which I didn't notice until I ran `ikhal` and it crashed when trying to parse this string.
8. I was able to replace the value in the file with my custom color again and `ikhal` correctly opens the file.

Additional Notes:
* All of these pieces of software use different storage locations for the calendar data for this specific calendar. The only consistent thing here is what is on the server.
    * Calendar.app (Apple software) seems to correctly show the custom color I picked for the cloud.
    * Fantastical 2 doesn't show any color for this specific calendar.
    * ikhal shows the **different** custom color I have selected
* In the attached log below the calendar in question has had the color metadata file remove from the filesystem prior to running in an attempt to reproduce getting `vdirsyncer` to download this bit of metadata. I am not seeing it get re-created, but based on the server response it is definitely there.
* Note that there are two different colors involved in the syncing here, I have different colors for displaying in my terminal vs on my mobile phone's calendar app. The cloud stores the color of the calendar that my phone should have, and i have a local override of the color in my `khal` config.

## Version Info

**vdirsyncer** version:
`vdirsyncer, version 0.14.1`

Server Software:
`Apple iCloud`

Python Version:
`Python 3.6.0`

Operating System:
```
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32
```

Config file:
```
[general]
status_path = "~/.config/vdirsyncer/status"

[pair icloud]
a = "local_icloud"
b = "remote_icloud"
collections = ["from a", "from b"]
conflict_resolution = "a wins"
metadata = ["color", "displayname"]

[storage local_icloud]
type = "filesystem"
path = "~/Calendars/icloud"
fileext = ".ics"

[storage remote_icloud]
type = "caldav"
url = "https://caldav.icloud.com/"
username.fetch = ["command", "/usr/local/bin/secure-env", "get", "--key:vdirsyncer-icloud-username"]
password.fetch = ["command", "/usr/local/bin/secure-env", "get", "--key:vdirsyncer-icloud-password"]
verify_fingerprint = "F5:CC:B1:A7:24:13:36:07:54:8B:00:D8:EB:40:2E:FC:A3:07:6D:58"

```

Debug Log for `vdirsyncer --verbosity DEBUG metasync`:
```
Metasyncing icloud/XXX
debug: PROPFIND https://p31-caldav.icloud.com:443/***/calendars/XXX/
debug: {
    'User-Agent': 'vdirsyncer', 
    'Content-Type': 'application/xml; charset=UTF-8', 
    'Depth': '0'
}
debug: <?xml version="1.0" encoding="utf-8" ?>
debug:             <D:propfind xmlns:D="DAV:">
debug:                 <D:prop>
debug:                     <ns0:calendar-color xmlns:ns0="http://apple.com/ns/ical/" />
debug:                 </D:prop>
debug:             </D:propfind>
debug:         
debug: Sending request...
debug: 207
debug: {
    'Server': 'AppleHttpServer/3b804a0', 
    'Date': 'Sat, 25 Feb 2017 18:07:03 GMT', 
    'Content-Type': 'text/xml', 
    'Content-Length': '390', 
    'Connection': 'keep-alive', 
    'Last-Modified': 'Sat, 25 Feb 2017 21:35:07 GMT', 
    'DAV': '1, access-control, calendar-access, calendar-schedule, calendar-auto-schedule, calendar-audit, calendar-managed-attachments, calendarserver-sharing, calendarserver-subscribed, calendarserver-home-sync', 
    'Accept-Ranges': 'bytes', 
    'X-Responding-Server': '***', 
    'X-Transaction-Id': '***', 
    'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 
    'via': '***', 
    'X-Apple-Request-UUID': '***', 
    'access-control-expose-headers': 'X-Apple-Request-UUID, Via'
}
debug: <?xml version='1.0' encoding='UTF-8'?>
debug: <multistatus xmlns='DAV:'>
debug:   <response>
debug:     <href>/***/calendars/XXX/</href>
debug:     <propstat>
debug:       <prop>
debug:         <calendar-color symbolic-color='custom' xmlns='http://apple.com/ns/ical/'>None</calendar-color>
debug:       </prop>
debug:       <status>HTTP/1.1 200 OK</status>
debug:     </propstat>
debug:   </response>
debug: </multistatus>
debug: Key: color
debug: A: 
debug: B: None
debug: S: None
Copying color to remote_icloud/XXX
debug: PROPPATCH https://p31-caldav.icloud.com:443/***/calendars/XXX/
debug: {
    'User-Agent': 'vdirsyncer', 
    'Content-Type': 'application/xml; charset=UTF-8'
}
debug: <?xml version="1.0" encoding="utf-8" ?>
debug:             <D:propertyupdate xmlns:D="DAV:">
debug:                 <D:set>
debug:                     <D:prop>
debug:                         <ns0:calendar-color xmlns:ns0="http://apple.com/ns/ical/" />
debug:                     </D:prop>
debug:                 </D:set>
debug:             </D:propertyupdate>
debug:         
debug: Sending request...
debug: 207
debug: {
    'Server': 'AppleHttpServer/3b804a0', 
    'Date': 'Sat, 25 Feb 2017 18:07:03 GMT', 
    'Content-Type': 'text/xml', 
    'Content-Length': '423', 
    'Connection': 'keep-alive', 
    'Last-Modified': 'Sat, 25 Feb 2017 21:35:07 GMT', 
    'DAV': '1, access-control, calendar-access, calendar-schedule, calendar-auto-schedule, calendar-audit, calendar-managed-attachments, calendarserver-sharing, calendarserver-subscribed, calendarserver-home-sync', 
    'Accept-Ranges': 'bytes', 
    'X-Responding-Server': '***', 
    'X-Transaction-Id': '***', 
    'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 
    'via': '***', 
    'X-Apple-Request-UUID': '***', 
    'access-control-expose-headers': 'X-Apple-Request-UUID, Via'
}
debug: <?xml version='1.0' encoding='UTF-8'?>
debug: <multistatus xmlns='DAV:'>
debug:   <response>
debug:     <href>/***/calendars/XXX/</href>
debug:     <propstat>
debug:       <prop>
debug:         <calendar-color symbolic-color='custom' xmlns='http://apple.com/ns/ical/'/>
debug:       </prop>
debug:       <status>HTTP/1.1 200 OK</status>
debug:       <responsedescription>OK</responsedescription>
debug:     </propstat>
debug:   </response>
debug: </multistatus>
debug: PROPFIND https://p31-caldav.icloud.com:443/***/calendars/XXX/
debug: {
    'User-Agent': 'vdirsyncer', 
    'Content-Type': 'application/xml; charset=UTF-8', 
    'Depth': '0'
}
debug: <?xml version="1.0" encoding="utf-8" ?>
debug:             <D:propfind xmlns:D="DAV:">
debug:                 <D:prop>
debug:                     <ns0:displayname xmlns:ns0="DAV:" />
debug:                 </D:prop>
debug:             </D:propfind>
debug:         
debug: Sending request...
debug: 207
debug: {
    'Server': 'AppleHttpServer/3b804a0', 
    'Date': 'Sat, 25 Feb 2017 18:07:03 GMT', 
    'Content-Type': 'text/xml', 
    'Content-Length': '333', 
    'Connection': 'keep-alive', 
    'Last-Modified': 'Sun, 26 Feb 2017 02:07:03 GMT', 
    'DAV': '1, access-control, calendar-access, calendar-schedule, calendar-auto-schedule, calendar-audit, calendar-managed-attachments, calendarserver-sharing, calendarserver-subscribed, calendarserver-home-sync', 
    'Accept-Ranges': 'bytes',
     'X-Responding-Server': '***', 
    'X-Transaction-Id': '***', 
    'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
    'via': '***', 
    'X-Apple-Request-UUID': '***', 
    'access-control-expose-headers': 'X-Apple-Request-UUID, Via'
}
debug: <?xml version='1.0' encoding='UTF-8'?>
debug: <multistatus xmlns='DAV:'>
debug:   <response>
debug:     <href>/***/calendars/XXX/</href>
debug:     <propstat>
debug:       <prop>
debug:         <displayname>Work Events</displayname>
debug:       </prop>
debug:       <status>HTTP/1.1 200 OK</status>
debug:     </propstat>
debug:   </response>
debug: </multistatus>
debug: Key: displayname
debug: A: Work Events
debug: B: Work Events
debug: S: Work Events
```

**Comment by untitaker** [comment]
If you run `vdirsyncer metasync` multiple times until nothing is copied around anymore, what is the final value of `color` (or: to which value does `color` "converge")?

And if you delete the local color file and sync a few times again, to which value does `color` converge?

----

I just realized that the entire `color` attribute is a proprietary extension by Apple, so no matter what they do, we need to follow. Also we should probably get started on #230.

**Comment by samdmarshall** [comment]
Once I change it server-side I was able to sync that value I specified on the web interface, prior to that it would still sync down "None".

**Comment by untitaker** [comment]
Ok, but you're not able to find a value which iCloud would convert to None? (Such as an invalid color)

**Comment by samdmarshall** [comment]
Not that I can tell. The interface seems to automatically generate a hex-code color. An additional detail I just recalled: I tried to use the color name "orange" (forgetting this isn't a valid color name) originally, which may have had a hand in generating the "None" string.

**Comment by untitaker** [comment]
I can reproduce this as part of #567 (i.e. in the testsuite)

**Comment by samdmarshall** [comment]
Cool, thanks!
