### ISSUE TITLE
Read-only storage for caldav

### ISSUE THREAD

**Issue by ahemwe** [pimutils/vdirsyncer#566]
I want to use vdirsyncer as a local backup for my caldav-account at my provider. The backup should be in a single ics-file and vcirsyncer must not change anything on the server.
So I tried this config:

```
# CALDAV
[pair my_calendar]
a = "my_calendar_local"
b = "my_calendar_remote"
collections = ["from a", "from b"]

# Calendars also have a color property
metadata = ["displayname", "color"]

[storage my_calendar_local]
type = "singlefile"
path = "~/.calendars/%s.ics"

[storage my_calendar_remote]
type = "caldav"
url = "https://posteo.de:8443"
readonly = true
username = "its.me@posteo.de"
#password =
password.fetch = ["prompt", "Password for CalDAV"]

```

discover argument works fine, but if I try to sync, I only get: 
```

pi@raspberrypi:/mnt/usbstick $ vdirsyncer sync
Password for CalDAV:
Syncing my_calendar/opnshz
Syncing my_calendar/jtmfam
Syncing my_calendar/default
critical: Failed to initialize my_calendar_remote
critical:   - caldav storage doesn't take the parameters: readonly
critical: Failed to initialize my_calendar_remote
critical:   - caldav storage doesn't take the parameters: readonly
critical: Failed to initialize my_calendar_remote
critical:   - caldav storage doesn't take the parameters: readonly
```

How can I be shure that the backup is only one-way? 

Thanks a lot for support and this great tool. (Later on, I also want to use it for carddav)

**Comment by untitaker** [comment]
It's called `read_only`, not `readonly` :)

**Comment by untitaker** [comment]
Also I would rather recommend `filesystem` storage whenever possible for performance reasons (the difference is really large!). If you need to restore (which is very seldom) you still can sync your `filesystem` storage with a `singlefile` storage to get a single file.

**Comment by ahemwe** [comment]
Thanks a lot. I'm so sorry.

**Comment by untitaker** [comment]
No problem!
