### ISSUE TITLE
Test Cyrus in Travis

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#571]
[Cyrus](http://cyrusimap.org/) is a IMAP, CalDAV and CardDAV server, used by FastMail. We should test it in Travis.

**Comment by hobarrera** [comment]
I'm not 100% certain if they use an unmodified Cyrus or not. I've reached out to them to see if they can provide a test-only account, but I'll try to confirm if they use plain Cyrus or not.

**Comment by untitaker** [comment]
I can't imagine them doing significant changes on the DAV-implementation, though of course it'd be nice to have confirmation.

**Comment by hobarrera** [comment]
Yup. I'll keep you updated. If they *can* provide us with an account, it'd also make things simpler for us since we won't need to set up Cyrus instances on CI either.

**Comment by untitaker** [comment]
Sure (I wrote an implementation of this a year ago), but the server load isn't nothing.

**Comment by hobarrera** [comment]
I got a reply from FastMail, and a comped account can be done. They basically use Cyrus from upstream, so I think we just need to consider if installing/starting Cyrus as part of the tests is faster than using an external one (my guess is nope). We'd also avoid having to upgrade anything.

It's your call though, untitaker. 🙂

**Comment by untitaker** [comment]
Yeah, I think using FastMail's servers is easier

On 1 March 2017 01:24:49 CET, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>I got a reply from FastMail, and a comped account can be done. They
>basically use Cyrus from upstream, so I think we just need to consider
>if installing/starting Cyrus as part of the tests is faster than using
>an external one (my guess is nope). We'd also avoid having to upgrade
>anything.
>
>It's your call though, untitaker. 🙂
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/571#issuecomment-283205041

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hobarrera** [comment]
Great! I've created the account and gotten in touch.

I've added `FASTMAIL_USERNAME` (vdirsyncer@fastmail.com) and `FASTMAIL_PASSWORD` to travis CI.

I think these settings should do:
```
[storage calendars_fastmail]
type = "caldav"
url = "https://caldav.messagingengine.com/"
username = "vdirsyncer@fastmail.com"
password.fetch = ["command", "echo", "$FASTMAIL_PASSWORD"]
```

**Comment by untitaker** [comment]
Thanks, could you send me the creds via email, Travis' environment variables are write-only.

**Comment by hobarrera** [comment]
Sent.

**Comment by untitaker** [comment]
Ok, I just had to add my phone number to the account to enable CalDAV.

**Comment by hobarrera** [comment]
Oh yeah, it's a trail account (for now), since it's probably past midnight in Australia, so they haven't replied. :P

**Comment by hobarrera** [comment]
To close up on this: The account has been comped for three years (the max allowed), but a note has been left to extend it further upon request.

On the other hand, if we ever find any issues, quirks, or have to make non-standard changes to work with Fastmail/Cyrus, I've agreed to attempt to reach out to them, so they can fix it and add tests around it (so if you did, please let me know).

**Comment by untitaker** [comment]
As far as I know there's nothing out of the ordinary with FastMail's servers.

**Comment by hobarrera** [comment]
Good to know!
