### ISSUE TITLE
vdirsyncer is failing to sync

### ISSUE THREAD

**Issue by hobarrera** [pimutils/vdirsyncer#577]
I'm not sure why, but as of today, vdirsyncer is failing to sync:

Debug log: https://gist.github.com/hobarrera/5bf0ecfdd163db6dde8e277fac4ef3ec

```
$ vdirsyncer --version
vdirsyncer, version 0.15.0
```

I can't find anything called `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` locally:

```
$ ag e3b0c44298f
$ find . -iname "*e3b0c44298f*"
$
```

**Comment by hobarrera** [comment]
I tried deleting the vdirsyncer status directory (and setting `b wins`), but it didn't change anything.

**Comment by hobarrera** [comment]
Okay, so I deleted everything locally, and then it worked. Not sure if it's useful to keep this open.

**Comment by untitaker** [comment]
That might be a sha hash of parts of the file content. Given that the request body is empty, you should have an empty file locally that is rejected on upload.

On 3 March 2017 18:10:28 CET, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>I'm not sure why, but as of today, vdirsyncer is failing to sync:
>
>Debug log:
>https://gist.github.com/hobarrera/5bf0ecfdd163db6dde8e277fac4ef3ec
>
>```
>$ vdirsyncer --version
>vdirsyncer, version 0.15.0
>```
>
>I can't find anything called
>`e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`
>locally:
>
>```
>$ ag e3b0c44298f
>$ find . -iname "*e3b0c44298f*"
>$
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/577

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
We should probably print out local and remote href in normal output, also a bit more upfront validation: It should be possible to catch the case where you're uploading an empty file.

Im on mobile right now. Please make two new issues for that and close this one.

**Comment by hobarrera** [comment]
> That might be a sha hash of parts of the file content. Given that the request body is empty, you should have an empty file locally that is rejected on upload.

Given what I'd edited earlier on, that's quite possible.

> We should probably print out local and remote href in normal output, also a bit more upfront validation: It should be possible to catch the case where you're uploading an empty file.

Sure, yup.
