### ISSUE TITLE
Random "cannot import name 'metasync'" errors

### ISSUE THREAD

**Issue by madduck** [pimutils/vdirsyncer#583]
I am running vdirsyncer HEAD (3b713a14ab74fb05496d7562e88e21de4f4b6a5d) and I am getting non-deterministic errors about the inability to `import name 'metasync'`, e.g.:

    (.ve) fishbowl:…imutils/vdirsyncer|master|% vdirsyncer metasync
    Metasyncing madduck_calendar/calendar.ics
    error: Unknown error occured: cannot import name 'metasync'
    error: Use `-vdebug` to see the full traceback.
    Metasyncing madduck_contacts/addressbook.vcf
    Metasyncing kiddiecal/calendar.ics
    error: 1 out of 8 tasks failed.

The next run might show the error 3 times (and report 3 out of 8 tasks
failed), then I might get a run with 2 errors.

The only time it seems to work without errors is if I also specify `-vdebug`
(of course…). I think this might be related to `max_workers`, which gets set
to 1 when debug logging is active. Unfortunately `--max-workers` doesn't seem
to work yet as CLI-option.

This is on Debian sid, running with Python 3.6.0-1.

**Comment by untitaker** [comment]
`--max-workers` does work as a CLI option, but has to be specified after the `metasync` argument since it is a parameter of `metasync`, not a global one. This should work: `vdirsyncer -vdebug metasync --max-workers=99`.

I think I know where exactly the error is raised, but I don't know why. Python imports are supposed to be threadsafe.

**Comment by madduck** [comment]
Thanks for the hint.

The problem seems to occur only with `--max-workers=3` and higher. With 2 workers only, the first two collections get processed in parallel (1&2), but since one finishes before the other, 3 is started such that for a short time, 2&3 run in parallel and only when 2 exits, then 4 runs in parallel with 3.

If I run with 3 or more workers, then it seems as if the third task throws the error, right away.

**Comment by untitaker** [comment]
Just for verification, could you give me the full traceback you presumably get with `vdirsyncer -vdebug metasync --max-workers=3`?

**Comment by madduck** [comment]
Sure thing!

I think what you're after is:

    debug:   File "/home/madduck/code/pimutils/.ve/lib/python3.6/site-packages/vdirsyncer-0.15.1.de
    debug:     func(wq=self)
    debug:   File "/home/madduck/code/pimutils/.ve/lib/python3.6/site-packages/vdirsyncer-0.15.1.de
    debug:     from ..metasync import metasync
    error: Unknown error occured: cannot import name 'metasync'

The rest of the debug output doesn't seem to apply. If you still want/need it,
I can send it via e-mail (but not via Github).

**Comment by untitaker** [comment]
No thanks, thats good enough though I dont understand why import would fail. I suspect a heavily patched Debian package ;)

On 5 March 2017 23:59:44 CET, "martin f. krafft" <notifications@github.com> wrote:
>Sure thing!
>
>I think what you're after is:
>
>debug:   File
>"/home/madduck/code/pimutils/.ve/lib/python3.6/site-packages/vdirsyncer-0.15.1.de
>    debug:     func(wq=self)
>debug:   File
>"/home/madduck/code/pimutils/.ve/lib/python3.6/site-packages/vdirsyncer-0.15.1.de
>    debug:     from ..metasync import metasync
>    error: Unknown error occured: cannot import name 'metasync'
>
>The rest of the debug output doesn't seem to apply. If you still
>want/need it,
>I can send it via e-mail (but not via Github).
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/583#issuecomment-284270715

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by madduck** [comment]
Not impossible, but also unlikely I think. We do make an effort to stay as close as possible to upstream, and a cursory look over the 36 patches we do apply did not reveal anything that could give a hint.

Note that if I move the `from ..metasync import metasync` out of the function and into the global scope, the problem seems to go away. This makes me think the problem is actually in Python's sometimes-whacky import handling.

    index 7c32de3..d1bc0ef 100644
    --- a/vdirsyncer/cli/tasks.py
    +++ b/vdirsyncer/cli/tasks.py
    @@ -124,8 +124,8 @@ def repair_collection(config, collection, repair_unsafe_uid):
      	 repair_storage(storage, repair_unsafe_uid=repair_unsafe_uid)
    
    
    +from ..metasync import metasync
     def metasync_collection(wq, collection, general):
    -    from ..metasync import metasync
         pair = collection.pair
         status_name = get_status_name(pair.name, collection.name)

**Comment by untitaker** [comment]
Python's imports are supposed to be threadsafe and I haven't heard of anybody else having such a problem.

**Comment by madduck** [comment]
What do you stand to gain from importing inside the function? I think herein lies the problem.

**Comment by untitaker** [comment]
Importing inside the function avoids unnecessary imports. Particularly requests and pkg_resources take almost half a second to import, each.

**Comment by madduck** [comment]
I can't really notice any delay with the change I made, as shown above.

**Comment by untitaker** [comment]
You sure don't when running `metasync`, because in that case the import is executed either way.

**Comment by madduck** [comment]
Even with sync, there's really no noticeable difference.

**Comment by untitaker** [comment]
Just noticed that this particular import really doesn't contribute that much to the speedups. However, even changing it is an insufficient hack without really understanding the problem.

**Comment by madduck** [comment]
Yes, it is. ;)

**Comment by untitaker** [comment]
Does the same error pop up when you install vdirsyncer in a virtualenv? Or if you install a custom Python with https://github.com/yyuu/pyenv?

**Comment by madduck** [comment]
I am using a Python 3.6 virtualenv.

**Comment by untitaker** [comment]
Could you try installing a non-distro Python with pyenv, linked above?

On 6 March 2017 01:13:41 CET, "martin f. krafft" <notifications@github.com> wrote:
>I am using a Python 3.6 virtualenv.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/583#issuecomment-284275534

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by madduck** [comment]
You seem to be correct with it being Debian-related. I can't reproduce the problem with upstream's 3.6.0.

I've reported http://bugs.debian.org/857010

**Comment by untitaker** [comment]
I'll create a minimal testcase later, but I need to know if you can reproduce this on a fresh Debian or Ubuntu installation. 

On 7 March 2017 07:35:36 CET, "martin f. krafft" <notifications@github.com> wrote:
>You seem to be correct with it being Debian-related. I can't reproduce
>the problem with upstream's 3.6.0.
>
>I've reported http://bugs.debian.org/857010
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/583#issuecomment-284635205

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
Btw I think it's too early to report this as bug before we can't reproduce this in a clean VM

On 7 March 2017 07:35:36 CET, "martin f. krafft" <notifications@github.com> wrote:
>You seem to be correct with it being Debian-related. I can't reproduce
>the problem with upstream's 3.6.0.
>
>I've reported http://bugs.debian.org/857010
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/583#issuecomment-284635205

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by madduck** [comment]
We can still do that, but having the bug report means that the maintainers of the Debian package might also chime in saying "oh yeah, we've heard of this…", saving us all time.

**Comment by untitaker** [comment]
I can't reproduce the core issue on a fresh Debian VM: https://gist.github.com/untitaker/db68007e4c8e4186de136a9988caa411

I really think there's a lot of research necessary before filing bugs.

**Comment by madduck** [comment]
The gist you shared also produces no problem on Debian sid, so it doesn't seem to capture the core problem.

**Comment by untitaker** [comment]
I also can't reproduce the issue using vdirsyncer and two local storages. Something else is broken.

**Comment by madduck** [comment]
also sprach Markus Unterwaditzer <notifications@github.com> [2017-03-08 11:16 +1300]:
> I also can't reproduce the issue using vdirsyncer and two local
> storages. Something else is broken.

Well, my setup does use remote storages on one side of each of the
four pairs…

**Comment by legrostdg** [comment]
Trying to sync "color" with a local xandikos server, I ran into the same problem. I'm also using Debian sid, with the latest git version of vdirsyncer.

**Comment by untitaker** [comment]
@legrostdg Can you reproduce this with a filesystem-to-filesystem sync as well?

**Comment by legrostdg** [comment]
Running with "-v debug" seems to fix the issue: the metada are synchronized, and there is no error reported...

I have six calendars, and I sometimes get one "error: Unknown error occured: can't decompress data; zlib not available", and two to four "error: Unknown error occured: cannot import name 'metasync'"

**Comment by legrostdg** [comment]
@untitaker it is reproducible with a filesystem-to-filesystem sync

**Comment by untitaker** [comment]
Could you give me step-by-step instructions (including installing vdirsyncer) on how to reproduce this? I am trying to reproduce this in a VM.

**Comment by legrostdg** [comment]
My config:

    [storage calendars_local]
    type = "filesystem"
    path = "~/lib/calendars/"
    fileext = ".ics"
    
    [storage calendars_local_bis]
    type = "filesystem"
    path = "~/tmp/calendars/"
    fileext = ".ics"
    
    [pair my_calendars_bis]
    a = "calendars_local"
    b = "calendars_local_bis"
    collections = ["from a", "from b"]
    metadata = ["color"]

To install vdirsyncer, I cloned the repo, and "python3 setup.py build && python3 setup.py install --user".

    $ mkdir -p ~/lib/calendars/{a,b,c,d,e,f} ~/tmp/calendars
    $ for i in ~/lib/calendars/{a,b,c,d,e,f}; do echo '#008B8B' > "$i"; done
    $ vdirsyncer discover
    $ vdirsyncer sync
    $ vdirsyncer metasync

**Comment by untitaker** [comment]
Ok thanks, I'll try. Last question, which Debian is this?

**Comment by legrostdg** [comment]
sid

**Comment by untitaker** [comment]
Yeah I still can't reproduce this with @legrostdg's config, so it's neither reproducible for me on Debian Jessie nor on Sid, with neither 0.14.1 nor 0.14.0 nor 0.15.0 nor master.

Under Sid I also tried with both the preinstalled `python3` and `python3.6` packages.

**Comment by untitaker** [comment]
I see that 3.6.1 has come out, perhaps that fixes the issue @madduck ?

**Comment by madduck** [comment]
@untitaker Nope, the issue persists, though it seems it happens less often now.

**Comment by untitaker** [comment]
Since this appears to be a Debian bug, I think this can be closed.

I recommend using a Python installed with `pyenv`. Who knows what else is wrong with Debian's Python.

**Comment by solonovamax** [comment]
I know this is an ancient thread, but I'm going to necropost anyways.

It seems that this _isn't_ actually a debian bug since it's happening for me on arch linux too.

**Comment by WhyNotHugo** [comment]
Still uncertain whether it's the same bug or a different issue. In any case, let's continue discussion on #862.

**Comment by solonovamax** [comment]
> Still uncertain whether it's the same bug or a different issue. In any case, let's continue discussion on #862.

I'm absolutely sure that it's the same bug (as everything seems to match up), but yeah. Probably best to continue there.
I was just posting that so if someone stumbled across this, on another distro, they'd know it wasn't something else. (Probably should've mentioned the other issue tho)
