### ISSUE TITLE
ignore .git dir

### ISSUE THREAD

**Issue by legrostdg** [pimutils/vdirsyncer#588]
Using version 0.14.0 on Debian sid, with this config:
```ini
[pair my_contacts]
a = "my_contacts_local"
b = "my_contacts_remote"
collections = null

[storage my_contacts_local]
type = "filesystem"
path = "~/.contacts/"
fileext = ".vcf"

[storage my_contacts_remote]
type = "carddav"
url = "http://localhost:8080/user/contacts/"
username = "user"
password = "password"
```
and this structure:

    /home/user/.contacts/
    /home/user/.contacts/.git/
    /home/user/.contacts/contact1.vcf
     /home/user/.contacts/contact2.vcf

I'd like vdirsyncer to ignore "~/.contacts/.git/". `vdirsyncer discover` seems to consider .git as a collection.

    $ vdirsyncer discover my_contacts
    Discovering collections for pair my_contacts
    my_contacts_local:
      - ".git"
    my_contacts_remote:
      - "contacts"

(It would be great if .git was ignored for calendar collections, too)

**Comment by untitaker** [comment]
I wondered about this too, but it didn't seem to harm to consider it a collection. I think it would be neat if we ignored folders that have subfolders (instead of having a blacklist of folder names).

**Comment by legrostdg** [comment]
or maybe adding an `ignore-regex` parameter in the config file?

**Comment by legrostdg** [comment]
what I'd like to avoid is creating a `.git` dir on the server (which uses git)

**Comment by untitaker** [comment]
I'd much rather go for a method that doesn't add additional parameters, I think my proposal will fit your usecase.

**Comment by legrostdg** [comment]
I was afraid that being implicit rather than explicit would get unexpected issues later... What if I want to ignore `.gitignore`, or maybe even a specific vcard collection?

**Comment by untitaker** [comment]
If you want to ignore an actual vcard collection you will need to set the collections parameter in the pair section to the list of collections you do care about.

What I at least want to have are reasonable defaults, that includes ignoring directories that can't be collections. `.gitignore` is a file, so it shouldn't be detected as collection in any recent version of vdirsyncer.

**Comment by legrostdg** [comment]
It would still be great to be able to ignore a specific collection, instead of having to specify all the collections one wants to synchronize.

`.gitignore` may not be a problem, but it could happen with another VCS format.

**Comment by untitaker** [comment]
Sure, that's a different issue though.

>.gitignore may not be a problem, but it could happen with another VCS format.

`.hgignore` is also a file.

**Comment by legrostdg** [comment]
OK, I reported another issue :-).

I mentioned other VCS formats (which would use a dir without subdir) as an example. I think it's best to support "classic" configuration out of the box (so `.git` could be excluded by the mechanism you mentioned), and then add a possibility for the "power users" to do more (and an ignore collection parameter could be used for that).

**Comment by untitaker** [comment]
What you consider a "power user feature" I'd consider feature creep :)

**Comment by hobarrera** [comment]
Maybe just exclude dotfiles as well (I think ikhal does this).

If you have a non-dotfile directory with no subdirectories, then I'd say that it's up to the user to configure collections manually.

**Comment by untitaker** [comment]
If khal does this we should unify behavior across programs.

**Comment by hobarrera** [comment]
Agreed. Also make this behaviour part of the vdir spec (or have a `discovery` annex).

**Comment by untitaker** [comment]
@geier what does khal do with `.git` directories during discovery?

**Comment by geier** [comment]
Depends, in khal we know use globbing, see the settings documentation.

Quoting Markus Unterwaditzer (2017-03-09 19:29:56)

**Comment by untitaker** [comment]
Ok then I think our current behavior is fine.
