### ISSUE TITLE
use XDG_DATA_HOME

### ISSUE THREAD

**Issue by legrostdg** [pimutils/vdirsyncer#589]
As vdirsyncer already supports XDG_CONFIG_HOME, it would be great if it could support XDG_DATA_HOME, too.

**Comment by untitaker** [comment]
How do you imagine this support to look like? The only path that the user doesn't explicitly configure is the path of the config, and `XDG_CONFIG_HOME` is already respected there.

**Comment by legrostdg** [comment]
`$XDG_DATA_HOME/vdirsyncer` would at least have the `status` dir. The goal would be to be able to not have any `~/.vdirsyncer/` anymore if wanted.

**Comment by legrostdg** [comment]
Oh, sorry I did not remember the "status_path" configuration option... Can be closed.

**Comment by legrostdg** [comment]
Unfortunately, 

    [general]
    status_path = "$XDG_DATA_HOME/vdirsyncer/status/"

will create `~/.config/vdirsyncer/\$XDG_DATA_HOME/vdirsyncer/status/`. Environment variables should be allowed.

**Comment by untitaker** [comment]
I really don't want to expand environment variables since you'd then have to define how escaping works. You'll go down a rabbit hole there very quickly.

Please just hardcode the path.
