### ISSUE TITLE
add ability to store calendars in the calendar home path?

### ISSUE THREAD

**Issue by legrostdg** [pimutils/vdirsyncer#596]
I'm trying to use vdirsyncer with davdroid and [xandikos](https://jelmer.uk/code/xandikos/).

Syncing the contacts (local <-> xandikos, xandikos <-> davdroid) works, with:

    [pair my_contacts]
    a = "my_contacts_local"
    b = "my_contacts_remote"
    collections = null
    
    [storage my_contacts_local]
    type = "filesystem"
    path = "~/lib/contacts/"
    fileext = ".vcf"
    
    [storage my_contacts_remote]
    type = "carddav"
    url = "http://localhost:8080/user/contacts/"
    username = "user"
    password = "password"

The contacts are stored in the server as:

    /store/user/
    /store/user/contacts/
    /store/user/contacts/mycontact1.vcf
    /store/user/contacts/mycontact2.vcf
    ...

The story is different with calendars, though. I have my calendars in ~/lib/calendars:

    ~/lib/calendars/
    ~/lib/calendars/home/
    ~/lib/calendars/home/event1.ics
    ~/lib/calendars/home/event2.ics
    ...
    ~/lib/calendars/work/
    ~/lib/calendars/work/event1.ics
    ~/lib/calendars/work/event2.ics
    ...

I tried using this config:

    [pair my_calendars]
    a = "calendars_local"
    b = "calendars_remote"
    collections = ["home", "work"]
    
    [storage calendars_local]
    type = "filesystem"
    path = "~/lib/calendars/"
    fileext = ".ics"
    
    [storage calendars_remote]
    type = "caldav"
    url = "http://localhost:8080/user/calendars/"
    username = "user"
    password = "password"

Syncing local <-> xandikos gives:

    /store/user/
    /store/user/calendars/
    /store/user/home/
    /store/user/home/event1.ics
    /store/user/home/event2.ics
    ...
    /store/user/work/
    /store/user/work/event1.ics
    /store/user/work/event2.ics
    ...

Syncing xandikos <-> davdroid does not find home and work, as davdroid seems to expect this structure:

    /store/user/
    /store/user/calendars/
    /store/user/calendars/home/
    /store/user/calendars/home/event1.ics
    /store/user/calendars/home/event2.ics
    ...
    /store/user/calendars/work/
    /store/user/calendars/work/event1.ics
    /store/user/calendars/work/event2.ics

Is there a way for vdirsyncer to support this last structure instead?

**Comment by jelmer** [comment]
davdroid follows the calendar-home-set and addressbook-home-set returned by xandikos, but vdirsyncer doesn't seem to for some reason in this case. 

There's probably a bug in xandikos here...

@legrostdg could you paste the output of 'vdirsyncer -vdebug discover' ?

**Comment by jelmer** [comment]
(@legrostdg sent me one by email earlier)

It looks like the issue is that Xandikos is not sending a trailing / for the home set property.

**Comment by jelmer** [comment]
@legrostdg can you check again with xandikos master?

**Comment by legrostdg** [comment]
@jelmer did you push your changes? I see nothing new in master.

**Comment by untitaker** [comment]
I can't see a specific feature request here. If vdirsyncer can't figure out the correct path, it's a bug, at the same time Xandikos shouldn't allow vdirsyncer to create collections outside of homeset-uri.

**Comment by untitaker** [comment]
@legrostdg please try out #600.

**Comment by jelmer** [comment]
@legrostdg Xandikos change also pushed now.

**Comment by legrostdg** [comment]
OK, I confirm that with the latest vdirsyncer and xandikos, syncing local and xandikos creates the right structure for calendars. Thanks!
