### ISSUE TITLE
Add Xandikos to CI

### ISSUE THREAD

**Issue by hobarrera** [pimutils/vdirsyncer#597]
#596 triggered my interest in Xandikos, so it might be worth adding it to CI.

[Its site](https://jelmer.uk/code/xandikos/) actually lists vdirsyncer as compatible! :+1:

I'd like to tackle this myself, but would actually like to see if a free-tier heroku "machine" can run Xandikos. We might be able to avoid the bootstrapping/installation overhead.

**Comment by jelmer** [comment]
As far as I can tell xandikos should be able to run on Heroku. It doesn't require any C extensions, and is just wsgi. I haven't actually tried it on heroku myself, but if you do please let me know how it goes.

**Comment by untitaker** [comment]
I'd prefer it if i can run the tests offline

On 13 March 2017 19:46:08 CET, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>#596 triggered my interest in Xandikos, so it might be worth adding it
>to CI.
>
>[Its site](https://jelmer.uk/code/xandikos/) actually lists vdirsyncer
>as compatible! :+1:
>
>I'd like to tackle this myself, but would actually like to see if a
>free-tier heroku "machine" can run Xandikos. We might be able to avoid
>the bootstrapping/installation overhead.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/597

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
I'd actually strongly recommend running Xandikos within Travis, as otherwise it won't run within PRs.

**Comment by untitaker** [comment]
Also given that this runs on WSGI, it should be very performant to test locally (taking code from Radicale setup code). However it's important that xandikos can be used like a library to obtain a WSGI app.

**Comment by untitaker** [comment]
@jelmer Please use `install_requires` and `setuptools` in your `setup.py`, otherwise `pip install xandikos` does not install any dependencies.

**Comment by hobarrera** [comment]
Oh, I'd tried to do the heroku verion, but ended up failing and was about to give up.

Good thing it didn't work, since you preferred an offline-friendly version. XD

**Comment by jelmer** [comment]
setup.py now uses install_requires and setuptools, thanks to @hobarrera.

**Comment by jelmer** [comment]
(and a new version with these changes has been uploaded)

**Comment by jelmer** [comment]
FWIW setting up Xandikos on Heroku is fairly straightforward: 
https://github.com/jelmer/xandikos/blob/master/notes/heroku.rst

**Comment by untitaker** [comment]
Fair enough, but directly calling the WSGI app instead of making a real HTTP
request is much faster anyway.

**Comment by jelmer** [comment]
Agreed that the current approach works better for the vdirsyncer case. I just wanted to mention that running Xandikos on Heroku actually works.
