### ISSUE TITLE
Calendar not being "discovered"

### ISSUE THREAD

**Issue by tdehaeze** [pimutils/vdirsyncer#598]
I added a new "agenda" on my google calendar account linked with my facebook events : "	webcal://www.facebook.com/ical/u.php?uid=foo&key=bar". It displays correctly on google calendar but I can't get this new agenda on my computer with vdirsyncer.

Indeed, it doesn't display when I type `vdirsyncer discover`.

Do you know why ? 

Thank

* Your vdirsyncer version
`vdirsyncer, version 0.15.0`
* Your Python version
`Python3.6`
* Your operating system
```
ProductName:    Mac OS X
ProductVersion: 10.12.3
BuildVersion:   16D32
```
* Your config file
```ini
[general]
status_path = "~/.config/vdirsyncer/status/"

[pair google_calendar]
a = "google_calendar_remote"
b = "google_calendar_local"
collections = ["dehaeze.thomas@gmail.com", "foo@import.calendar.google.com"]
conflict_resolution = "a wins"

[storage google_calendar_remote]
type = "google_calendar"
token_file = "~/.config/dotfiles/private/token_file"
client_id = "foo"
client_secret = "bar"
#start_date = null
#end_date = null
#item_types = []

[storage google_calendar_local]
type = "filesystem"
path = "~/.calendars/google/"
fileext = ".ics"
```

**Comment by hobarrera** [comment]
There's a secret(?) page to configure which calendars are exposed via CalDAV, etc:

    https://calendar.google.com/calendar/syncselect

Make sure your calendar is checked there.

**Comment by tdehaeze** [comment]
Awesome, Thanks :)

**Comment by untitaker** [comment]
In principle this is already documented here: https://vdirsyncer.pimutils.org/en/stable/config.html#google, just pushed a commit that makes this flash out a bit more
