### ISSUE TITLE
vdirsyncer-xandikos: discover always tries to create existing calendars

### ISSUE THREAD

**Issue by legrostdg** [pimutils/vdirsyncer#604]
`vdirsyncer discover` creates the calendars in xandikos, after confirmation, but then, running `vdirsyncer discover` again asks to create these calendars again. If the answer is `y`, vdirsyncer fails.

    $ vdirsyncer -vdebug discover my_calendars
    debug: Using 1 maximal workers.
    Discovering collections for pair my_calendars
    calendars_local:
      - "work"
    debug: PROPFIND http://localhost:8080/
    debug: {'Depth': '1', 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
    debug: 
    debug:     <d:propfind xmlns:d="DAV:">
    debug:         <d:prop>
    debug:             <d:resourcetype />
    debug:         </d:prop>
    debug:     </d:propfind>
    debug:     
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '253', 'Content-Type': 'text/xml; charset="utf-8"'}
    debug: <ns0:multistatus xmlns:ns0="DAV:"><ns0:response><ns0:href>/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:resourcetype /></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: Skipping, not of resource type {urn:ietf:params:xml:ns:caldav}calendar: <Element '{DAV:}response' at 0x7f9bd3b45d18>
    debug: Given URL is not a homeset URL
    debug: PROPFIND http://localhost:8080/
    debug: {'Depth': '0', 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
    debug: 
    debug:         <d:propfind xmlns:d="DAV:">
    debug:             <d:prop>
    debug:                 <d:current-user-principal />
    debug:             </d:prop>
    debug:         </d:propfind>
    debug:         
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '318', 'Content-Type': 'text/xml; charset="utf-8"'}
    debug: <ns0:multistatus xmlns:ns0="DAV:"><ns0:response><ns0:href>/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:current-user-principal><ns0:href>/user/</ns0:href></ns0:current-user-principal></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: PROPFIND http://localhost:8080/user/
    debug: {'Depth': '0', 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
    debug: 
    debug:     <d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
    debug:         <d:prop>
    debug:             <c:calendar-home-set />
    debug:         </d:prop>
    debug:     </d:propfind>
    debug:     
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '366', 'Content-Type': 'text/xml; charset="utf-8"'}
    debug: <ns0:multistatus xmlns:ns0="DAV:" xmlns:ns1="urn:ietf:params:xml:ns:caldav"><ns0:response><ns0:href>/user/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns1:calendar-home-set><ns0:href>/user/calendars/</ns0:href></ns1:calendar-home-set></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: PROPFIND http://localhost:8080/user/calendars/
    debug: {'Depth': '1', 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
    debug: 
    debug:     <d:propfind xmlns:d="DAV:">
    debug:         <d:prop>
    debug:             <d:resourcetype />
    debug:         </d:prop>
    debug:     </d:propfind>
    debug:     
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '304', 'Content-Type': 'text/xml; charset="utf-8"'}
    debug: <ns0:multistatus xmlns:ns0="DAV:"><ns0:response><ns0:href>/user/calendars/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:resourcetype><ns0:collection /></ns0:resourcetype></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: Skipping, not of resource type {urn:ietf:params:xml:ns:caldav}calendar: <Element '{DAV:}response' at 0x7f9bd3b45e58>
    calendars_remote:
    warning: No collection "work" found for storage calendars_remote.
    Should vdirsyncer attempt to create it? [y/N]: y
    debug: PROPFIND http://localhost:8080/
    debug: {'Depth': '1', 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
    debug: 
    debug:     <d:propfind xmlns:d="DAV:">
    debug:         <d:prop>
    debug:             <d:resourcetype />
    debug:         </d:prop>
    debug:     </d:propfind>
    debug:     
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '253', 'Content-Type': 'text/xml; charset="utf-8"'}
    debug: <ns0:multistatus xmlns:ns0="DAV:"><ns0:response><ns0:href>/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:resourcetype /></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: Skipping, not of resource type {urn:ietf:params:xml:ns:caldav}calendar: <Element '{DAV:}response' at 0x7f9bd3b45e58>
    debug: Given URL is not a homeset URL
    debug: PROPFIND http://localhost:8080/
    debug: {'Depth': '0', 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
    debug: 
    debug:         <d:propfind xmlns:d="DAV:">
    debug:             <d:prop>
    debug:                 <d:current-user-principal />
    debug:             </d:prop>
    debug:         </d:propfind>
    debug:         
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '318', 'Content-Type': 'text/xml; charset="utf-8"'}
    debug: <ns0:multistatus xmlns:ns0="DAV:"><ns0:response><ns0:href>/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:current-user-principal><ns0:href>/user/</ns0:href></ns0:current-user-principal></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: PROPFIND http://localhost:8080/user/
    debug: {'Depth': '0', 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
    debug: 
    debug:     <d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
    debug:         <d:prop>
    debug:             <c:calendar-home-set />
    debug:         </d:prop>
    debug:     </d:propfind>
    debug:     
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '366', 'Content-Type': 'text/xml; charset="utf-8"'}
    debug: <ns0:multistatus xmlns:ns0="DAV:" xmlns:ns1="urn:ietf:params:xml:ns:caldav"><ns0:response><ns0:href>/user/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns1:calendar-home-set><ns0:href>/user/calendars/</ns0:href></ns1:calendar-home-set></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: PROPFIND http://localhost:8080/user/calendars/
    debug: {'Depth': '1', 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
    debug: 
    debug:     <d:propfind xmlns:d="DAV:">
    debug:         <d:prop>
    debug:             <d:resourcetype />
    debug:         </d:prop>
    debug:     </d:propfind>
    debug:     
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '304', 'Content-Type': 'text/xml; charset="utf-8"'}
    debug: <ns0:multistatus xmlns:ns0="DAV:"><ns0:response><ns0:href>/user/calendars/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:resourcetype><ns0:collection /></ns0:resourcetype></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: Skipping, not of resource type {urn:ietf:params:xml:ns:caldav}calendar: <Element '{DAV:}response' at 0x7f9bd3b45e08>
    debug: PROPFIND http://localhost:8080/
    debug: {'Depth': '0', 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
    debug: 
    debug:         <d:propfind xmlns:d="DAV:">
    debug:             <d:prop>
    debug:                 <d:current-user-principal />
    debug:             </d:prop>
    debug:         </d:propfind>
    debug:         
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '318', 'Content-Type': 'text/xml; charset="utf-8"'}
    debug: <ns0:multistatus xmlns:ns0="DAV:"><ns0:response><ns0:href>/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:current-user-principal><ns0:href>/user/</ns0:href></ns0:current-user-principal></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: PROPFIND http://localhost:8080/user/
    debug: {'Depth': '0', 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
    debug: 
    debug:     <d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
    debug:         <d:prop>
    debug:             <c:calendar-home-set />
    debug:         </d:prop>
    debug:     </d:propfind>
    debug:     
    debug: Sending request...
    debug: 207
    debug: {'Content-Length': '366', 'Content-Type': 'text/xml; charset="utf-8"'}
    debug: <ns0:multistatus xmlns:ns0="DAV:" xmlns:ns1="urn:ietf:params:xml:ns:caldav"><ns0:response><ns0:href>/user/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns1:calendar-home-set><ns0:href>/user/calendars/</ns0:href></ns1:calendar-home-set></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: MKCOL http://localhost:8080/user/calendars/work
    debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
    debug: <?xml version="1.0" encoding="utf-8" ?>
    debug:             <D:mkcol xmlns:D="DAV:">
    debug:                 <D:set>
    debug:                     <D:prop>
    debug:                         <D:resourcetype>
    debug:                             <D:collection/>
    debug:                             <ns0:calendar xmlns:ns0="urn:ietf:params:xml:ns:caldav" />
    debug:                         </D:resourcetype>
    debug:                     </D:prop>
    debug:                 </D:set>
    debug:             </D:mkcol>
    debug:         
    debug: Sending request...
    error: Unknown error occured: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
    error: Use `-vdebug` to see the full traceback.
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/cli/utils.py", line 306, in _worker
    debug:     func(wq=self)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/cli/tasks.py", line 89, in discover_collections
    debug:     rv = collections_for_pair(pair=pair, **kwargs)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/cli/discover.py", line 81, in collections_for_pair
    debug:     _handle_collection_not_found=handle_collection_not_found
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/cli/discover.py", line 183, in expand_collections
    debug:     _handle_collection_not_found
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/cli/discover.py", line 199, in _collection_from_discovered
    debug:     return _handle_collection_not_found(config, collection)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/cli/utils.py", line 377, in handle_collection_not_found
    debug:     args = cls.create_collection(**config)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/dav.py", line 420, in create_collection
    debug:     return d.create(collection)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/dav.py", line 257, in create
    debug:     url = self._create_collection_impl(url)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/dav.py", line 287, in _create_collection_impl
    debug:     headers=self.session.get_default_headers(),
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/dav.py", line 358, in request
    debug:     return http.request(method, url, session=self._session, **more)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/http.py", line 164, in request
    debug:     r = func(method, url, **kwargs)
    debug:   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    debug:     resp = self.send(prep, **send_kwargs)
    debug:   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 641, in send
    debug:     r.content
    debug:   File "/usr/lib/python3/dist-packages/requests/models.py", line 781, in content
    debug:     self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
    debug:   File "/usr/lib/python3/dist-packages/requests/models.py", line 706, in generate
    debug:     raise ChunkedEncodingError(e)
    error: 1 out of 1 tasks failed.

**Comment by legrostdg** [comment]
@jelmer

**Comment by untitaker** [comment]
This is a bug in xandikos (PROPFIND on a collection with `Depth: 1` is supposed to list subcollections), also this output is certainly scrambled because the sequence of requests is out of order. Since `vdirsyncer discover` is single-threaded by default I can't see a way requests in this order would be possible.

**Comment by jelmer** [comment]
Can you try again with current xandikos?This is probably https://github.com/jelmer/xandikos/issues/27

**Comment by legrostdg** [comment]
@untitaker, the fix in xandikos works, but there is one caveat: when running `vdirsyncer discover` again, if at least one calendar is empty, `vdirsyncer` fails (see jelmer/xandikos#27).
