### ISSUE TITLE
trying to sync contacts with xandikos raises PreconditionFailed error

### ISSUE THREAD

**Issue by legrostdg** [pimutils/vdirsyncer#605]
I don't know if something changed on xandikos (latest revision) or vdirsyncer (latest revision), but trying to sync contacts with xandikos now raises a `PreconditionFailed` error.

My config:

    [pair my_contacts]
    a = "my_contacts_local"
    b = "my_contacts_remote"
    collections = null
    
    [storage my_contacts_local]
    type = "filesystem"
    path = "~/lib/contacts/"
    fileext = ".vcf"
    
    [storage my_contacts_remote]
    type = "carddav"
    url = "http://localhost:8080/user/contacts/"
    username = "user"
    password = "password"

Here is the log:

    $ vdirsyncer -vdebug sync my_contacts
    debug: Using 1 maximal workers.
    Syncing my_contacts
    debug: Loaded status for my_contacts
    debug: PROPFIND http://localhost:8080/user/contacts/
    debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer', 'Depth': '1'}
    debug: <?xml version="1.0" encoding="utf-8" ?>
    debug:             <D:propfind xmlns:D="DAV:">
    debug:                 <D:prop>
    debug:                     <D:resourcetype/>
    debug:                     <D:getcontenttype/>
    debug:                     <D:getetag/>
    debug:                 </D:prop>
    debug:             </D:propfind>
    debug:             
    debug: Sending request...
    debug: 207
    debug: {'Content-Type': 'text/xml; charset="utf-8"', 'Content-Length': '433'}
    debug: <ns0:multistatus xmlns:ns0="DAV:"><ns0:response><ns0:href>/user/contacts/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:resourcetype><ns0:collection /></ns0:resourcetype><ns0:getcontenttype>httpd/unix-directory</ns0:getcontenttype><ns0:getetag>"4b825dc642cb6eb9a060e54bf8d69288fbee4904"</ns0:getetag></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: Already normalized: '/user/contacts/'
    debug: Skipping '/user/contacts/', is collection.
    Copying (uploading) item ed0e2e72a72d08638d393e59ef322270e4e7b4050ce80f0cba97a17783f2f12c to my_contacts_remote
    debug: Normalized URL from 'ed0e2e72a72d08638d393e59ef322270e4e7b4050ce80f0cba97a17783f2f12c.vcf' to '/user/contacts/ed0e2e72a72d08638d393e59ef322270e4e7b4050ce80f0cba97a17783f2f12c.vcf'
    debug: PUT http://localhost:8080/user/contacts/ed0e2e72a72d08638d393e59ef322270e4e7b4050ce80f0cba97a17783f2f12c.vcf
    debug: {'Content-Type': 'text/vcard', 'User-Agent': 'vdirsyncer', 'If-None-Match': '*'}
    debug: BEGIN:VCARD
    debug: VERSION:3.0
    debug: FN:Forest Gump
    debug: N:Gump;Forest
    debug: END:VCARD
    debug: Sending request...
    debug: 412
    debug: {'Content-Type': 'text/plain; encoding="utf-8"', 'Content-Length': '0'}
    
    error: Unknown error occured for my_contacts: Precondition Failed
    error: Use `-vdebug` to see the full traceback.
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/cli/utils.py", line 74, in handle_cli_error
    debug:     raise e
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/sync.py", line 268, in sync
    debug:     action.run(a_info, b_info, conflict_resolution, partial_sync)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/sync.py", line 299, in run
    debug:     self._run_impl(a, b)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/sync.py", line 330, in _run_impl
    debug:     href, etag = self.dest.storage.upload(self.item)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/base.py", line 15, in inner
    debug:     return f(self, *args, **kwargs)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/base.py", line 15, in inner
    debug:     return f(self, *args, **kwargs)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/dav.py", line 528, in upload
    debug:     return self._put(href, item, None)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/dav.py", line 499, in _put
    debug:     headers=headers
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/dav.py", line 358, in request
    debug:     return http.request(method, url, session=self._session, **more)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/http.py", line 179, in request
    debug:     raise exceptions.PreconditionFailed(r.reason)
    error: 1 out of 2 tasks failed.

On the server's side I get this:

    [pid: 12261|app: 0|req: 1/1] 127.0.0.1 (user) {38 vars in 505 bytes} [Tue Mar 21 12:25:58 2017] PROPFIND /user/contacts/ => generated 433 bytes in 7 msecs (HTTP/1.1 207) 2 headers in 91 bytes (1 switches on core 0)
    [pid: 12260|app: 0|req: 1/2] 127.0.0.1 (user) {38 vars in 623 bytes} [Tue Mar 21 12:25:58 2017] PUT /user/contacts/ed0e2e72a72d08638d393e59ef322270e4e7b4050ce80f0cba97a17783f2f12c.vcf => generated 0 bytes in 5 msecs (HTTP/1.1 412) 2 headers in 99 bytes (0 switches on core 0)

**Comment by untitaker** [comment]
Afaik you can't just store contacts directly in `http://localhost:8080/user/contacts/`, you need to create an addressbook like in NextCloud:

    collections = [["default", null, "default"]]

**Comment by legrostdg** [comment]
Mmh, this exact configuration used to work one week ago...

**Comment by untitaker** [comment]
@jelmer Is `/contacts/` an addressbook?

**Comment by jelmer** [comment]
With the --defaults setup only /user/contacts/addressbook is an address book, /user/contacts is not.

**Comment by untitaker** [comment]
That settles it. @legrostdg I'm not sure if all you have to do is change the config and run `discover` again, but in any case this is not vdirsyncer's issue.

**Comment by legrostdg** [comment]
OK, so, it's a problem on xandikos' side. Setting `collections = [["addressbook", null, "addressbook"]]` did not work either, but I'll report a bug on xandikos bug tracker :-). Thanks!

On vdirsyncer's side, the error message is not very informative, though, and should probably be improved:
"error: Unknown error occured for my_contacts: Precondition Failed"

**Comment by untitaker** [comment]
If you use `collections = null`, vdirsyncer disables a lot of sanity checks to see if the thing you're pointing it to is actually a valid collection. Originally it was the only option when vdirsyncer could only sync a single collection per pair, but it is nowadays intended as a workaround to be used with DAV-servers which don't implement the protocols for discovering collections properly.

I am actually surprised that `PreconditionFailed` is shown in this case, because that usually indicates a data race that has been prevented (a very unlikely edge case that only happens if two clients sync large amounts of data at the same time. Even in that situation it is as likely as an accidental hash collision).

**Comment by legrostdg** [comment]
Note that setting `collections = [["addressbook", null, "addressbook"]]` also returns `PreconditionFailed` (see https://github.com/jelmer/xandikos/issues/40)
