### ISSUE TITLE
Debian, Ubuntu, Fedora and nix ship outdated packages

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#606]
According to https://repology.org/metapackage/vdirsyncer/versions, Debian unstable ships with 0.14.0 (October 2016), Fedora rawhide with 0.14.1 (three weeks old), nixpkgs with 0.11.3 (half a year!!)

@pimutils/packaging Please make sure you are subscribed to something like https://github.com/pimutils/vdirsyncer/releases.atom or the PyPI releases and act accordingly. If you ship a version of vdirsyncer that contains bugs fixed last year because nobody is actively maintaining that package, I'd much rather see that package completely removed.

**Comment by untitaker** [comment]
Note that I'm specifically talking about unstable/bleeding-edge distro channels here. I understand that there can be nothing done about other channels.

**Comment by mathstuf** [comment]
Sorry, I've not been having much time for Fedora work lately. I may have time Wednesday.

**Comment by fpytloun** [comment]
Hello,
I am watching for new versions of software that I package periodically (so I know about 0.15.0 and 0.14.1). The reason why there's still 0.14.0 in Debian unstable was code freeze for stretch - to be able to make bugfixing upload + migration to stretch easily if it's needed.
I was thinking about getting 0.14.1 into Stretch but I am not sure if it will pass migration unfreeze as there are more changes than pure bugfixes. If you think that release is important, then I will package it and request migration unfreeze (reasoning from upstream will be surely useful in that case).

BTW, thank you for letting us know about such things. I like the way you care about how distributions ship your software and wish every software developer behave the same :-)

**Comment by untitaker** [comment]
If you want to use Google storage at all you will need the latest release, though if that means you're about to cherrypick bugfixes I'd prefer you not do it.

**Comment by AMDmi3** [comment]
Repology link above is actually incomplete, as there are two entries, ```vdirsyncer``` and ```python:vdirsyncer``` because some distros use python prefix (like py27- or python2-) and some don't. Unfortunately these cases require manual intervention. Anyway, I've merged them both into ```python:vdirsyncer```:

https://repology.org/metapackage/python:vdirsyncer/versions

So, FreeBSD and Gentoo also ship outdated packages. Also created update request for FreeBSD port: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=217981

**Comment by geier** [comment]
I have contacted repology's author, this should be fixed soon (is
already fixed on github).

Quoting Dmitry Marakasov (2017-03-21 19:19:49)

**Comment by geier** [comment]
I guess I should really pay better attention...

Quoting Dmitry Marakasov (2017-03-21 19:19:49)

**Comment by mathstuf** [comment]
FYI, Fedora uses anyita deployed on https://release-monitoring.org/. [vdirsyncer's entry](https://release-monitoring.org/project/5624). You can add mappings there by registering (no need to contact a maintainer).

**Comment by untitaker** [comment]
Well, it appears for logging in I need to either have a Fedora, Yahoo (?!) or OpenID account.

**Comment by DamienCassou** [comment]
Even though I love NixOS, it was taking me too long to maintain a working system so I stopped using it. I hope to switch back to it one day, but not before long. Maybe @jgeerds and @matthiasbeyer could take over.

**Comment by matthiasbeyer** [comment]
@DamienCassou definitively! NixOS has 1.14.1 in master (also in unstable), updated by me in 2017-02-15, so I'm not sure why @untitaker talks about 0.11.* ?

**Comment by untitaker** [comment]
Then it appears nixpkg has a stable channel. See link in OP.

On 22 March 2017 09:20:12 CET, Matthias Beyer <notifications@github.com> wrote:
>@DamienCassou definitively! NixOS has 1.14.1 in master (also in
>unstable), updated by me in 2017-02-15, so I'm not sure why @untitaker
>talks about 0.11.* ?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/606#issuecomment-288328133

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by matthiasbeyer** [comment]
Well yes, the stable channel (17.03) ships older versions, that's correct. I will file an issue asking whether it should be updated or not (well "stable" as in "old" or "stable" as in "stable", you know).

**Comment by AMDmi3** [comment]
There's also https://github.com/NixOS/nixos-homepage/pull/125 for NixOS which would allow repology to track nixpkgs unstable.

**Comment by untitaker** [comment]
@AMDmi3 it would be nice if repology could recognize the stable channels as "intentionally out of date". Perhaps orange as color?

**Comment by AMDmi3** [comment]
@untitaker I don't see a reason for this. Outdated is outdated. I plan to change logic of "outdated for maintainer" list though, which should not list a package as outdated as long as there is at least one newest package in the repository family (e.g. in all nixpkgs channels).

**Comment by untitaker** [comment]
Outdated is indeed outdated, but there's a difference between "actionable" and "not actionable". Your plan sounds good.

**Comment by AMDmi3** [comment]
> but there's a difference between "actionable" and "not actionable"

Yes, that I want to improve. It's more complex than just marking a single repo as "non actionable" though.

**Comment by untitaker** [comment]
Bump.

**Comment by untitaker** [comment]
Next week on friday I will remove all documentation links that point to packages not containing version 0.15.

**Comment by fpytloun** [comment]
0.14.1 is waiting for migration unblock to get to Stretch:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=858814

0.15 is in experimental already (thanks to @jelmer):
https://tracker.debian.org/pkg/vdirsyncer
