### ISSUE TITLE
Relicense under 3-clause BSD

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#610]
As per https://github.com/pimutils/vdirsyncer/issues/253 a portion of contributors has given me permission to relicense vdirsyncer under any OSI license. I want to switch to the 3-clause BSD for 0.16.

Contributors that have not commented on #253 are by @beli3ver and @benjaminfrank as far as I can tell (other contributions are one-line typo fixes). Would you be fine with your contributions being relicensed under the 3-clause BSD license?

**Comment by beli3ver** [comment]
Go ahead. Is for me OK.

Am 26. März 2017 14:37:09 MESZ schrieb Markus Unterwaditzer <notifications@github.com>:
>As per https://github.com/pimutils/vdirsyncer/issues/253 a portion of
>contributors has given me permission to relicense vdirsyncer under any
>OSI license. I want to switch to the 3-clause BSD for 0.16.
>
>Contributors that have not commented on #253 are by @beli3ver and
>@benjaminfrank as far as I can tell (other contributions are one-line
>typo fixes). Would you be fine with your contributions being relicensed
>under the 3-clause BSD license?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/610

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by hobarrera** [comment]
Any reason to pick the 3-clause BSD over MIT or ISC?

**Comment by untitaker** [comment]
The endorsement clause seems important to me.

On 26 March 2017 22:13:45 CEST, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>Any reason to pick the 3-clause BSD over MIT or ISC?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/610#issuecomment-289311467

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hobarrera** [comment]
Oh, sorry, I though of the 2-clause. I got them all mixed up.

As far as I'm concerned, I'm okay with any of the MIT/BSC/ISC licenses.

**Comment by untitaker** [comment]
Ah sorry, I thought you also signed the generic OSI-compatible waiver. Thanks for confirming.

**Comment by hobarrera** [comment]
Nope, I hadn't. 😛

**Comment by untitaker** [comment]
@benjaminfrank could you please leave a short comment on whether you approve of your contribution (the `.plist` file for vdirsyncer) being relicensed under the 3-clause BSD license? Thanks!

**Comment by untitaker** [comment]
Since @benjaminfrank didn't respond and technically I can relicense MIT code to 3-clause BSD without the copyright holder's consent, I will presumably do that tomorrow. However, I will exclude the `contrib` folder from the pypi distribution, partially due to the unrelated reason of minimizing tarball size.
