### ISSUE TITLE
Proposed changes for vdirsyncer/docs/installation.rst

### ISSUE THREAD

**Issue by toxadx** [pimutils/vdirsyncer#615]
Just want to inform you that since mid of March 2017 vdirsyncer added to the [OpenBSD ports collection](http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/productivity/vdirsyncer/).
Some extra information could be viewed at [unofficial ports catalog](http://openports.se/productivity/vdirsyncer).
Users are able to install vdirsyncer at OpenBSD with `doas pkg_add vdirsyncer` command.

**Comment by hobarrera** [comment]
Cool, thanks! FWIW, we should mention that there's a port *and* a binary package, since that's not always the case.

**Comment by hobarrera** [comment]
Oh, docs for the latest (unreleased) already mention this: http://vdirsyncer.readthedocs.io/en/latest/installation.html

**Comment by untitaker** [comment]
Yes, this is already done in master. Thanks for notifying though!
