### ISSUE TITLE
"Invalid XML encountered": control characters in XML

### ISSUE THREAD

**Issue by epilys** [pimutils/vdirsyncer#626]
* vdirsyncer version: 0.15.0
* server: owncloud 8.2.2 (has sabre 2.1.7)
* Python version: 3.6
* Your operating system: openbsd 6.1
* Your config file: not applicable

So I got this error: 
error: The server returned something vdirsyncer doesn't understand. Error message: InvalidXMLResponse('Invalid XML encountered: not well-formed (invalid token): line 430, column 21\nDouble-check the URLs in your config.',)

Running --verbosity=DEBUG and looking at this line in the returned XML, I find this (censored) event: 
```
<cal:calendar-data>BEGIN:VCALENDAR 
debug: VERSION:2.0                                                                             
debug: PRODID:ownCloud Calendar                                                                
 debug: CALSCALE:GREGORIAN                                                                      
 debug: BEGIN:VEVENT                                                                            
 debug: UID:<censored>                                                                          
 debug: DTSTAMP:<censored>                                                              
 debug: CREATED:<censored>                                                                     
 debug: LAST-MODIFIED:<censored>                                                               
 debug: SUMMARY:<censored>                                                            
 debug: DTSTART;TZID=<censored>                                                   
 debug: DTEND;TZID=<censored>                                                     
 debug: LOCATION:                                                                               
 debug: DESCRIPTION:<censored>^D<censored>                                  
 debug: CATEGORIES:                                                                             
 debug: END:VEVENT                                                                              
 debug: END:VCALENDAR                                                                           
 debug: </cal:calendar-data>
```
A stray ^D char in the DESCRIPTION field (how did it get there?). is returned. Other clients (owncloud web client, thunderbird lightning) don't throw an error at this. 

Running sync again...:
`error: The server returned something vdirsyncer doesn't understand. Error message: InvalidXMLResponse('Invalid XML encountered: not well-formed (invalid token): line 1189, column 21\nDouble-check the URLs in your config.',)`

Now what? 
```
...
1189: debug: SUMMARY:<censored>^O
...
```
Ugh! And not only 1189, but a lot of other events had stray ^Ds and ^Os. Turns out copying text from pdfs leaks control characters in your calendar, who knew. Removing those characters from the events allowed me to finally sync.

**Comment by untitaker** [comment]
Let's remove ASCII control characters before parsing XML. This change has to happen in [_parse_xml](https://github.com/pimutils/vdirsyncer/blob/09dacde3f3ef964e4e44800945ca3c6f40d0a1ee/vdirsyncer/storage/dav.py#L79).

**Comment by untitaker** [comment]
@epilys could you figure out where that control character came from?

**Comment by epilys** [comment]
@untitaker copy pasted from a pdf.

**Comment by untitaker** [comment]
Right, sorry, i forgot

On 11 May 2017 23:01:33 GMT+02:00, Manos Pitsidianakis <notifications@github.com> wrote:
>@untitaker copy pasted from a pdf. 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/626#issuecomment-300915794

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
