### ISSUE TITLE
Link to current version of documentation

### ISSUE THREAD

**Issue by f-breidenstein** [pimutils/vdirsyncer#634]
Hi,
this is not directly an issue with vdirsyncer, but rather with this repository: All the documentation links, link to the "/stable/" tag on ReadTheDocs, which is from February (Release 0.15). A lot of fixes in the documentation happend since then e.g. regarding the problem with quoted strings in the configuration file. Therefore it would maybe suitable to use the "/latest/" links from RTD to include all of these fixes.

Best regards,
    Felix

**Comment by untitaker** [comment]
Sure, but there could be documentation in master that only applies to the
development version of vdirsyncer. This is why I link /stable/ instead of
master.

It might make sense to release a new version because those typo fixes are
rather important.

**Comment by untitaker** [comment]
I will probably release a new version once #428 is resolved, because currently master is broken as well and this is the solution for it.
