### ISSUE TITLE
Show subject of synced entires

### ISSUE THREAD

**Issue by varac** [pimutils/vdirsyncer#636]
Please inlcude the subject of synced entries in the output of `vdirsyncer sync`.
It would increase the perception of what's going on behind the scene.

Before:

```
Copying (updating) item 20170328T102010Z-8788-1000-8785-10@roc to calendar_remote/personal
```

After:

```
Copying (updating) item 20170328T102010Z-8788-1000-8785-10@roc ("Meeting with Rob") to calendar_remote/personal
```

**Comment by untitaker** [comment]
We already have an issue open for this as far as I can remember.

**Comment by varac** [comment]
@untitaker oh, which one is it ?

**Comment by geier** [comment]
I believe it's this one: https://github.com/pimutils/vdirsyncer/issues/210

**Comment by hobarrera** [comment]
Closing as duplicate.
