### ISSUE TITLE
[feature request] Enable custom event handlers

### ISSUE THREAD

**Issue by raspbeguy** [pimutils/vdirsyncer#643]
Hi,
I think it would be nice to allow custom scripts execution when events happen, like added, modified or deleted item. It would be useful for people wanting to make stuff automatic, like sending a notification when an important calendar event is added or, in my case, adding a new contact in a database in order to be used by some other script.
Thanks.

**Comment by untitaker** [comment]
the `filesystem` storage already has such a hook for added and updated events. I was never really happy with those hooks being there though. In my opinion people should not rely too much on the synchronization engine, and figure out themselves which files were added and which ones removed. That way you will also stay in sync with changes made by local applications, and you won't be bound to vdirsyncer as a sync mechanism.

**Comment by raspbeguy** [comment]
Okay, that's cool. It's a shame it won't work for deleted items but I'll try to figure out a solution.
> In my opinion people should not rely too much on the synchronization engine, and figure out themselves which files were added and which ones removed.
Well it has the advantage not to need to run another diff utility.
> That way you will also stay in sync with changes made by local applications, and you won't be bound to vdirsyncer as a sync mechanism.
Why not extend `post_hook` mechanism to local changes then?
I prefer being bound to vdirsyncer as a sync mechanism than run another one. It would be useless, the work being done by an efficient tool already.

**Comment by untitaker** [comment]
>Why not extend post_hook mechanism to local changes then?

Because that's going far beyond what vdirsyncer is supposed to do: Synchronizing data.

**Comment by raspbeguy** [comment]
Maybe, but that what's beautiful : the "far beyond what vdirsyncer is supposed to do" part is not supposed to be implemented by you, but by people developping scripts that could be handled by `post_hook`.

You just extend event handling, and the users take the rest in charge. What could be the problem?

**Comment by untitaker** [comment]
>the "far beyond what vdirsyncer is supposed to do" part is not supposed to be implemented by you,

If vdirsyncer is supposed to notice changes made by local applications in the way you imagine, it would require extra computation in a way I'm not comfortable with.

I recommend checking your data into git, and commiting after each sync. That way you can read the local changes from the commit diff.

**Comment by raspbeguy** [comment]
> If vdirsyncer is supposed to notice changes made by local applications in the way you imagine, it would require extra computation in a way I'm not comfortable with.

The extra computation wouldn't be your responsability, would it? People are responsible of the hooks they use, right? I don't get why it would make you unconfortable. Anyway, in my case, I'm only interrested about changes events from remote source, but still, I still think that could be a nice feature and make the `post_hook` option more coherent.

> I recommend checking your data into git, and commiting after each sync. That way you can read the local changes from the commit diff.

Well that would mean running another diff tool, and that actually create useless extra computation.

**Comment by untitaker** [comment]
>Well that would mean running another diff tool, and that actually create useless extra computation.

I meant that vdirsyncer would have to do the same extra computation, *in addition to the syncing*. Whether it happens in git or in vdirsyncer doesn't make a difference.

**Comment by raspbeguy** [comment]
When vdirsyncer syncs, doesn't it make a diff between local and remote before?

**Comment by hobarrera** [comment]
Further discussing how this is out-of-scope: what prevents you from writing a script to do this?

```sh
# Dummy example script
vdirsyncer sync || notify-send "sync failed"
another_command
```

> When vdirsyncer syncs, doesn't it make a diff between local and remote before?

No, in fact, both storages can be local.

**Comment by raspbeguy** [comment]
> No, in fact, both storages can be local.

Well, between local and remote or both remote, that doesn't change my question.
Concerning your snippet, I don't see how it is related to the topic.

**Comment by untitaker** [comment]
>When vdirsyncer syncs, doesn't it make a diff between local and remote before?

Actually yes you're right it does, but the entire thing would require a refactor from a storage specific parameter to something that is embedded in the synchronization algorithm. I really don't want to be the one maintaining that. Having the hooks as storage parameter is somewhat acceptable because they are separated into a module that hasn't changed in half a year. The synchronization module has changed a lot, and is still badly written.

Perhaps a separate hook tool is needed. The additional computation is negligible.

**Comment by raspbeguy** [comment]
> Actually yes you're right it does, but the entire thing would require a refactor from a storage specific parameter to something that is embedded in the synchronization algorithm. I really don't want to be the one maintaining that.

Okay, that is a more-than-valid argument.

**Comment by untitaker** [comment]
Cool, I'll close this then. Something that keeps track of changes and executes some hooks would be a 100-line Python script, at most. I would recommend doing that, or using git (which gives you a few nice features like version history, rollback).

**Comment by untitaker** [comment]
Also if somebody ends up writing that I would like to have it in the pimutils repo.

**Comment by untitaker** [comment]
Another rant because it just came to my mind: Judging from the contribution stats it appears that vdirsyncer already is an unapproachable codebase as-is. Putting in more features doesn't help that. We do need more people working on pimutils though. Hence I think more smaller projects would be better.

**Comment by geier** [comment]
> Judging from the contribution stats it appears that vdirsyncer already is an unapproachable codebase as-is.

Other interpretation: it does what people expect it to do well enough.

**Comment by untitaker** [comment]
@geier I don't think that's true. There are a lot of feature requests submitted by third parties compared to pull requests. That ratio appears to be much better for khal and todoman.

**Comment by geier** [comment]
To be fair, in khal it's mostly you and hobarrera, and I don't contribute to vdirsyncer because it does what I expect it to do.

**Comment by untitaker** [comment]
Nah, apart from that I do think that khal and todoman have more "outside" contributors.

**Comment by hobarrera** [comment]
todoman has a much simpler codebase though (in great deal because what is does is a lot simpler), so it's really more welcoming to newcomers. (I believe the same applies to khal)

Syncing is harder, and lots of parts need to be understood together before anything can be done on vdirsyncer, so that probably moves the contribution barrier up a bit. But again, it's simply related to what it does being more complex.

FWIW, though, vdirsyncer does everything I need it to, so I'm less inclined to contribute as much.

**Comment by untitaker** [comment]
It could be that vdirsyncer is more complex to grasp as a tool, but I rather
consider it as a problem of vdirsyncer rather than the problem it tries to
solve.

Anyway, I continuously try to minimize vdirsyncer's codebase for this reason.
