### ISSUE TITLE
Update docs for tutorial (stable)

### ISSUE THREAD

**Issue by pfertyk** [pimutils/vdirsyncer#645]
I tried to configure vdirsyncer according to the tutorial:
https://vdirsyncer.pimutils.org/en/stable/tutorial.html
The line `status_path = ~/.vdirsyncer/status/` causes the following error when running `vdirsyncer discover`:
```
Section "general": Section "general", option "status_path": Expecting value: line 1 column 1 (char 0)
```
When the path is in quotes everything works fine. I wanted to fix this but it seems that vdirsyncer repo already contains a correct version (file: `docs/tutorial.rst`). So most likely the page with documentation has not been refreshed. Could you update it?

I'm using Python 3.5 and vdirsyncer 0.15.0

**Comment by cjwatson** [comment]
Looks like there just hasn't been a release since then; the commit that fixed that (5e0dc0d5aae68faaf2816f00340ddbd502bd1699) postdates 0.15.0.

**Comment by untitaker** [comment]
Yup, closing this. I want to do a new release but the iCloud tests fail :(

**Comment by pfertyk** [comment]
Thanks, can't wait for the new release :)
