### ISSUE TITLE
Reenable iCloud tests

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#646]
I am going to push a commit that will disable iCloud tests. iCloud recently started requiring 2fa-authentication, unfortunately I forgot the necessary credentials for that. Also the Apple devices I used to create the original iCloud account are too old to use 2fa with.

I am looking into getting my hands on an Apple device with at least iOS 9+ (or [any compatible device](https://support.apple.com/en-us/HT205075)) which I then can also use as a permanent testing device. But it will take time. In the meantime the tests will have to stay disabled.

**Comment by hobarrera** [comment]
I've an iPhone 6, but my personal iCloud account is used for personal data. Is there any way I can help? (eg: some one-time configuration, etc).

**Comment by untitaker** [comment]
If you manage to set up a new iCloud acct with 2fa that can then be linked to my phone number (for the second factor), that'd work.

Make sure to delete your personal data, should it get synced accidentally.

On 2 July 2017 00:39:42 GMT+02:00, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>I've an iPhone 6, but my personal iCloud account is used for personal
>data. Is there any way I can help? (eg: some one-time configuration,
>etc).
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/646#issuecomment-312459414

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
More specifically, an Apple device is only necessary for creating the account, after that it could work without it I think.

On 2 July 2017 00:39:42 GMT+02:00, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>I've an iPhone 6, but my personal iCloud account is used for personal
>data. Is there any way I can help? (eg: some one-time configuration,
>etc).
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/646#issuecomment-312459414

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hobarrera** [comment]
Apparently, you can create one [here](https://www.icloud.com/). Are you prompted at some point to interact with a apple device to continue?

**Comment by untitaker** [comment]
That doesn't work. The account has limited features, i.e. calendar is missing.

**Comment by untitaker** [comment]
I think that I need a testing device in the long run again though, because whenever the iCloud tests fail I have to have some point of reference for how correct client behavior should look like.

I have an iPhone 6+ with a shattered display, [ebay has a cheap replacement screen](http://www.ebay.at/itm/Display-fur-iPhone-6-PLUS-mit-RETINA-LCD-Glas-VORMONTIERT-Komplett-Front-Schwarz-/132216399859?hash=item1ec8b627f3:g:7BMAAOSwaeRZNSQs) for 20€. So if you want to see that, please donate to my PayPal so I can buy the screen (I have no personal goal in supporting iCloud, so I don't want to spend money on it).

**Comment by untitaker** [comment]
I recently bought the screen for purposes outside of vdirsyncer.

**Comment by untitaker** [comment]
Done
