### ISSUE TITLE
discovery not using url path part

### ISSUE THREAD

**Issue by WhilelM** [pimutils/vdirsyncer#650]
I can't initialize remote storage (nextcloud 11). Seems to me that
vdirsyncer not using a correct URL to discover each addressbook.

The remote storage URL is https://vm.laressourcerieverte.com/nextcloud
and it request https://vm.laressourcerieverte.com/.well-known/carddav
url during discovery.

* Your vdirsyncer version

0.16.0

* Your Python version

python3                    3.5.3-1
python3-atomicwrites       1.1.5-1
python3-click              6.6-1
python3-click-log          0.1.8-1
python3-click-threading    0.4.3-1
python3-requests           2.12.4-1
python3-requests-toolbelt  0.7.0-1

* Your operating system

Debian Release: 9.0
  APT prefers stable
  APT policy: (500, 'stable')
Architecture: amd64 (x86_64)
Foreign Architectures: i386

* Your config file

[general]
status_path = "~/.vdirsyncer/status/"

[pair appairage_lrv]
a = "contacts_lrv_local"
b = "contacts_lrv_distant"
collections = ["from a", "from b"]
conflict_resolution = "b wins"
metadata = ["displayname"]

[storage contacts_lrv_local]
type = "filesystem"
path = "~/.contacts/lrv/"
fileext = ".vcf"

[storage contacts_lrv_distant]
type = "carddav"
url = "https://vm.laressourcerieverte.com/nextcloud/"
username = "christophe,moille"
password.fetch = ["prompt", "Password for CalDAV lrv"]
verify_fingerprint = "30:EA:98:60:96:21:1F:18:F6:AD:63:88:18:FA:71:79:0E:FA:23:31:AB:79:51:E9:D5:AE:42:B0:A4:AF:9A:25"

**Comment by untitaker** [comment]
Please format your report correctly. The GitHub help contains documentation about this.

On 5 July 2017 17:32:44 GMT+02:00, WhilelM <notifications@github.com> wrote:
>Package: vdirsyncer
>Version: 0.16.0-1
>Severity: important
>
>I can't initialize remote storage (nextcloud 11). Seems to me that
>vdirsyncer not using a correct URL to discover each addressbook.
>
>The remote storage URL is https://vm.laressourcerieverte.com/nextcloud
>and it request https://vm.laressourcerieverte.com/.well-known/carddav
>url during discovery.
>
>**debug output:**
>
>16:58:41 whilelm@littlegr82:~$ vdirsyncer -vdebug discover             
>                                                                       
>debug: Using 1 maximal workers.                                        
>                                                                       
>debug: Fetching value for password.fetch with prompt strategy.         
>                                  
>Password for CalDAV lrv:                                       
>Discovering collections for pair appairage_lrv                         
>                                  
>contacts_lrv_local:                                                    
>                                  
>debug: PROPFIND https://vm.laressourcerieverte.com/nextcloud/          
>                                  
>debug: {'User-Agent': 'vdirsyncer/0.16.0', 'Content-Type':
>'application/xml; charset=UTF-8', 'Depth': '1'}
>debug:                                                                 
>                                   
>debug:     <d:propfind xmlns:d="DAV:">             
>debug:         <d:prop>                                                
>                      
>debug:             <d:resourcetype />                                  
>                                                                       
>debug:         </d:prop>                                               
>                                                                       
>debug:     </d:propfind>                                               
>                                                                       
>debug:                                                                 
>                                                                       
>debug: Sending request...                                              
>                                                                       
>debug: 405                                                             
>                                                                       
>debug: {'Status': '405 Method Not Allowed', 'X-XSS-Protection': '1;
>mode=block', 'Set-Cookie': 'ocyart057i15=pdrp59m4656or0np52u56q2sm5;
>path=/nextcloud; HttpO
>nly,
>oc_sessionPassphrase=Lf9K0UyR4WRLqdNitV1RONmz4hWgHF9%2FmGFuRNElKyqkTjTGCe6se%2F7lSaSVRcZHtBrn%2B5J2VBVit6RmCTDTSTZmxljSNSDfrh5lx9R75LoTMVz70IZE98zKD1lCJEf
>S; path=/nextcloud; secure; httponly, nc_sameSiteCookielax=true;
>path=/nextcloud; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59
>GMT; SameSite=lax, nc_same
>SiteCookiestrict=true; path=/nextcloud; httponly;secure; expires=Fri,
>31-Dec-2100 23:59:59 GMT; SameSite=strict,
>ocyart057i15=k3hpojldshn35bm802uvhosgv2; path=
>/nextcloud; secure; HttpOnly', 'Content-Length': '0', 'Content-Type':
>'text/html; charset=UTF-8', 'X-Download-Options': 'noopen',
>'X-Robots-Tag': 'none', 'Cont
>ent-Security-Policy': "default-src 'self'; script-src 'self'
>'unsafe-eval'
>'nonce-SmhkRGhiak4xZDN6R0RsNmY2YXM5ZGRRSnNuVnArVVVJaFlwR0N4Sytocz06U0YxeTU5S2RtNjJnW
>W5kTUtPRHZrdVYvRWY2OHhLOWdVV1ZQWDNRenNTND0='; style-src 'self'
>'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self'
>data:; media-src *; connect
>-src *", 'Server': 'Apache/2.4.10 (Debian)', 'Pragma': 'no-cache',
>'X-Content-Type-Options': 'nosniff', 'Cache-Control': 'no-store,
>no-cache, must-revalidate,p
>ost-check=0, pre-check=0', 'X-Permitted-Cross-Domain-Policies': 'none',
>'Date': 'Wed, 05 Jul 2017 14:58:50 GMT', 'Strict-Transport-Security':
>'max-age=15552000
>; includeSubDomains; preload', 'Connection': 'Keep-Alive', 'Expires':
>'Thu, 19 Nov 1981 08:52:00 GMT', 'X-Frame-Options': 'SAMEORIGIN',
>'Keep-Alive': 'timeout=
>5, max=100'}
>                                          
>debug: Given URL is not a homeset URL                                  
>                                                              [122/513]
>debug: PROPFIND https://vm.laressourcerieverte.com/nextcloud/
>debug: {'User-Agent': 'vdirsyncer/0.16.0', 'Content-Type':
>'application/xml; charset=UTF-8', 'Depth': '0'}
>debug:                      
>debug:         <d:propfind xmlns:d="DAV:">
>debug:             <d:prop>
>debug:                 <d:current-user-principal />
>debug:             </d:prop>                                           
>                                                                       
>debug:         </d:propfind>                                           
>                                                                       
>debug:                                                                 
>                                                                       
>debug: Sending request...                                              
>                                                                       
>debug: 405                                                             
>                                                                       
>debug: {'Status': '405 Method Not Allowed', 'X-XSS-Protection': '1;
>mode=block', 'Set-Cookie': 'ocyart057i15=ivtq8v7if1jsuvsbitd946h626;
>path=/nextcloud; secu$
>e; HttpOnly', 'Content-Length': '0', 'Content-Type': 'text/html;
>charset=UTF-8', 'X-Download-Options': 'noopen', 'X-Robots-Tag': 'none',
>'Content-Security-Pol$
>cy': "default-src 'self'; script-src 'self' 'unsafe-eval'
>'nonce-c2E2V1JSeEtITkw1ZjR6US9raHRWdmNFNzB3VG5sdmVLa3BnZVpXZDBIQT06MytTbkozWWFVcUtxQmNMbXFRNHVNY1VyM$
>h0Ni9SR3FXVGtHUHMza20wVT0='; style-src 'self' 'unsafe-inline';
>frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *;
>connect-src *", 'Server$
>: 'Apache/2.4.10 (Debian)', 'Pragma': 'no-cache',
>'X-Content-Type-Options': 'nosniff', 'Cache-Control': 'no-store,
>no-cache, must-revalidate, post-check=0, pr$
>-check=0', 'X-Permitted-Cross-Domain-Policies': 'none', 'Date': 'Wed,
>05 Jul 2017 14:59:20 GMT', 'Strict-Transport-Security':
>'max-age=15552000; includeSubDoma
>ins; preload', 'Connection': 'Keep-Alive', 'Expires': 'Thu, 19 Nov 1981
>08:52:00 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'Keep-Alive':
>'timeout=5, max=99'}
>
>debug: Trying out well-known URI                                       
>                                                              [102/513]
>debug: PROPFIND https://vm.laressourcerieverte.com/.well-known/carddav
>debug: {'User-Agent': 'vdirsyncer/0.16.0', 'Content-Type':
>'application/xml; charset=UTF-8', 'Depth': '0'}
>debug: 
>debug:         <d:propfind xmlns:d="DAV:">
>debug:             <d:prop>
>debug:                 <d:current-user-principal />
>debug:             </d:prop>
>debug:         </d:propfind>
>debug: 
>debug: Sending request...
>debug: 405
>debug: {'Allow': 'GET,HEAD,POST,OPTIONS', 'Content-Type': 'text/html;
>charset=iso-8859-1', 'Keep-Alive': 'timeout=5, max=98',
>'Content-Length': '338', 'Date':'
>Wed, 05 Jul 2017 14:59:50 GMT', 'Strict-Transport-Security':
>'max-age=15552000; includeSubDomains; preload', 'Connection':
>'Keep-Alive', 'Server': 'Apache/2.4.
>10 (Debian)'}
>debug: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">              
>                                                               [87/513]
>debug: <html><head>
>debug: <title>405 Method Not Allowed</title>
>debug: </head><body>
>debug: <h1>Method Not Allowed</h1>
>debug: <p>The requested method PROPFIND is not allowed for the URL
>/.well-known/carddav.</p>
>debug: <hr>
>debug: <address>Apache/2.4.10 (Debian) Server at
>vm.laressourcerieverte.com Port 443</address>
>debug: </body></html>
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/cli/discover.py", line 204,
>in _print_collections
>debug:     discovered = get_discovered()
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/cli/discover.py", line 133,
>in get_self
>debug:     return self._discovered
>debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/utils.py",
>line 170, in __get__
>debug:     obj.__dict__[self.__name__] = result = self.fget(obj)
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/cli/discover.py", line 142,
>in _discovered
>debug:     return handle_storage_init_error(self._cls, self._config)
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/cli/discover.py", line 138,
>in _discovered
>debug:     discovered = list(self._cls.discover(**self._config))
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/storage/dav.py", line 251,
>in discover
>debug:     for c in self.find_collections():
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/storage/dav.py", line 211,
>in find_collections
>debug:     return self._find_collections_impl(self.find_home())
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/storage/dav.py", line 187,
>in find_home
>debug:     url = self.find_principal()
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/storage/dav.py", line 158,
>in find_principal
>debug:     return self._find_principal_impl(self._well_known_uri)
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/storage/dav.py", line 172,
>in _find_principal_impl
>debug:     data=body)
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/storage/dav.py", line 374,
>in request
>debug:     return http.request(method, url, session=self._session,
>**more)
>debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/http.py", line
>183, in request
>debug:     r.raise_for_status()
>debug:   File "/usr/lib/python3/dist-packages/requests/models.py", line
>893, in raise_for_status
>debug:     raise HTTPError(http_error_msg, response=self)
>warning: Failed to discover collections for contacts_lrv_distant, use
>`-vdebug` to see the full traceback.
>debug: PROPFIND https://vm.laressourcerieverte.com/nextcloud/
>debug: {'User-Agent': 'vdirsyncer/0.16.0', 'Content-Type':
>'application/xml; charset=UTF-8', 'Depth': '1'}
>debug: 
>debug:     <d:propfind xmlns:d="DAV:">
>debug:         <d:prop>
>debug:             <d:resourcetype />
>debug:         </d:prop>
>debug:     </d:propfind>
>debug: 
>debug: Sending request...
>debug: 405
>debug: {'Status': '405 Method Not Allowed', 'X-XSS-Protection': '1;
>mode=block', 'Set-Cookie': 'ocyart057i15=mvk23hq54flm6f099i9aipphs6;
>path=/nextclou[40/513]
>nly,
>oc_sessionPassphrase=yMH%2FyXdTovOwgYyitYCcywooJfDR1af4a71rDIy8J%2BMCO7mO37vk596tv%2BVH%2BXD6SlY6c1QYLIULloF5krmBq70syUEFAXG7xsixgsBSfhpnQl2I3%2Fd5NSLDpF5
>lJ8Fl; path=/nextcloud; secure; httponly, nc_sameSiteCookielax=true;
>path=/nextcloud; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59
>GMT; SameSite=lax, nc_
>sameSiteCookiestrict=true; path=/nextcloud; httponly;secure;
>expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict,
>ocyart057i15=45brqs37knk152gccs7mohqri4; p
>ath=/nextcloud; secure; HttpOnly', 'Content-Length': '0',
>'Content-Type': 'text/html; charset=UTF-8', 'X-Download-Options':
>'noopen', 'X-Robots-Tag': 'none', '
>Content-Security-Policy': "default-src 'self'; script-src 'self'
>'unsafe-eval'
>'nonce-UzltcVVyY3RBOXJqYkhOTnkzdmM4ME14em0xS3lCOSs3dWVoQnU2djRPYz06TGJqOFpORWZSN
>TY2TmtNNXJReTBsR3dFL1NFTDQxVlJtNkh0VWFyQnJJVT0='; style-src 'self'
>'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self'
>data:; media-src *; con
>nect-src *", 'Server': 'Apache/2.4.10 (Debian)', 'Pragma': 'no-cache',
>'X-Content-Type-Options': 'nosniff', 'Cache-Control': 'no-store,
>no-cache, must-revalida
>te, post-check=0, pre-check=0', 'X-Permitted-Cross-Domain-Policies':
>'none', 'Date': 'Wed, 05 Jul 2017 14:59:51 GMT',
>'Strict-Transport-Security': 'max-age=155
>52000; includeSubDomains; preload', 'Connection': 'Keep-Alive',
>'Expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'X-Frame-Options':
>'SAMEORIGIN', 'Keep-Alive': 'tim
>eout=5, max=100'}
>
>debug: Given URL is not a homeset URL
>debug: PROPFIND https://vm.laressourcerieverte.com/nextcloud/
>debug: {'User-Agent': 'vdirsyncer/0.16.0', 'Content-Type':
>'application/xml; charset=UTF-8', 'Depth': '0'}
>debug: 
>debug:         <d:propfind xmlns:d="DAV:">
>debug:             <d:prop>
>debug:                 <d:current-user-principal />
>debug:             </d:prop>
>debug:         </d:propfind>
>debug: 
>debug: Sending request...
>debug: 405
>debug: {'Status': '405 Method Not Allowed', 'X-XSS-Protection': '1;
>mode=block', 'Set-Cookie': 'ocyart057i15=nd2u9khho40nquunn2d6e5lpm6;
>path=/nextcloud; secur
>e; HttpOnly', 'Content-Length': '0', 'Content-Type': 'text/html;
>charset=UTF-8', 'X-Download-Options': 'noopen', 'X-Robots-Tag': 'none',
>'Content-Security-Poli
>cy': "default-src 'self'; script-src 'self' 'unsafe-eval'
>'nonce-Q0graWVxMWN2enRNdjR2TEM1WWJVMGVuYnlmcWpaRHVlZzliOFFUVFJVZz06Ymg3MFRNdHUrMzhWNWJ1L2JlRnpOR2lTWE
>d1cnB0ckJEMGtYcGtDOUNTbz0='; style-src 'self' 'unsafe-inline';
>frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *;
>connect-src *", 'Server'
>: 'Apache/2.4.10 (Debian)', 'Pragma': 'no-cache',
>'X-Content-Type-Options': 'nosniff', 'Cache-Control': 'no-store,
>no-cache, must-revalidate, post-check=0, pre
>-check=0', 'X-Permitted-Cross-Domain-Policies': 'none', 'Date': 'Wed,
>05 Jul 2017 15:00:21 GMT', 'Strict-Transport-Security':
>'max-age=15552000; includeSubDoma
>ins; preload', 'Connection': 'Keep-Alive', 'Expires': 'Thu, 19 Nov 1981
>08:52:00 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'Keep-Alive':
>'timeout=5, max=99'}
>
>debug: Trying out well-known URI                                       
>                                                                [8/513]
>debug: PROPFIND https://vm.laressourcerieverte.com/.well-known/carddav
>debug: {'User-Agent': 'vdirsyncer/0.16.0', 'Content-Type':
>'application/xml; charset=UTF-8', 'Depth': '0'}
>debug: 
>debug:         <d:propfind xmlns:d="DAV:">
>debug:             <d:prop>
>debug:                 <d:current-user-principal />
>debug:             </d:prop>
>debug:         </d:propfind>
>debug: 
>debug: Sending request...
>debug: 405
>debug: {'Allow': 'GET,HEAD,POST,OPTIONS', 'Content-Type': 'text/html;
>charset=iso-8859-1', 'Keep-Alive': 'timeout=5, max=98',
>'Content-Length': '338', 'Date':'
>Wed, 05 Jul 2017 15:00:52 GMT', 'Strict-Transport-Security':
>'max-age=15552000; includeSubDomains; preload', 'Connection':
>'Keep-Alive', 'Server': 'Apache/2.4.
>10 (Debian)'}
>debug: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
>debug: <html><head>
>debug: <title>405 Method Not Allowed</title>
>debug: </head><body>
>debug: <h1>Method Not Allowed</h1>
>debug: <p>The requested method PROPFIND is not allowed for the URL
>/.well-known/carddav.</p>
>debug: <hr>
>debug: <address>Apache/2.4.10 (Debian) Server at
>vm.laressourcerieverte.com Port 443</address>
>debug: </body></html>
>error: Unknown error occured: 405 Client Error: Method Not Allowed for
>url: https://vm.laressourcerieverte.com/.well-known/carddav
>error: Use `-vdebug` to see the full traceback.
>debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/cli/utils.py",
>line 344, in _worker
>debug:     func(wq=self)
>debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/cli/tasks.py",
>line 82, in discover_collections
>debug:     rv = collections_for_pair(pair=pair, **kwargs)
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/cli/discover.py", line 81,
>in collections_for_pair
>debug:     _handle_collection_not_found=handle_collection_not_found
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/cli/discover.py", line 163,
>in expand_collections
>debug:     collections = get_b_discovered()
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/cli/discover.py", line 133,
>in get_self
>debug:     return self._discovered
>debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/utils.py",
>line 170, in __get__
>debug:     obj.__dict__[self.__name__] = result = self.fget(obj)
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/cli/discover.py", line 142,
>in _discovered
>debug:     return handle_storage_init_error(self._cls, self._config)
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/cli/discover.py", line 138,
>in _discovered
>debug:     discovered = list(self._cls.discover(**self._config))
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/storage/dav.py", line 251,
>in discover
>debug:     for c in self.find_collections():
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/storage/dav.py", line 211,
>in find_collections
>debug:     return self._find_collections_impl(self.find_home())
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/storage/dav.py", line 187,
>in find_home
>debug:     url = self.find_principal()
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/storage/dav.py", line 158,
>in find_principal
>debug:     return self._find_principal_impl(self._well_known_uri)
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/storage/dav.py", line 172,
>in _find_principal_impl
>debug:     data=body)
>debug:   File
>"/usr/lib/python3/dist-packages/vdirsyncer/storage/dav.py", line 374,
>in request
>debug:     return http.request(method, url, session=self._session,
>**more)
>debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/http.py", line
>183, in request
>debug:     r.raise_for_status()
>debug:   File "/usr/lib/python3/dist-packages/requests/models.py", line
>893, in raise_for_status
>debug:     raise HTTPError(http_error_msg, response=self)
>error: 1 out of 1 tasks failed.
>
>
>
>**configuration file:**
>
>17:08:21 whilelm@littlegr82:~$ cat ~/.vdirsyncer/config
>[general]
>status_path = "~/.vdirsyncer/status/"
>
>[pair appairage_lrv]
>a = "contacts_lrv_local"
>b = "contacts_lrv_distant"
>collections = ["from a", "from b"]
>conflict_resolution = "b wins"
>metadata = ["displayname"]
>
>[storage contacts_lrv_local]
>type = "filesystem"
>path = "~/.contacts/lrv/"
>fileext = ".vcf"
>
>[storage contacts_lrv_distant]
>type = "carddav"
>url = "https://vm.laressourcerieverte.com/nextcloud/"
>username = "christophe,moille"
>password.fetch = ["prompt", "Password for CalDAV lrv"]
>verify_fingerprint =
>"30:EA:98:60:96:21:1F:18:F6:AD:63:88:18:FA:71:79:0E:FA:23:31:AB:79:51:E9:D5:AE:42:B0:A4:AF:9A:25"
>
>
>**-- System Information:**
>Debian Release: 9.0
>  APT prefers stable
>  APT policy: (500, 'stable')
>Architecture: amd64 (x86_64)
>Foreign Architectures: i386
>
>Kernel: Linux 4.9.0-3-amd64 (SMP w/4 CPU cores)
>Locale: LANG=fr_FR.utf8, LC_CTYPE=fr_FR.utf8 (charmap=UTF-8),
>LANGUAGE=fr_FR.utf8 (charmap=UTF-8)
>Shell: /bin/sh linked to /bin/dash
>Init: systemd (via /run/systemd/system)
>
>Versions of packages vdirsyncer depends on:
>ii  python3                    3.5.3-1
>ii  python3-atomicwrites       1.1.5-1
>ii  python3-click              6.6-1
>ii  python3-click-log          0.1.8-1
>ii  python3-click-threading    0.4.3-1
>ii  python3-requests           2.12.4-1
>ii  python3-requests-toolbelt  0.7.0-1
>
>vdirsyncer recommends no packages.
>
>Versions of packages vdirsyncer suggests:
>pn  python3-requests-oauthlib  <none>
>
>-- no debconf information
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/650

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by WhilelM** [comment]
[vdirsyncer debug discover.txt](https://github.com/pimutils/vdirsyncer/files/1127056/vdirsyncer.debug.discover.txt)

**Comment by untitaker** [comment]
Please use /nextcloud/remote.php/dav/ instead of /nextcloud/.

Also I would recommend using a separate subdomain for nextcloud.

On 6 July 2017 09:35:45 GMT+02:00, WhilelM <notifications@github.com> wrote:
>[vdirsyncer debug
>discover.txt](https://github.com/pimutils/vdirsyncer/files/1127056/vdirsyncer.debug.discover.txt)
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/650#issuecomment-313319855

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
