### ISSUE TITLE
[feature request] Password / tokens in URLs

### ISSUE THREAD

**Issue by nim65s** [pimutils/vdirsyncer#655]
Hi,

Several ics providers (meetup, facebook, …) are providing calendar urls that includes a private token / password.
It would be great to be able to use the password.fetch mechanism to avoid having to write in clear those private informations.

eg:
```
[storage facebook_remote]
type = "http"
url = "https://www.facebook.com/ical/u.php?<PASSWORD>"
password.fetch = ["command", "pass", "ics/facebook"]
```
Where the password for `ics/facebook` might be something like `uid=664927601&key=492749276060`

This looks like a trivial change, so I can provide a pull request for this :)

**Comment by nim65s** [comment]
Well… This is useless. FTR, you just need to use `url.fetch`:

```
[storage facebook_remote]
type = "http"
url =  ["command", "pass", "ics/facebook"]
```

Where the password for `ics/facebook` is something like `https://www.facebook.com/ical/u.php?uid=664927601&key=492749276060`

Cheers :)

**Comment by untitaker** [comment]
Yes exactly :)

On 27 July 2017 14:41:07 GMT+02:00, Guilhem Saurel <notifications@github.com> wrote:
>Well… This is useless. FTR, you just need to use `url.fetch`:
>
>```
>[storage facebook_remote]
>type = "http"
>url =  ["command", "pass", "ics/facebook"]
>```
>
>Where the password for `ics/facebook` is something like
>`https://www.facebook.com/ical/u.php?uid=664927601&key=492749276060`
>
>Cheers :)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/655#issuecomment-318350306

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
