### ISSUE TITLE
Google calendar crashes with start/end date set

### ISSUE THREAD

**Issue by vestingz** [pimutils/vdirsyncer#657]
I am using vdirsyncer v0.16.0, Python 3.6.2 on Arch 4.12.3-1. I set up a pair for syncing between my local calendar and the calendars of my organization hosted by Google. Discovering the collections (vdirsyncer discover) works well, as did the sync, at least for the first time. Since then I have been trying to sync this pair without any success; vdirsyncer returns "Unknown error..." (see debugfile).

Here is my (sanitized) config:
```[general]
status_path = "~/.vdirsyncer/status/"

[storage calendar_remote]
type = "google_calendar"
read_only = "true"
token_file = "~/.vdirsyncer/token"
client_id = "<SOMETHING>.apps.googleusercontent.com"
client_secret = "<SOMETHING>"
start_date = "datetime.now() - timedelta(days=10)"
end_date = "datetime.now() + timedelta(days=100)"

[storage calendar_khal_loc]
type = "filesystem"
path = "~/.calendars/calendar_khal/"
fileext = ".ics"

[pair calendar_khal]
a = "calendar_khal_loc"
b = "calendar_remote"
collections = ["from a", "from b"]
partial_sync = "ignore"
conflict_resolution = "b wins"
metadata = ["displayname"]
```
and the error log: 
[out0.txt](https://github.com/pimutils/vdirsyncer/files/1194247/out0.txt)

Edit: I did some more testing and it seems that deleting everything in ~/.vdirsyncer/status/ helps.

**Comment by untitaker** [comment]
>Edit: I did some more testing and it seems that deleting everything in ~/.vdirsyncer/status/ helps.

Ok, since you deleted the data I can't help figure out what the issue was, but it appears that there's a bug in vdirsyncer... somewhere.

**Comment by vestingz** [comment]
No problem, I can upload those files somewhere, as the bug reproducibly appears after running vdirsyncer the first on an empty status directory. It then creates those files again and fails with seemingly the same error the next time I run it. Which files exactly would be helpful?

**Comment by untitaker** [comment]
The .items file would be useful (in addition to the debug logs)

**Comment by untitaker** [comment]
@vestingz I can't decrypt the email you sent me. It appears to be encrypted with the wrong public key.

**Comment by untitaker** [comment]
Hmm, the status file you sent me didn't help. I also don't understand how you get the error you're experiencing, regardless of the server's response it should be impossible to get into this state.

Could you try to remove your timerange parameters?

**Comment by vestingz** [comment]
Yes, removing the timeranger parameters helps indeed. thank you :)
This, however, bloats the calendar files as the calendar goes back to 2011..

**Comment by untitaker** [comment]
I don't think this is ready to close yet... needs further investigation.

**Comment by untitaker** [comment]
I can even reproduce this with my own calendar

**Comment by stettberger** [comment]
Thank you for fixing this bug. It also bit me.

**Comment by untitaker** [comment]
@vestingz please file a new issue since this appears to be a separate bug, and also include the full debug output since i can't work with this excerpt.
