### ISSUE TITLE
Investigate usage of packagecloud.io for Debian/Ubuntu repositories

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#663]
Debian has policies that prevent users from using the latest vdirsyncer version. We should make it possible for users to add a repository that contains the latest version while still using their *native* package manager for updates.

The two options for this are:
* PPAs
* http://packagecloud.io

An ideal solution would automatically generate apt packages from the PyPI releases.

@hobarrera investigated this sometime ago, however it's unclear what the conclusions/results were. We should try this out again and perhaps contact packagecloud's support about our usecase. We should also clearly document what we found out.

**Comment by untitaker** [comment]
By the way, I would consider it unproblematic to bundle all dependencies of vdirsyncer in the same package, as long as it doesn't conflict with the system-site-packages.

**Comment by untitaker** [comment]
```I don't see much wrong with the package -- one blocker was needing to package missing dependencies as well (eg: atomicwrites) as debs..
17:23 "blocker". I'd actually done it. :P
17:23 Can you see the packages if you log into packagecloud? https://packagecloud.io/pimutils/todoman
```

I can see the packages python-atomicwrites and python-pyxdg without logging in.

**Comment by hobarrera** [comment]
Looks like package generation was the actual issue:
https://github.com/pimutils/todoman/pull/84

packagecloud merely provides repositories, not packaging itself.

**Comment by geier** [comment]
I've heard good things about open build service [0], but a) never used
it and b) it looks like it's "just" the software and we would need to
host it ourselves. Perhaps there is a hosted version of it somewhere.


[0] http://openbuildservice.org/

Quoting Hugo Osvaldo Barrera (2017-08-24 17:34:55)

**Comment by hobarrera** [comment]
The issue I mentioned above has been reported:

https://github.com/jordansissel/fpm/issues/1106

However, there's an extra issue with `fpm`; ideally, both `khal` and `todoman` aren't pure-python, since we provide custom entry point to avoid setuptools' overhead.

@geier There's a public instance here: https://build.opensuse.org/

**Comment by geier** [comment]
there is one here: https://build.opensuse.org/

Quoting Christian Geier (2017-08-24 17:48:53)

**Comment by untitaker** [comment]
This also looks very interesting: https://github.com/spotify/dh-virtualenv

**Comment by hobarrera** [comment]
`dh-virtualenv` looks promising. I think the idea of having a virtualenv makes sense it that we don't have to deal with outdated dependencies (and I don't want to have to package the whole dependency tree for debian).

**Comment by untitaker** [comment]
FWIW I have had great success with dh-virtualenv. The initial setup is quite laborious and you have to write your own docker/docker-compose files to build packages for all distros, but once you have that releases are completely automatic (although resource intensive).

**Comment by untitaker** [comment]
Btw I now replaced dh-virtualenv with fpm. It turns out fpm has a virtualenv source.
