### ISSUE TITLE
vdirsync discover fails with radicale

### ISSUE THREAD

**Issue by esbjerg** [pimutils/vdirsyncer#665]
Client OS: FreeBSD 11.1p1
vdirsyncer: py27-vdirsyncer-0.12.1

Server OS: Debian 8.9
radicale: 0.9-1+deb8u1

vdirsyncer config:
[general]
python2 = true
status_path = "~/.vdirsyncer/status/"

[pair calendars]
a = "cal_local"
b = "cal_remote"
collections = ["from a", "from b"]

[storage cal_local]
type = "filesystem"
path = "~/.calendar/"
fileext = ".ics"

[storage cal_remote]
type = "caldav"
verify = false
verify_fingerprint = DB:E4:B9:EA:93:10:59:59:9C:F2:E5:23:1E:09:59:7A:43:3F:89:36

url = "https://cal.esbjerg.name/joker/calendar.ics/"
username = "joker"
password = "xxxxxxxxxx"

Actual error:
% vdirsyncer -vdebug discover calendars > vdir.out
warning: Python 2 support will be dropped. Please switch to at least Python 3.3 as soon as possible. See https://github.com/pimutils/vdirsyncer/issues/219 for more information.
error: The server returned something vdirsyncer doesn't understand. Error message: InvalidXMLResponse()
error: While this is most likely a serverside problem, the vdirsyncer devs are generally interested in such bugs. Please report it in the issue tracker at https://github.com/pimutils/vdirsyncer/issues
error: 1 out of 1 tasks failed.

Contents of vdir.out:
debug: Using 1 maximal workers.
Discovering collections for pair calendars
debug: PROPFIND https://cal.esbjerg.name/joker/calendar.ics/
debug: {'Depth': '0', 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
debug: 
debug:         <d:propfind xmlns:d="DAV:">
debug:             <d:prop>
debug:                 <d:current-user-principal />
debug:             </d:prop>
debug:         </d:propfind>
debug:         
debug: Sending request...
debug: 207
debug: {'Content-Length': '353', 'Connection': 'Keep-Alive', 'Keep-Alive': 'timeout=5, max=100', 'Server': 'Apache', 'DAV': '1, 2, 3, calendar-access, addressbook, extended-mkcol', 'Date': 'Sun, 27 Aug 2017 12:36:26 GMT', 'X-Frame-Options': 'sameorigin', 'Content-Type': 'text/xml'}
debug: <?xml version="1.0"?>
debug: <multistatus xmlns="DAV:">
debug:   <response>
debug:     <href>/joker/calendar.ics/</href>
debug:     <propstat>
debug:       <prop />
debug:       <status>HTTP/1.1 200 OK</status>
debug:     </propstat>
debug:     <propstat>
debug:       <prop>
debug:         <current-user-principal />
debug:       </prop>
debug:       <status>HTTP/1.1 404 Not Found</status>
debug:     </propstat>
debug:   </response>
debug: </multistatus>
debug: GET https://cal.esbjerg.name/.well-known/caldav/
debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
debug: None
debug: Sending request...
debug: 200
debug: {'Content-Length': '0', 'Keep-Alive': 'timeout=5, max=99', 'Server': 'Apache', 'Last-Modified': 'Sun, 27 Aug 2017 12:17:04 GMT', 'Connection': 'Keep-Alive', 'ETag': '"d41d8cd98f00b204e9800998ecf8427e"', 'Date': 'Sun, 27 Aug 2017 12:36:26 GMT', 'X-Frame-Options': 'sameorigin', 'Content-Type': 'text/calendar'}

debug: PROPFIND https://cal.esbjerg.name/.well-known/caldav/
debug: {'Depth': '0', 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
debug: 
debug:         <d:propfind xmlns:d="DAV:">
debug:             <d:prop>
debug:                 <d:current-user-principal />
debug:             </d:prop>
debug:         </d:propfind>
debug:         
debug: Sending request...
debug: 207
debug: {'Content-Length': '353', 'Connection': 'Keep-Alive', 'Keep-Alive': 'timeout=5, max=98', 'Server': 'Apache', 'DAV': '1, 2, 3, calendar-access, addressbook, extended-mkcol', 'Date': 'Sun, 27 Aug 2017 12:36:26 GMT', 'X-Frame-Options': 'sameorigin', 'Content-Type': 'text/xml'}
debug: <?xml version="1.0"?>
debug: <multistatus xmlns="DAV:">
debug:   <response>
debug:     <href>/.well-known/caldav/</href>
debug:     <propstat>
debug:       <prop />
debug:       <status>HTTP/1.1 200 OK</status>
debug:     </propstat>
debug:     <propstat>
debug:       <prop>
debug:         <current-user-principal />
debug:       </prop>
debug:       <status>HTTP/1.1 404 Not Found</status>
debug:     </propstat>
debug:   </response>
debug: </multistatus>

Apache log:
cal.esbjerg.name:443 151.217.3.4 - - [27/Aug/2017:14:17:41 +0200] "PROPFIND /joker/calendar.ics/ HTTP/1.1" 207 3192 "-" "vdirsyncer"
cal.esbjerg.name:443 151.217.3.4 - - [27/Aug/2017:14:17:41 +0200] "GET /.well-known/caldav/ HTTP/1.1" 200 321 "-" "vdirsyncer"
cal.esbjerg.name:443 151.217.3.4 - - [27/Aug/2017:14:17:41 +0200] "PROPFIND /.well-known/caldav/ HTTP/1.1" 207 677 "-" "vdirsyncer"

**Comment by untitaker** [comment]
This is a very old vdirsyncer version, please update to at least 0.16.0.
