### ISSUE TITLE
bad handshake: Error 'ssl3_get_server_certificate', 'certificate verify failed'

### ISSUE THREAD

**Issue by potuz** [pimutils/vdirsyncer#666]
Just updated from 0.14.0 to 0.16.2 on gentoo:

```
$ vdirsyncer --version
vdirsyncer, version 0.16.2
$ vdirsyncer -vdebug sync
debug: Using 1 maximal workers.
Syncing myusername_contacts/business
debug: PROPFIND https://radicale.myhost.net:8458/myusername/business/
debug: {'User-Agent': 'vdirsyncer/0.16.2', 'Depth': '1', 'Content-Type': 'application/xml; charset=UTF-8'}
debug: <?xml version="1.0" encoding="utf-8" ?>
debug:             <D:propfind xmlns:D="DAV:">
debug:                 <D:prop>
debug:                     <D:resourcetype/>
debug:                     <D:getcontenttype/>
debug:                     <D:getetag/>
debug:                 </D:prop>
debug:             </D:propfind>
debug:             
debug: Sending request...
error: Unknown error occured for myusername_contacts/business: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
error: Use `-vdebug` to see the full traceback.
debug:   File "/usr/lib64/python3.4/site-packages/vdirsyncer/cli/tasks.py", line 69, in sync_collection
debug:     partial_sync=pair.partial_sync
debug:   File "/usr/lib64/python3.4/site-packages/vdirsyncer/sync.py", line 561, in sync
debug:     b_nonempty = b_info.prepare_new_status()
debug:   File "/usr/lib64/python3.4/site-packages/vdirsyncer/sync.py", line 470, in prepare_new_status
debug:     for href, etag in self.storage.list():
debug:   File "/usr/lib64/python3.4/site-packages/vdirsyncer/storage/dav.py", line 628, in list
debug:     headers=headers)
debug:   File "/usr/lib64/python3.4/site-packages/vdirsyncer/storage/dav.py", line 374, in request
debug:     return http.request(method, url, session=self._session, **more)
debug:   File "/usr/lib64/python3.4/site-packages/vdirsyncer/http.py", line 164, in request
debug:     r = func(method, url, **kwargs)
debug:   File "/usr/lib64/python3.4/site-packages/requests/sessions.py", line 502, in request
debug:     resp = self.send(prep, **send_kwargs)
debug:   File "/usr/lib64/python3.4/site-packages/requests/sessions.py", line 612, in send
debug:     r = adapter.send(request, **kwargs)
debug:   File "/usr/lib64/python3.4/site-packages/requests/adapters.py", line 514, in send
debug:     raise SSLError(e, request=request)
 $ python --version
Python 3.4.6
$ uname -a
Linux myhost 3.10.17-gentoo #4 SMP Thu Nov 28 12:13:29 UTC 2013 x86_64 Intel(R) Core(TM) i7 CPU 870 @ 2.93GHz GenuineIntel GNU/Linux\
$ radicale --version
2.0.0
```

**Comment by untitaker** [comment]
More likely related to the python-requests version you're using. Try installing httpie if your distro has packages for that, and test it with your server.

On 30 August 2017 15:48:44 GMT+02:00, Potuz <notifications@github.com> wrote:
>Just updated from 0.14.0 to 0.16.2 on gentoo:
>
>```
>$ vdirsyncer --version
>vdirsyncer, version 0.16.2
>$ vdirsyncer -vdebug sync
>debug: Using 1 maximal workers.
>Syncing myusername_contacts/business
>debug: PROPFIND https://radicale.myhost.net:8458/myusername/business/
>debug: {'User-Agent': 'vdirsyncer/0.16.2', 'Depth': '1',
>'Content-Type': 'application/xml; charset=UTF-8'}
>debug: <?xml version="1.0" encoding="utf-8" ?>
>debug:             <D:propfind xmlns:D="DAV:">
>debug:                 <D:prop>
>debug:                     <D:resourcetype/>
>debug:                     <D:getcontenttype/>
>debug:                     <D:getetag/>
>debug:                 </D:prop>
>debug:             </D:propfind>
>debug:             
>debug: Sending request...
>error: Unknown error occured for myusername_contacts/business: ("bad
>handshake: Error([('SSL routines', 'ssl3_get_server_certificate',
>'certificate verify failed')],)",)
>error: Use `-vdebug` to see the full traceback.
>debug:   File
>"/usr/lib64/python3.4/site-packages/vdirsyncer/cli/tasks.py", line 69,
>in sync_collection
>debug:     partial_sync=pair.partial_sync
>debug:   File "/usr/lib64/python3.4/site-packages/vdirsyncer/sync.py",
>line 561, in sync
>debug:     b_nonempty = b_info.prepare_new_status()
>debug:   File "/usr/lib64/python3.4/site-packages/vdirsyncer/sync.py",
>line 470, in prepare_new_status
>debug:     for href, etag in self.storage.list():
>debug:   File
>"/usr/lib64/python3.4/site-packages/vdirsyncer/storage/dav.py", line
>628, in list
>debug:     headers=headers)
>debug:   File
>"/usr/lib64/python3.4/site-packages/vdirsyncer/storage/dav.py", line
>374, in request
>debug:     return http.request(method, url, session=self._session,
>**more)
>debug:   File "/usr/lib64/python3.4/site-packages/vdirsyncer/http.py",
>line 164, in request
>debug:     r = func(method, url, **kwargs)
>debug:   File
>"/usr/lib64/python3.4/site-packages/requests/sessions.py", line 502, in
>request
>debug:     resp = self.send(prep, **send_kwargs)
>debug:   File
>"/usr/lib64/python3.4/site-packages/requests/sessions.py", line 612, in
>send
>debug:     r = adapter.send(request, **kwargs)
>debug:   File
>"/usr/lib64/python3.4/site-packages/requests/adapters.py", line 514, in
>send
>debug:     raise SSLError(e, request=request)
> $ python --version
>Python 3.4.6
>$ uname -a
>Linux myhost 3.10.17-gentoo #4 SMP Thu Nov 28 12:13:29 UTC 2013 x86_64
>Intel(R) Core(TM) i7 CPU 870 @ 2.93GHz GenuineIntel GNU/Linux\
>$ radicale --version
>2.0.0
>```
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/666

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by potuz** [comment]
I'm not sure what to test but after installing httpie:

```
$ http https://radicale.myhost.net:8458

http: error: SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",) while doing GET request to URL:
https://radicale.myhost.net:8458/
```

**Comment by untitaker** [comment]
If you have a custom SSL certificate you can use verify and verify_fingerprint, see docs.

**Comment by untitaker** [comment]
Closing this since you asked me to. @potuz fwiw I think certificate pinning as in the linked docs is probably a valid workaround in your situation.

**Comment by potuz** [comment]
Thanks for the linked docs, unfortunately verify = false is not allowed, and verify_fingerprint does not suffice (it still gives same error). I'll try with a new certificate.

**Comment by untitaker** [comment]
@potuz You need to use both at the same time :)

**Comment by potuz** [comment]
Ohh thanks! that did it!
