### ISSUE TITLE
Usage of Rust inside of vdirsyncer

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#673]
This is a continuation of the discussion in #651.

* pkgsrc and OpenBSD will not be able to maintain packages for platforms other than i386 and amd64. I don't consider this a problem since I doubt that there are more than 2 users that use vdirsyncer on a BSD on a platform other than those two.
* Unbundling of rust-vobject might happen. Contrary to my previous answers to @mathstuf this might just work similarly to how normal rust libraries are unbundled. However, it would be particularly tricky to unbundle the `vdirsyncer-ext` rust library, which is a part of the vdirsyncer repo and doesn't have its own versioning. It is also not on crates.io.

  I personally don't recommend it, and won't support the "usecase" of unbundling dependencies.

I am thinking of releasing a minor "test" version of vdirsyncer with the new Rust stuff merged, with the reserved "right" to revert the changes if they don't work out. @pimutils/packaging thoughts?

**Comment by untitaker** [comment]
0.16.3 is released with the remaining bugfixes, 0.16.4 will contain Rust as only change.

**Comment by WhyNotHugo** [comment]
I'd vote for that new release to be `0.17.0`, since it's really backwards incompatible and has breaking changes (requires Rust).  
Actually, I think `0.17.0b1` would probably be best, to so packagers can work on this and provide feedback, but not necessarily push this to downstream users.

**Comment by untitaker** [comment]
On Tue, Oct 03, 2017 at 04:00:20PM +0000, Hugo Osvaldo Barrera wrote:
> I'd vote for that new release to be `0.17.0`, since it's really backwards incompatible and has breaking changes (requires Rust).  

Good idea.

> Actually, I think `0.17.0b1` would probably be best, to so packagers can work on this and provide feedback, but not necessarily push this to downstream users.

Nobody uses something in beta, and I doubt that I would recieve enough
feedback.

**Comment by untitaker** [comment]
Also I'll leave it in master for quite a while since I'm using the master branch directly, to try it out. But I definetly don't want to make beta releases.

**Comment by 0-wiz-0** [comment]
Update for pkgsrc - there are now rust packages for i386/x86_64/powerpc/ARM64/sparc64/some ARM32 on NetBSD. Just FYI.
