### ISSUE TITLE
vdirsyncer creates only unnamed calendars in owncloud 

### ISSUE THREAD

**Issue by makabar** [pimutils/vdirsyncer#677]
Setup: 
there is one folder with multiple ics files (timetables) course1.ics, course2.ics, course3.ics and so on.
i want to share this calendars with my students using owncloud. (want to migrate to nextcloud if this soloution works stable)
the config of vdirsyncer looks like this

```
[pair bachelor_calendar]
a = "bachelor_calendar_local"
b = "bachelor_calendar_remote"
collections = ["from a", "from b"]

conflict_resolution = "a wins"

[storage bachelor_calendar_local]
type = "singlefile"
path = "/var/www/vhosts/poleon.de/cloud/bachelorcals/BA%s.ics"


[storage ba_calendar_remote]
type = "caldav"
url = "https://cloud.serv.er/remote.php/caldav/"
username ="Bachelor"
password ="thepassword4bacheloraccount"

```
after starting "discover" vdryncer asks me for creating any single calendar based on ics file (is there an option to force this process to "yes" automatically??).
after this i´ve got those calenders on the owncloud-side, but all of theme are **unnamed**.
this is not really cool. is it possible to name the calendars based on the ics file-names or the X-WR-CALNAME  in the ics-file?

**Comment by untitaker** [comment]
>(is there an option to force this process to "yes" automatically??)

Well, you can always pipe `yes` into vdirsyncer if you really need it. Such as `yes | vdirsyncer discover`. But since you usually discover manually (I wouldn't recommend putting `discover` into a cronjob or similar), I don't think it matters.

>after this i´ve got those calenders on the owncloud-side, but all of theme are unnamed.

Two issues here:

* vdirsyncer should probably set a collection name explicitly
* ownCloud should probably set a collection name implicitly, like many other calendar servers do. In fact it used to do that at some point if I remember correctly.

>is it possible to name the calendars based on the ics file-names or the X-WR-CALNAME in the ics-file?

I wasn't aware of this semi-standard. Probably a good idea to implement this.

----

Regarding your immediate problem: Is it a good enough solution for you to manually name those calendars? How many calendars are there?

**Comment by untitaker** [comment]
Also as a side note, what speaks against putting those ICS files on a HTTP server? Why would your students want to use your ownCloud instance?

**Comment by makabar** [comment]
putting the ics-files to an http server is not a solution for me. owncloud is already in use. it must be possible to subscribe to caldav with their mobile devices.
btw... in fact it is a good idea (X-WR-CALNAME) ;-)

**Comment by untitaker** [comment]
ICS files can be subscribed to with their mobile devices. There are
applications for that, I'd say more than there are applications for CalDAV, for
the simple reason that ICS-over-HTTP is a much simpler protocol than CalDAV.
Most cloud services such as Google Calendar support subscribing to them too.
That's not the case with CalDAV.

I'd strongly recommend you to reconsider bringing CalDAV into the mix just for
read-only calendars. It complicates the system for no obvious reason.
ICS-over-HTTP (aka WebCAL) is the de-facto standard for read-only calendars.

**Comment by makabar** [comment]
@untitaker  i sent a direct message via twitter

**Comment by untitaker** [comment]
I'll close this, the followup is https://github.com/pimutils/vdirsyncer/issues/682. That would allow you to use `vdirsyncer metasync` to copy over the displaynames of all calendars.
