### ISSUE TITLE
[feature request] fix timestamps of .ics files created

### ISSUE THREAD

**Issue by pille** [pimutils/vdirsyncer#679]
it would be nice to let vdirsyncer automatically set the date of an .ics file to the LAST-MODIFIED date of the event. that way you could easily see which events updated recently. in case this field is missing, DTSTAMP may be used.

i understand that i could implement a workaround by using hooks.

**Comment by untitaker** [comment]
I really think that you shouldn't do this, not even in a hook. mtime refers to
the modification date of the ICS file, and it's relied upon by vdirsyncer to
detect when an item has changed. Mtime automatically changes when the file
does, and therefore is more reliable than any ICS property where it's up to the
application to implement this. Syncing those two will result in vdirsyncer not
correctly updating items in some cases.

**Comment by pille** [comment]
given your explanation, i share your concerns.
