### ISSUE TITLE
rusty part of the build fails

### ISSUE THREAD

**Issue by jelmer** [pimutils/vdirsyncer#680]
vdirsyncer recently seems to be failing in travis for xandikos builds (https://travis-ci.org/jelmer/xandikos/jobs/289740198)

   make[2]: Entering directory `/home/travis/build/jelmer/xandikos/compat/vdirsyncer'
    [ "$READTHEDOCS" != "True" ] || make install-rust
    cd ./rust && PATH="$HOME/.cargo/bin/:$PATH" cargo build --release
        Updating registry `https://github.com/rust-lang/crates.io-index`
     Downloading ring v0.12.1
     Downloading vobject v0.3.0
     Downloading libc v0.2.32
     Downloading untrusted v0.5.1
     Downloading rayon v0.8.2
     Downloading gcc v0.3.54
     Downloading rayon-core v1.2.1
     Downloading futures v0.1.16
     Downloading rand v0.3.17
     Downloading lazy_static v0.2.9
     Downloading coco v0.1.1
     Downloading num_cpus v1.7.0
     Downloading either v1.3.0
     Downloading scopeguard v0.3.3
     Downloading cbindgen v0.1.26
     Downloading syn v0.11.11
     Downloading serde_json v0.9.10
     Downloading log v0.3.8
     Downloading clap v2.26.2
     Downloading serde_derive v0.9.15
     Downloading toml v0.3.2
     Downloading tempdir v0.3.5
     Downloading serde v0.9.15
     Downloading quote v0.3.15
     Downloading unicode-xid v0.0.4
     Downloading synom v0.11.3
     Downloading num-traits v0.1.40
     Downloading dtoa v0.4.2
     Downloading itoa v0.3.4
     Downloading strsim v0.6.0
     Downloading bitflags v0.9.1
     Downloading vec_map v0.8.0
     Downloading ansi_term v0.9.0
     Downloading term_size v0.3.0
     Downloading unicode-width v0.1.4
     Downloading atty v0.2.3
     Downloading textwrap v0.8.0
     Downloading serde_codegen_internals v0.14.2
       Compiling serde v0.9.15
       Compiling unicode-xid v0.0.4
       Compiling ansi_term v0.9.0
       Compiling either v1.3.0
       Compiling bitflags v0.9.1
       Compiling synom v0.11.3
       Compiling strsim v0.6.0
       Compiling quote v0.3.15
       Compiling rayon-core v1.2.1
       Compiling vec_map v0.8.0
       Compiling gcc v0.3.54
       Compiling libc v0.2.32
       Compiling vobject v0.3.0
       Compiling term_size v0.3.0
       Compiling atty v0.2.3
       Compiling rand v0.3.17
       Compiling log v0.3.8
       Compiling num-traits v0.1.40
       Compiling lazy_static v0.2.9
       Compiling itoa v0.3.4
       Compiling tempdir v0.3.5
       Compiling untrusted v0.5.1
       Compiling unicode-width v0.1.4
       Compiling dtoa v0.4.2
       Compiling syn v0.11.11
       Compiling serde_json v0.9.10
       Compiling toml v0.3.2
       Compiling futures v0.1.16
       Compiling scopeguard v0.3.3
       Compiling coco v0.1.1
       Compiling num_cpus v1.7.0
       Compiling rayon v0.8.2
       Compiling serde_codegen_internals v0.14.2
       Compiling ring v0.12.1
       Compiling serde_derive v0.9.15
    error: `pub(restricted)` syntax is experimental (see issue #32409)
      --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.12.1/src/agreement.rs:93:9
       |
    93 |     pub(crate) i: ec::AgreementAlgorithmImpl,
       |         ^^^^^
    
    error: aborting due to previous error
    
    error: Could not compile `ring`.
    Build failed, waiting for other jobs to finish...
    error: build failed
    make[2]: *** [rust-ext] Error 101

**Comment by jelmer** [comment]
This seems to be specific to the trusty build environment; I can't reproduce it on Debian.

**Comment by untitaker** [comment]
It seems to be caused by an outdated version of rust.

On 19 October 2017 04:37:11 GMT+02:00, "Jelmer Vernooĳ" <notifications@github.com> wrote:
>This seems to be specific to the trusty build environment; I can't
>reproduce it on Debian.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/680#issuecomment-337783023

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jelmer** [comment]
How do you manage to get the new version of rust on trusty in travis?

**Comment by untitaker** [comment]
There is rustup, you can use it with "make install-rust". I will send a PR today.

On 19 October 2017 07:25:40 GMT+02:00, "Jelmer Vernooĳ" <notifications@github.com> wrote:
>How do you manage to get the new version of rust on trusty in travis?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/680#issuecomment-337803093

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
