### ISSUE TITLE
Syncing with iCloud and start_date/end_date does not work

### ISSUE THREAD

**Issue by deg0nz** [pimutils/vdirsyncer#681]
I wasn't able to find this issue, nor an information about it in the wiki. So this is the problem:

When I use the `start_date` and `end_date` parameters for syncing with iCloud, I get the following error:
`critical: Error during reading config /home/pi/.config/vdirsyncer/config: Section "storage iCloud": Section "storage iCloud", option "start_date": Expecting value: line 1 column 1 (char 0)`
It is the same error when I use the `-vdebug` option.

Syncing without these parameters works well though.

Here's my config:

``` ini
[general]
# A folder where vdirsyncer can store some metadata about each pair.
status_path = "~/.vdirsyncer/status/"

# Synchronize all collections that can be found.
# You need to run `vdirsyncer discover` if new calendars/addressbooks are added
# on the server.

# CALDAV
[pair Mirror]
a = "Local"
b = "iCloud"
collections = ["MYID"]
conflict_resolution = "b wins"

# Calendars also have a color property
metadata = ["displayname", "color"]

[storage Local]
type = "singlefile"
path = "/home/USER/PATH/TO/FILE/%s.ics"

[storage iCloud]
type = "caldav"
url = "https://caldav.icloud.com/"
username = "<MYICLOUDEMAIL>"
password = "<MYSUPERPASSWORD>"
read_only = true
item_types = ["VEVENT"]
start_date = datetime.now() - timedelta(days=10)
end_date = datetime.now() + timedelta(days=30)
```

Additional information:

* vdirsyncer version: 0.16.3
* Server: https://caldav.icloud.com
* Python version: Python 3.4.2
* Operating system: Raspbian 8, `uname -a` output: Linux <HOSTNAME> 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

**Comment by untitaker** [comment]
You are missing double-quotes (") around your values for start_date and
end_date.

**Comment by deg0nz** [comment]
Alright! This works. Thank you for the quick answer!

Unfortunately, the quotes are missing in the documentation at [Storage->Caldav](http://vdirsyncer.pimutils.org/en/stable/config.html#storage-caldav).

**Comment by untitaker** [comment]
thanks, I fixed it in master.
