### ISSUE TITLE
vdirsyncer creates ics files with LF instead of CRLF endings.

### ISSUE THREAD

**Issue by Panke** [pimutils/vdirsyncer#683]
* vdirsyncer, version 0.16.3
* Using Nextcloud
* Python 3.6.2
* ArchLinux
* Your config file

If I create an event in my nextcloud calendar and export it via the web interface ("Export"-Button) the resulting ics-file has CRLF line endings as required by RFC5545. If I now sync that calendar with vdirsyncer  the newly created ics-file has LF as line endings. I am reading the ics files with an hexeditor, so I doubt any conversions happend accidently on my side.

Config of local calendar:
[storage taskcal_local] 
type = "filesystem"
path = "~/.taskcal/data"
fileext = ".ics"

**Comment by untitaker** [comment]
What exactly do you sync with vdirsyncer? Do you sync the exported file with
vdirsyncer (using singlefile storage), or nextcloud (dav storages)?

**Comment by Panke** [comment]
[pair local_nextcloud]
a = "nextcloud"
b = "local"
collections = null

[storage nextcloud]
type = "caldav"
url = "url/to/calendar/"
username = "*****"
password = "*****"

[storage local] 
type = "filesystem"
path = "~/.localpath/data"
fileext = ".ics"

I sync via DAV.

**Comment by untitaker** [comment]
I suspect this is done by nextcloud. Vdirsyncer dumps the raw string response. We should correct it though.

On 31 October 2017 16:11:22 GMT+01:00, Panke <notifications@github.com> wrote:
>[pair local_nextcloud]
>a = "nextcloud"
>b = "local"
>collections = null
>
>[storage nextcloud]
>type = "caldav"
>url = "url/to/calendar/"
>username = "*****"
>password = "*****"
>
>[storage local] 
>type = "filesystem"
>path = "~/.localpath/data"
>fileext = ".ics"
>
>I sync via DAV.
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/683#issuecomment-340793649

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
@Panke is this issue making vdirsyncer unusuable for you?

**Comment by NorfairKing** [comment]
The same thing happens when syncing `VCARD`s.
