### ISSUE TITLE
Caldav: 503 Server Error: Service Unavailable

### ISSUE THREAD

**Issue by strk** [pimutils/vdirsyncer#688]
vdirsyncer, version 0.16.3

Server is davmail 4.8.0.3

Davdroid works fine, while vdirsyncer complains about "Service Unavailable".

The Davmail logs show, for "vdirsyncer sync" call:

> 2017-11-09 21:32:26,726 ERROR [CaldavConnection-24662] davmail.exchange.ExchangeSession  - ErrorNoDestinationCASDueToVersionMismatch The Client Access Server version does not match the accessed resource's Mailbox Server version.  Use AutoDiscover with the address of the resource being accessed to determine the correct URL to use to access the specified resource.

Full -vdebug output of vdirsyncer sync (anonymized) is here:
http://strk.kbt.io/tmp/vdirsyncer-log.txt

Anonymized and trimmed down log from Davdroid is here:
http://strk.kbt.io/tmp/davdroid-31834-20171107-105929.txt

**Comment by untitaker** [comment]
Your links are broken, please use something reliable.

**Comment by strk** [comment]
Sorry, permissions fixed

**Comment by untitaker** [comment]
No, please use gists if you don't mind. I don't want the availability of issue data to depend on more hosts than necessary

**Comment by strk** [comment]
vdirsyncer log: https://gist.github.com/anonymous/078ba82a29983a395cedf475138cdea8
davdroid log: https://gist.github.com/12716c6b22b94edc7611081cf0e6bd43

**Comment by untitaker** [comment]
I'll take a look shortly, sorry for the harsh tone earlier. I hope you understand my motivation for keeping all data in one place.

**Comment by untitaker** [comment]
Ok, there's one bug in vdirsyncer I just saw and fixed in master, could you try installing vdirsyncer from master using a virtualenv and pip?

**Comment by untitaker** [comment]
@strk any updates on this?

**Comment by strk** [comment]
Nope sorry, the problem was somehow fixed (on server side, I guess) so cannot prove any fix

**Comment by untitaker** [comment]
ok cool
