### ISSUE TITLE
error: Unknown error occured: .... : Failed to establish a new connection: [Errno 65] No route to host',))

### ISSUE THREAD

**Issue by arooni** [pimutils/vdirsyncer#689]
Before you submit bug reports: https://vdirsyncer.pimutils.org/en/stable/contributing.html

Things to include in your bugreport:

I got to the google accept authorization page and entered the code into vdirsyncer.  Than I ran into a game over problem :(.  Any ideas how to proceed?  Apologies I couldn't get mark down working perfectly for the config file part

* Your vdirsyncer version : 0.16.3
* If applicable, which server software (and which version) you're using
* Your Python version: Python 3.6.3
* Your operating system: mac os x ; high sierra ; python is installed via homebrew; vdirsyncer is installed via pip3
* Your config file: [i removed token file and client_secret]

# An example configuration for vdirsyncer.

`
[general]
# A folder where vdirsyncer can store some metadata about each pair.
status_path = "~/.vdirsyncer/status/"

# CARDDAV
# [pair contacts]
# a = "contacts_local"
# b = "contacts_remote"
# collections = ["family", "friends"]
# conflict_resolution = "a wins"

# [storage contacts_local]
# type = "filesystem"
# path = "~/vdirsyncer/contacts/"
# fileext = ".vcf"

# [storage contacts_remote]
# type = "carddav"
# url = "https://example.org/baikal/card.php/addressbooks/YOURUSERNAME/"
# auth = "digest"
# verify = "/etc/ssl/local/example.org.pem"
# username = "YOURUSERNAME"
# password = "YOURPASSWORD"

# CALDAV
[pair calendar]
a = "calendar_local"
b = "calendar_remote"
collections = ["calendar", "holidays", "birthdays"]
conflict_resolution = "b wins"

[storage calendar_local]
type = "filesystem"
path = "~/.vdirsyncer/calendars/"
fileext = ".ics"

[storage calendar_remote]
type = "google_calendar"
token_file = "~/.vdirsyncer/tokens"
#start_date = null
#end_date = null
#
`

* Use `vdirsyncer -vdebug` for debug output. The output is sensitive, but
  please attach at least the last few lines before the error (if applicable),
  censored as necessary. This is almost always the most useful information.

`
[I]  ✘  ~/.vdirsyncer  vdirsyncer -vdebug discover
debug: Using 1 maximal workers.
Discovering collections for pair calendar
calendar_local:
  - "calendar"
debug: PROPFIND https://apidata.googleusercontent.com/caldav/v2/
debug: {'User-Agent': 'blah-blahblah.apps.googleusercontent.com', 'Content-Type': 'application/xml; charset=UTF-8', 'Depth': '1'}
debug:
debug:     <d:propfind xmlns:d="DAV:">
debug:         <d:prop>
debug:             <d:resourcetype />
debug:         </d:prop>
debug:     </d:propfind>
debug:
debug: Sending request...
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/cli/discover.py", line 204, in _print_collections
debug:     discovered = get_discovered()
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/cli/discover.py", line 133, in get_self
debug:     return self._discovered
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/utils.py", line 170, in __get__
debug:     obj.__dict__[self.__name__] = result = self.fget(obj)
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/cli/discover.py", line 142, in _discovered
debug:     return handle_storage_init_error(self._cls, self._config)
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/cli/discover.py", line 138, in _discovered
debug:     discovered = list(self._cls.discover(**self._config))
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/storage/dav.py", line 267, in discover
debug:     for c in self.find_collections():
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/storage/dav.py", line 220, in find_collections
debug:     rv = list(self._find_collections_impl(''))
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/storage/dav.py", line 250, in _find_collections_impl
debug:     data=self._collection_xml)
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/storage/dav.py", line 390, in request
debug:     return http.request(method, url, session=self._session, **more)
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/http.py", line 164, in request
debug:     r = func(method, url, **kwargs)
debug:   File "/usr/local/lib/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 360, in request
debug:     headers=headers, data=data, **kwargs)
debug:   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
debug:     resp = self.send(prep, **send_kwargs)
debug:   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
debug:     r = adapter.send(request, **kwargs)
debug:   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
debug:     raise ConnectionError(e, request=request)
warning: Failed to discover collections for calendar_remote, use `-vdebug` to see the full traceback.
debug: PROPFIND https://apidata.googleusercontent.com/caldav/v2/
debug: {'User-Agent': '339147690910-utvfvuvf83bg8pp52kv8kd8eqopmmmk8.apps.googleusercontent.com', 'Content-Type': 'application/xml; charset=UTF-8', 'Depth': '1'}
debug:
debug:     <d:propfind xmlns:d="DAV:">
debug:         <d:prop>
debug:             <d:resourcetype />
debug:         </d:prop>
debug:     </d:propfind>
debug:
debug: Sending request...
error: Unknown error occured: HTTPSConnectionPool(host='apidata.googleusercontent.com', port=443): Max retries exceeded with url: /caldav/v2/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10a2b36a0>: Failed to establish a new connection: [Errno 65] No route to host',))
error: Use `-vdebug` to see the full traceback.
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/cli/utils.py", line 341, in _worker
debug:     func(wq=self)
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/cli/tasks.py", line 82, in discover_collections
debug:     rv = collections_for_pair(pair=pair, **kwargs)
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/cli/discover.py", line 81, in collections_for_pair
debug:     _handle_collection_not_found=handle_collection_not_found
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/cli/discover.py", line 183, in expand_collections
debug:     _handle_collection_not_found
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/cli/discover.py", line 197, in _collection_from_discovered
debug:     return get_discovered()[collection]
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/cli/discover.py", line 133, in get_self
debug:     return self._discovered
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/utils.py", line 170, in __get__
debug:     obj.__dict__[self.__name__] = result = self.fget(obj)
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/cli/discover.py", line 142, in _discovered
debug:     return handle_storage_init_error(self._cls, self._config)
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/cli/discover.py", line 138, in _discovered
debug:     discovered = list(self._cls.discover(**self._config))
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/storage/dav.py", line 267, in discover
debug:     for c in self.find_collections():
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/storage/dav.py", line 220, in find_collections
debug:     rv = list(self._find_collections_impl(''))
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/storage/dav.py", line 250, in _find_collections_impl
debug:     data=self._collection_xml)
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/storage/dav.py", line 390, in request
debug:     return http.request(method, url, session=self._session, **more)
debug:   File "/usr/local/lib/python3.6/site-packages/vdirsyncer/http.py", line 164, in request
debug:     r = func(method, url, **kwargs)
debug:   File "/usr/local/lib/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 360, in request
debug:     headers=headers, data=data, **kwargs)
debug:   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
debug:     resp = self.send(prep, **send_kwargs)
debug:   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
debug:     r = adapter.send(request, **kwargs)
debug:   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
debug:     raise ConnectionError(e, request=request)
error: 1 out of 1 tasks failed.
[I]  ✘  ~/.vdirsyncer `

**Comment by untitaker** [comment]
We discussed this already in IRC and I don't think this is a bug in vdirsyncer.
