### ISSUE TITLE
port number in URL is not respected

### ISSUE THREAD

**Issue by mjg** [pimutils/vdirsyncer#690]
vdirsyncer 0.16.0 on Fedora 27

I sync successfully with one CardDAV server on a standard port.

A second server with a different name/IP is at the non-standard port 444, I have `url ="https://servername.tld:444/owncloudpath"` in the config. But discover errors out with `error: Unknown error occured: HTTPSConnectionPool(host='servername.tld', port=443)`, and the fingerprint also tells me that vdirsyncer indeed connects at port 443, not 444. Turning off verification completely does not help either. I gutess the port in the URL is simply stripped.

**Comment by untitaker** [comment]
That's weird. Could you do this:

```sh
python3
>>> import requests
>>> requests.get("https://servername.tld:444/owncloudpath", verify=False)
```

I strongly suspect that ownCloud does a wrong redirect here.

**Comment by mjg** [comment]
The above gives `<Response [401]>` on port 444 and `<Response [404]>` on port 443 as it should (owncloud is on 444 only).

In fact, it turned out that the 443 in the HTTPSConnectionPool error above was a terrible red herring: vdirsyncer talks to owncloud as it should, and by checking the nginx logs I realized that the password credentials were wrong... Sorry for the noise!

Syncing happiily now, and closing.
