### ISSUE TITLE
Is there a good way to revert a bunch of changes?

### ISSUE THREAD

**Issue by amandabee** [pimutils/vdirsyncer#693]
I managed to completely foul my local contacts by being stupid. I'd like to revert to the stored contacts on Nextcloud, but I can't figure out how to do that. I can't be the only person who does things like this so it might be a useful thing to put explicitly in the documentation.

```
[general]
status_path = "~/.vdirsyncer/status/"

[pair cards]
a = "local_cards"
b = "nextcloud_cards"
collections = ["from a", "from b"]
conflict_resolution: ["command","meld"]

[storage local_cards]
type = "filesystem"
path = "~/.nextcloud/addresses/"
fileext = ".vcf"

[storage nextcloud_cards]
type = "carddav"
url = "https://redacted"
username = "redacted"
password = "redacted"
```

**Comment by untitaker** [comment]
Delete your local contacts (i.e. all vcf files), then delete the status folder ~/.vdirsyncer/status/, then sync.

On 22 December 2017 02:18:03 GMT+01:00, Amanda Hickman <notifications@github.com> wrote:
>I managed to completely foul my local contacts by being stupid. I'd
>like to revert to the stored contacts on Nextcloud, but I can't figure
>out how to do that. Tips? 
>
>
>```
>[general]
>status_path = "~/.vdirsyncer/status/"
>
>[pair cards]
>a = "local_cards"
>b = "nextcloud_cards"
>collections = ["from a", "from b"]
>conflict_resolution: ["command","meld"]
>
>[storage local_cards]
>type = "filesystem"
>path = "~/.nextcloud/addresses/"
>fileext = ".vcf"
>
>[storage nextcloud_cards]
>type = "carddav"
>url = "https://redacted"
>username = "redacted"
>password = "redacted"
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/693

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by amandabee** [comment]
Thank you!
