### ISSUE TITLE
Posteo generates invalid VCARDS (escaped newlines, trailing "NULL")

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#703]
```
debug: </card:address-data><d:getetag>"1fa232abae442c42237d74847bd6a91b"</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/addressbooks/iom/default/224D4AA8-8F76-113D-077D-F2F2BC74A4AE.vcf</d:href><d:propstat><d:prop><card:address-data>BEGIN:VCARD&#13;
debug: VERSION:3.0&#13;
debug: N:;Bxxxxxx;;;&#13;
debug: FN:Bxxxxxx&#13;
debug: TEL;TYPE=CELL:015-155-05xxxx&#13;
debug: TEL;TYPE=work:906-514-xxxx&#13;
debug: ADR;TYPE=home:;;Rauhxxxxxxx 8 C \n87xxx   Soxxxxxxn, Obexxxxgäu;;;;&#13;
debug: UID:224D4AA8-8F76-113D-077D-F2F2BC74A4AE&#13;
debug: END:VCARD&#13;NULL
```

* DAVDroid deals with this fine, we should work with it too
* Report to Posteo
* notify original user (email addr in source of this issue)

**Comment by untitaker** [comment]
@rfc2822 is it intentional in DavDroid that trailing data like the NULL is ignored? Am I missing something in the RFC?

**Comment by rfc2822** [comment]
DAVdroid just passes the contents of< card:address-data> into the https://github.com/mangstadt/ez-vcard parser, and it has never complained until now…

**Comment by untitaker** [comment]
It turns out that Posteo generated invalid vcards. If the contact is edited in the web UI, the contact is fixed.
