### ISSUE TITLE
vdirsyncer discover. Icloud 3 Calenders Only one UUID found

### ISSUE THREAD

**Issue by paddyhughes** [pimutils/vdirsyncer#711]
Hi  

Sorry I am a total Noob so not sure I can easily give you any answers but i will try my best.

* Raspberry pi 3
* Jessie OS
* python3

Vdirsyncer is installed by following the  instructions for MagicMirror2 setup: https://forum.magicmirror.builders/topic/5327/sync-private-icloud-calendar-with-magicmirror?page=1

**My Issue is** i am Running MagicMirror2 Displaying my iCloud Calendar on screen
I have 3 calendars 
* Calendar-------This is my primary one on my phone
* home------------This is the one i want displayed on the mirror
* work

When i run 
`vdirsyncer discover`

I Just get back one UUID for the Calendar  when the instructions on the site say i should get back UUID for each Calendar.

```pi@raspberrypi:~/MagicMirror $ vdirsyncer discover
Discovering collections for pair iCloud_to_MagicMirror
Mirror:
iCloud:
  - "tasks" ("Reminders")
  - "AE********-E**4-4D**-A**4-*****************" ("Calendar")
  - "home" ("Home Calendar")
  - "work" ("Work")
warning: No collection "HERE-GOES-THE-UUID-OF-THE-CALENDAR-YOU-WANT-TO-SYNC" found for storage Mirror.
Should vdirsyncer attempt to create it? [y/N]:
```

Config File

```# vdirsyncer configuration for MagicMirror.
#
# Move it to ~/.vdirsyncer/config or ~/.config/vdirsyncer/config and edit it.
# Run `vdirsyncer --help` for CLI usage.
#
# Optional parameters are commented out.
# This file doesn't document all available parameters, see
# http://vdirsyncer.pimutils.org/ for the rest of them.

[general]
# A folder where vdirsyncer can store some metadata about each pair.
status_path = "~/.vdirsyncer/status/"

# CALDAV Sync
[pair iCloud_to_MagicMirror]
a = "Mirror"
b = "iCloud"
collections = ["home","AE*******-E***-4****-A***-***********"]


# Calendars also have a color property
metadata = ["displayname", "color"]

[storage Mirror]
# We need a single .ics file for use with the mirror (Attention! This is really slow on big amounts of events.)
type = "singlefile"
# We'll put the calendar file to a readable location for the calendar module
path = "/home/pi/MagicMirror/modules/calendars/%s.ics"

[storage iCloud]
type = "caldav"
url = "https://caldav.icloud.com/"
# Authentication credentials
username = "my user************************"
password = "my key**********************"
# We only want to sync in the direction TO the mirror, so we make iCloud readonly
read_only = true
```

Thanks for any help given 👍

**Comment by untitaker** [comment]
Hey @paddyhughes, please fix the formatting of your post, as of now it's quite unreadable. In particular please use single backticks for inline code, and triple-backticks around your pasted config.

**Comment by paddyhughes** [comment]
Hi @untitaker  Sorry about the format hope this is better

**Comment by untitaker** [comment]
> ```
iCloud:
  - "tasks" ("Reminders")
  - "AE********-E**4-4D**-A**4-*****************" ("Calendar")
  - "home" ("Home Calendar")
  - "work" ("Work")
```

Those are all the UUIDs you need? E.g. `"tasks"` is a valid ID as well, even though it is a word. As is `"home"`, and `"work"`.

**Comment by paddyhughes** [comment]
Yes sorry tasks is also a calendar.
i was expecting to see something like this as in the URL link in my first post has an example it shows each Calendar getting its own UUID.
```Discovering collections for pair iCloud_to_MagicMirror
Mirror:
iCloud:
  - "25CB285C-E163-4E0E-B420-C3FB469B7C00" ("Reminders")
  - "9221FEE8-E8B4-4D07-9402-8638529919EC" ("Calendar")
  - "953A5477-E405-4ED6-A5C3-473444EACC95" ("Home Calendar")
- "9FEE8477-E456-2ED3-A4C6-345477EACC98" ("Work")
warning: No collection "9221FEE8-E8B4-4D07-9402-8638529919EC" found for storage Mirror.
Should vdirsyncer attempt to create it? [y/N]:
```


But when i run the code i only get UUID for Calendar

```
Discovering collections for pair iCloud_to_MagicMirror
Mirror:
iCloud:
  - "tasks" ("Reminders")
  - "AE********-E**4-4D**-A**4-*****************" ("Calendar")
  - "home" ("Home Calendar")
  - "work" ("Work")
warning: No collection "HERE-GOES-THE-UUID-OF-THE-CALENDAR-YOU-WANT-TO-SYNC" found for storage Mirror.
Should vdirsyncer attempt to create it? [y/N]:
```

**Comment by untitaker** [comment]
Again, "tasks" etc are UUIDs for your purpose.

On 7 February 2018 22:10:38 GMT+01:00, paddyhughes <notifications@github.com> wrote:
>Yes sorry tasks is also a calendar.
>i was expecting to see something like this as in the URL link in my
>first post has an example it shows each Calendar getting its own UUID.
>```Discovering collections for pair iCloud_to_MagicMirror
>Mirror:
>iCloud:
>  - "25CB285C-E163-4E0E-B420-C3FB469B7C00" ("Reminders")
>  - "9221FEE8-E8B4-4D07-9402-8638529919EC" ("Calendar")
>  - "953A5477-E405-4ED6-A5C3-473444EACC95" ("Home Calendar")
>- "9FEE8477-E456-2ED3-A4C6-345477EACC98" ("Work")
>warning: No collection "9221FEE8-E8B4-4D07-9402-8638529919EC" found for
>storage Mirror.
>Should vdirsyncer attempt to create it? [y/N]:
>```
>
>
>But when i run the code i only get UUID for Calendar
>
>```
>Discovering collections for pair iCloud_to_MagicMirror
>Mirror:
>iCloud:
>  - "tasks" ("Reminders")
>  - "AE********-E**4-4D**-A**4-*****************" ("Calendar")
>  - "home" ("Home Calendar")
>  - "work" ("Work")
>warning: No collection
>"HERE-GOES-THE-UUID-OF-THE-CALENDAR-YOU-WANT-TO-SYNC" found for storage
>Mirror.
>Should vdirsyncer attempt to create it? [y/N]:
>```
>
>
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/711#issuecomment-363911774

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by paddyhughes** [comment]
Sorry 
So in my Config File in Collections i don't need UUID like this AE216FF8-D89D4-5E06-2509-9283221815FG"
"home" for my (Home Calendar")
```
# CALDAV Sync
[pair iCloud_to_MagicMirror]
a = "Mirror"
b = "iCloud"
collections = ["home"]
```

**Comment by untitaker** [comment]
Yes exactly, ["from b"] also works to do this automatically

On 7 February 2018 22:37:00 GMT+01:00, paddyhughes <notifications@github.com> wrote:
>Sorry 
>So in my Config File in Collections i don't need UUID like this
>AE216FF8-D89D4-5E06-2509-9283221815FG"
>"home" for my (Home Calendar")
>```
># CALDAV Sync
>[pair iCloud_to_MagicMirror]
>a = "Mirror"
>b = "iCloud"
>collections = ["home"]
>```
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/711#issuecomment-363918980

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by paddyhughes** [comment]
Thanks @untitaker I will give it a shot now

**Comment by paddyhughes** [comment]
Thant worked thanks.
If i may just ask one more question about the ```start_date```  ```end_date```
If i want to get the the 4 days that have gone can that be done?

```
start_date = "datetime.now() - timedelta(days=1)"
end_date = "datetime.now() + timedelta(days=30)"```

**Comment by paddyhughes** [comment]
Thanks for all the help
