### ISSUE TITLE
"Force" Sync with discover and "auto"-yes

### ISSUE THREAD

**Issue by der-Daniel** [pimutils/vdirsyncer#723]
Hi,

let me further expand on my title:  
I want to backup calendars and contacts from my Nextcloud. In this use case there is only a one directional conceptional channel from the Nextcloud server to my backup system.
So far, I have a crownjob doing `vdirsyncer sync`, `git add -A` and a `git commit`.

There is a problem when new calendars are added to my Nextcloud calendar. Before I can sync the calendar I have to do a `vdirsyncer discover` in combination with entering `y` for creating the corresponding directory for the new calendar.

Is there a way/flag for just pulling, creating and overwriting everything that comes from the server?

~ For Frodo!

**Comment by untitaker** [comment]
Something like:

    yes | vdirsyncer discover
    vdirsyncer sync

should work

**Comment by der-Daniel** [comment]
Awesome I never knew about `yes`.
