### ISSUE TITLE
Failure to upload carddav to Hover.com server

### ISSUE THREAD

**Issue by charlesmcevoy** [pimutils/vdirsyncer#725]
Before you submit bug reports: https://vdirsyncer.pimutils.org/en/stable/contributing.html

Things to include in your bugreport:

* Your vdirsyncer version
* If applicable, which server software (and which version) you're using
* Your Python version
* Your operating system
* Your config file
* Use `vdirsyncer -vdebug` for debug output. The output is sensitive, but
  please attach at least the last few lines before the error (if applicable),
  censored as necessary. This is almost always the most useful information.

**Comment by untitaker** [comment]
@charlesmcevoy could you fill out the details (such as debug output from vdirsyncer)? Thanks

**Comment by charlesmcevoy** [comment]
On Wednesday, 14 March 2018 23:42:05 GMT Markus Unterwaditzer wrote:
> @charlesmcevoy could you fill out the details (such as debug output from
> vdirsyncer)? Thanks
Just about to - computer crashed...

**Comment by charlesmcevoy** [comment]
Sync local Linux box with CARDDAV collection on Hover.com (initially generated with DAVdroid) works perfectly Hover -> local, but does not upload changes local -> Hover
DAVdroid is able to update the collection.
Python 3.6.4
vdirsyncer, version 0.16.4
Linux 4.15.7-1-default #1 SMP x86_64 GNU/Linux
openSUSE Tumbleweed VERSION="20180311"
[vconf.txt](https://github.com/pimutils/vdirsyncer/files/1813521/vconf.txt)
[vbug.txt](https://github.com/pimutils/vdirsyncer/files/1813522/vbug.txt)

**Comment by untitaker** [comment]
What exactly did you change in the file to trigger a re-upload? Could you run the following on the shell:

```
touch foo
stat foo
sleep 3
touch foo
stat foo
```

where `foo` is a file in the same filesystem you use for your contacts.

**Comment by charlesmcevoy** [comment]
The trigger I was using is that there are a couple of files present in local that are absent from the server.
I've run the script against feba49fa-41e4-4992-b3b9-9c3b999578bd.vcf and got two different timestamps from stat.
This is the next sync.
[vbug2.txt](https://github.com/pimutils/vdirsyncer/files/1817301/vbug2.txt)

**Comment by untitaker** [comment]
Sorry for slow response.

If you wipe the status directory, does the problem fix itself?

I'm at a loss as to what's happening here.

**Comment by untitaker** [comment]
Perhaps... what are the filenames of the local files that are missing from the server? Could you upload your `*.items` file from the status directory?

**Comment by charlesmcevoy** [comment]
Genius! Problem solved, and I'm sorry to have wasted your time. Checking the filenames in the contacts folder I see that KDE/Kontact is not putting a .vcf suffix on the contacts it creates, so that is why vsyncdir isn't synchronising them. Correct the filename and everything works as expected.
Again, sorry to have wasted your time, I'll let Kontact know and write a quick hacky fix to solve the problem for now.

**Comment by untitaker** [comment]
You can likely fix this by setting the fileext in the config file to an empty string (cant remember if this could work, but worth a try)

On 19 March 2018 00:46:00 GMT+01:00, charlesmcevoy <notifications@github.com> wrote:
>Genius! Problem solved, and I'm sorry to have wasted your time.
>Checking the filenames in the contacts folder I see that KDE/Kontact is
>not putting a .vcf suffix on the contacts it creates, so that is why
>vsyncdir isn't synchronising them. Correct the filename and everything
>works as expected.
>Again, sorry to have wasted your time, I'll let Kontact know and write
>a quick hacky fix to solve the problem for now.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/725#issuecomment-374067658

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
Actually you might not want to do what I said earlier if you have any other file in the directory that really isnt a vcf (such as something created by metasync)

**Comment by untitaker** [comment]
Also thx for the money. :)

**Comment by charlesmcevoy** [comment]
Thanks for super-useful software and a level of support that puts most paid support to shame.
