### ISSUE TITLE
google contacts sync seemingly slow

### ISSUE THREAD

**Issue by eleith** [pimutils/vdirsyncer#727]
i am seeing google_contacts sync (against a read only carddav) take 2+ hours for 400+ contacts, but when syncing against a standard caldav server, it takes a few seconds.

is this to be expected because of google's custom caldav implementation? this may not be an issue if this is expected, so feel free to close.

**Comment by untitaker** [comment]
[Yeah, it's not surprising at least.](https://evertpot.com/google-carddav-issues/) I can't do anything against it.

**Comment by eleith** [comment]
perfect explanatory link, thank you. 

this project is great and i'm enjoying using it for the rest of my more important caldav compliant services =]
