### ISSUE TITLE
Syncing VTODO doesn´t work (error 403 - Invalid component type VTODO)

### ISSUE THREAD

**Issue by controlcde** [pimutils/vdirsyncer#737]
I use vdirsyncer 0.16.4 on OS X to sync from my old Apple Calendarserver to the new one. Both are running under Debian. This is a one-way sync but it doesn't work to sync the VTODO.

> Copying (uploading) item F4D000D5-6235-4DF1-BA2F-B2B6AC11631C to Kalender_neu/calendar
> debug: Normalized URL from 'F4D000D5-6235-4DF1-BA2F-B2B6AC11631C.ics' to '/calendars/__uids__/30000000-0000-0000-0000-000000000001/calendar/F4D000D5-6235-4DF1-BA2F-B2B6AC11631C.ics'
> debug: PUT https://SERVERNAME:443/calendars/__uids__/30000000-0000-0000-0000-000000000001/calendar/F4D000D5-6235-4DF1-BA2F-B2B6AC11631C.ics
> debug: {'User-Agent': 'vdirsyncer/0.16.4', 'Content-Type': 'text/calendar', 'If-None-Match': '*'}
> debug: BEGIN:VCALENDAR
> debug: VERSION:2.0
> debug: CALSCALE:GREGORIAN
> debug: PRODID:-//Apple Inc.//iOS 7.0.4//EN
> debug: BEGIN:VTODO
> debug: UID:F4D000D5-6235-4DF1-BA2F-B2B6AC11631C
> debug: COMPLETED:20150212T185651Z
> debug: CREATED:20150211T103706Z
> debug: DTSTAMP:20150212T193756Z
> debug: LAST-MODIFIED:20150212T185653Z
> debug: PERCENT-COMPLETE:100
> debug: SEQUENCE:0
> debug: STATUS:COMPLETED
> debug: SUMMARY:Make it
> debug: X-APPLE-SORT-ORDER:413807826
> debug: END:VTODO
> debug: END:VCALENDAR
> debug: Sending request...
> debug: 403
> debug: {'Server': 'nginx/1.13.12', 'Date': 'Wed, 23 May 2018 12:35:33 GMT', 'Content-Type': 'text/xml', 'Content-Length': '299', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=31536000'}
> debug: <?xml version='1.0' encoding='UTF-8'?>
> debug: <error xmlns='DAV:'>
> debug:   <supported-calendar-component xmlns='urn:ietf:params:xml:ns:caldav'/>
> debug:   <error-description xmlns='http://twistedmatrix.com/xml_namespace/dav/'>Invalid component type VTODO for calendar: &lt;Calendar: 2&gt;</error-description>
> debug: </error>
> error: Unknown error occured for Kalender/calendar: 403 Client Error: Forbidden for url: https://SERVERNAME:443/calendars/__uids__/30000000-0000-0000-0000-000000000001/calendar/F4D000D5-6235-4DF1-BA2F-B2B6AC11631C.ics

**Comment by controlcde** [comment]
> Are you able to sync VTODO with any other client? To me it seems your server is
configured to store/accept VTODOs.

Well, the old server is running and different osx and iphone user are using the reminder app and sync it with the old server.

**Comment by untitaker** [comment]
Well, what about the new server?

**Comment by controlcde** [comment]
> Well, what about the new server?

I could also add VTODO to the new server and I could manually move VTODOs from the old account to the new one.

**Comment by untitaker** [comment]
@controlcde is this issue still relevant?

**Comment by untitaker** [comment]
closing due to lack of response and because this is unlikely to be a vdirsyncer bug
