### ISSUE TITLE
sync of calendar cause an error on source server with sqlite (<class 'sqlite3.OperationalError'>: too many SQL variables)

### ISSUE THREAD

**Issue by controlcde** [pimutils/vdirsyncer#740]
I want to sync from an old calendarserver with sqlite backend to a new calendarserver with postgres backend. If I want to sync one calendar I got the following error:

> debug: Sending request...
> debug: 500
> debug: {'Date': 'Sun, 27 May 2018 18:48:54 GMT', 'Content-Length': '201', 'Content-Type': 'text/html', 'Server': 'CalendarServer/3.2(r) Twisted/12.0.0 TwistedWeb/9.0.0'}
> debug: <html><head><title>Internal Server Error</title></head><body><h1>Internal Server Error</h1>An error occurred rendering the requested page. More information is available in the server log.</body></html>
> error: Unknown error occured for Kalender/calendar: 500 Server Error: Internal Server Error for url: http://calendar.controlc.de:8008/calendars/__uids__/81e8da56-c0ad-5589-aa2c-8e4410dbfe3f/calendar/
> error: Use `-vdebug` to see the full traceback.
> debug:   File "/usr/local/Cellar/vdirsyncer/0.16.4_2/libexec/lib/python3.6/site-packages/vdirsyncer/cli/tasks.py", line 69, in sync_collection
> debug:     partial_sync=pair.partial_sync
> debug:   File "/usr/local/Cellar/vdirsyncer/0.16.4_2/libexec/lib/python3.6/site-packages/vdirsyncer/sync/__init__.py", line 135, in sync
> debug:     a_nonempty = a_info.prepare_new_status()
> debug:   File "/usr/local/Cellar/vdirsyncer/0.16.4_2/libexec/lib/python3.6/site-packages/vdirsyncer/sync/__init__.py", line 59, in prepare_new_status
> debug:     if prefetch else ()):
> debug:   File "/usr/local/Cellar/vdirsyncer/0.16.4_2/libexec/lib/python3.6/site-packages/vdirsyncer/storage/dav.py", line 485, in get_multi
> debug:     headers=self.session.get_default_headers()
> debug:   File "/usr/local/Cellar/vdirsyncer/0.16.4_2/libexec/lib/python3.6/site-packages/vdirsyncer/storage/dav.py", line 390, in request
> debug:     return http.request(method, url, session=self._session, **more)
> debug:   File "/usr/local/Cellar/vdirsyncer/0.16.4_2/libexec/lib/python3.6/site-packages/vdirsyncer/http.py", line 183, in request
> debug:     r.raise_for_status()
> debug:   File "/usr/local/Cellar/vdirsyncer/0.16.4_2/libexec/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
> debug:     raise HTTPError(http_error_msg, response=self)

and on the old server I could see the following in the log

> 2018-05-27 20:35:55+0200 [-] [caldav-4]  [PooledMemCacheProtocol,client] [twext.web2.server#error] [Failure instance: Traceback: <class 'sqlite3.OperationalError'>: too many SQL va
> riables
> 2018-05-27 20:35:55+0200 [-] [caldav-4]         /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1187:unwindGenerator
> 2018-05-27 20:35:55+0200 [-] [caldav-4]         /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1045:_inlineCallbacks
> 2018-05-27 20:35:55+0200 [-] [caldav-4]         /usr/lib/python2.7/dist-packages/twistedcaldav/method/report_multiget_common.py:314:multiget_common
> 2018-05-27 20:35:55+0200 [-] [caldav-4]         /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1187:unwindGenerator
> 2018-05-27 20:35:55+0200 [-] [caldav-4]         --- <exception caught here> ---
> 2018-05-27 20:35:55+0200 [-] [caldav-4]         /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1045:_inlineCallbacks
> 2018-05-27 20:35:55+0200 [-] [caldav-4]         /usr/lib/python2.7/dist-packages/twistedcaldav/method/report_multiget_common.py:193:doResponse
> 2018-05-27 20:35:55+0200 [-] [caldav-4]         /usr/lib/python2.7/dist-packages/txdav/caldav/datastore/index_file.py:238:resourcesExist
> 2018-05-27 20:35:55+0200 [-] [caldav-4]         /usr/lib/python2.7/dist-packages/twistedcaldav/sql.py:314:_db_values_for_sql
> 2018-05-27 20:35:55+0200 [-] [caldav-4]         /usr/lib/python2.7/dist-packages/twistedcaldav/sql.py:341:_db_execute
> 2018-05-27 20:35:55+0200 [-] [caldav-4]         ]

Maybe the `calendar-multiget` wants too many objects? Could I limit them?

**Comment by untitaker** [comment]
There is currently no way to fix this using master, unless you patch vdirsyncer yourself (the relevant code is in DavStorage.get_multi). This will be fixed during the rust rewrite, but I have had no time to push that one forward.

On 27 May 2018 20:57:22 GMT+02:00, controlcde <notifications@github.com> wrote:
>I want to sync from an old calendarserver with sqlite backend to a new
>calendarserver with postgres backend. If I want to sync one calendar I
>got the following error:
>
>> debug: Sending request...
>> debug: 500
>> debug: {'Date': 'Sun, 27 May 2018 18:48:54 GMT', 'Content-Length':
>'201', 'Content-Type': 'text/html', 'Server': 'CalendarServer/3.2(r)
>Twisted/12.0.0 TwistedWeb/9.0.0'}
>> debug: <html><head><title>Internal Server
>Error</title></head><body><h1>Internal Server Error</h1>An error
>occurred rendering the requested page. More information is available in
>the server log.</body></html>
>> error: Unknown error occured for Kalender/calendar: 500 Server Error:
>Internal Server Error for url:
>http://calendar.controlc.de:8008/calendars/__uids__/81e8da56-c0ad-5589-aa2c-8e4410dbfe3f/calendar/
>> error: Use `-vdebug` to see the full traceback.
>> debug:   File
>"/usr/local/Cellar/vdirsyncer/0.16.4_2/libexec/lib/python3.6/site-packages/vdirsyncer/cli/tasks.py",
>line 69, in sync_collection
>> debug:     partial_sync=pair.partial_sync
>> debug:   File
>"/usr/local/Cellar/vdirsyncer/0.16.4_2/libexec/lib/python3.6/site-packages/vdirsyncer/sync/__init__.py",
>line 135, in sync
>> debug:     a_nonempty = a_info.prepare_new_status()
>> debug:   File
>"/usr/local/Cellar/vdirsyncer/0.16.4_2/libexec/lib/python3.6/site-packages/vdirsyncer/sync/__init__.py",
>line 59, in prepare_new_status
>> debug:     if prefetch else ()):
>> debug:   File
>"/usr/local/Cellar/vdirsyncer/0.16.4_2/libexec/lib/python3.6/site-packages/vdirsyncer/storage/dav.py",
>line 485, in get_multi
>> debug:     headers=self.session.get_default_headers()
>> debug:   File
>"/usr/local/Cellar/vdirsyncer/0.16.4_2/libexec/lib/python3.6/site-packages/vdirsyncer/storage/dav.py",
>line 390, in request
>> debug:     return http.request(method, url, session=self._session,
>**more)
>> debug:   File
>"/usr/local/Cellar/vdirsyncer/0.16.4_2/libexec/lib/python3.6/site-packages/vdirsyncer/http.py",
>line 183, in request
>> debug:     r.raise_for_status()
>> debug:   File
>"/usr/local/Cellar/vdirsyncer/0.16.4_2/libexec/lib/python3.6/site-packages/requests/models.py",
>line 935, in raise_for_status
>> debug:     raise HTTPError(http_error_msg, response=self)
>
>and on the old server I could see the following in the log
>
>> 2018-05-27 20:35:55+0200 [-] [caldav-4] 
>[PooledMemCacheProtocol,client] [twext.web2.server#error] [Failure
>instance: Traceback: <class 'sqlite3.OperationalError'>: too many SQL
>va
>> riables
>> 2018-05-27 20:35:55+0200 [-] [caldav-4]        
>/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1187:unwindGenerator
>> 2018-05-27 20:35:55+0200 [-] [caldav-4]        
>/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1045:_inlineCallbacks
>> 2018-05-27 20:35:55+0200 [-] [caldav-4]        
>/usr/lib/python2.7/dist-packages/twistedcaldav/method/report_multiget_common.py:314:multiget_common
>> 2018-05-27 20:35:55+0200 [-] [caldav-4]        
>/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1187:unwindGenerator
>> 2018-05-27 20:35:55+0200 [-] [caldav-4]         --- <exception caught
>here> ---
>> 2018-05-27 20:35:55+0200 [-] [caldav-4]        
>/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1045:_inlineCallbacks
>> 2018-05-27 20:35:55+0200 [-] [caldav-4]        
>/usr/lib/python2.7/dist-packages/twistedcaldav/method/report_multiget_common.py:193:doResponse
>> 2018-05-27 20:35:55+0200 [-] [caldav-4]        
>/usr/lib/python2.7/dist-packages/txdav/caldav/datastore/index_file.py:238:resourcesExist
>> 2018-05-27 20:35:55+0200 [-] [caldav-4]        
>/usr/lib/python2.7/dist-packages/twistedcaldav/sql.py:314:_db_values_for_sql
>> 2018-05-27 20:35:55+0200 [-] [caldav-4]        
>/usr/lib/python2.7/dist-packages/twistedcaldav/sql.py:341:_db_execute
>> 2018-05-27 20:35:55+0200 [-] [caldav-4]         ]
>
>Maybe the `calendar-multiget` wants too many objects? Could I limit
>them?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/740

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by controlcde** [comment]
@untitaker That´s ok. My solution is to create different conf files with start and end dates each with only one year at all. Separating VTODO und VEVENT helps a lot too.

**Comment by untitaker** [comment]
I think this is now fixed in master, but it might be generally slower

**Comment by controlcde** [comment]
Thanks - how could I test it? How could I make my own vdirsyncer bin?

**Comment by untitaker** [comment]
Check https://vdirsyncer.pimutils.org/en/latest/installation.html#manual-installation

The master version is quite experimental at the moment, Google does not work at all, and it has more dependencies because I am in the middle of porting this to Rust. It *does* work well once you managed to install it though.

**Comment by untitaker** [comment]
@controlcde if you're on debian, check out https://packagecloud.io/pimutils/vdirsyncer

**Comment by controlcde** [comment]
@untitaker I´ve installed a debian stretch machine with vdirsyncer-latest but it doesn´t work :(.

```
error: Unknown error occurred for Kalender/calendar: http://OLDSERVER:8008/calendars/__uids__/2d61425c-438c-5da9-b0c1-08ce24b0df1f/calendar/: Client Error: 401 Unauthorized
error: Use `-vdebug` to see the full traceback.
debug:   File "/opt/venvs/vdirsyncer-latest/lib/python3.5/site-packages/vdirsyncer/cli/tasks.py", line 69, in sync_collection
debug:     partial_sync=pair.partial_sync
debug:   File "/opt/venvs/vdirsyncer-latest/lib/python3.5/site-packages/vdirsyncer/sync/__init__.py", line 142, in sync
debug:     a_nonempty = a_info.prepare_new_status()
debug:   File "/opt/venvs/vdirsyncer-latest/lib/python3.5/site-packages/vdirsyncer/sync/__init__.py", line 46, in prepare_new_status
debug:     for href, etag in self.storage.list():
debug:   File "/opt/venvs/vdirsyncer-latest/lib/python3.5/site-packages/vdirsyncer/storage/_rust.py", line 18, in list
debug:     native.check_error(e)
debug:   File "/opt/venvs/vdirsyncer-latest/lib/python3.5/site-packages/vdirsyncer/native.py", line 29, in check_error
debug:     errors.check_exception(e[0])
debug:   File "/opt/venvs/vdirsyncer-latest/lib/python3.5/site-packages/shippai/__init__.py", line 112, in check_exception
debug:     _raise_with_more_frames(exc, frames)
debug:   File "/opt/venvs/vdirsyncer-latest/lib/python3.5/site-packages/shippai/__init__.py", line 208, in _raise_with_more_frames
debug:     raise exc
error: 1 out of 2 tasks failed.
```
and on the old calendarserver:

```
2018-06-19 12:27:18+0200 [-] [caldav-6]  [-] [twistedcaldav.extensions#error] Client authentication scheme basic is not provided by server ['digest']
```

in my conf file I define

```
[general]
# A folder where vdirsyncer can store some metadata about each pair.
status_path = "~/vds/status/"

# CALDAV
[pair Kalender]
a = "Kalender_alt"
b = "Kalender_neu"
collections = ["calendar"]
conflict_resolution = "a wins"
metadata = ["color", "displayname"]
partial_sync = "ignore"

[storage Kalender_alt]
type = "caldav"
url = "http://OLDSERVER:8008/principals/__uids__/UID/"
auth = "digest"
username = "USER"
password = "PASSWORD"
read_only = true
item_types = ["VEVENT"]

[storage Kalender_neu]
type = "caldav"
url = "https://NEWSERVER:443/principals/users/USER/"
auth = "digest"
verify_fingerprint = "FP"
username = "USER"
password = "PASSWORD"
```

**Comment by controlcde** [comment]
After changing authentification scheme on the source server to basic everything works fine. Thank you!

**Comment by untitaker** [comment]
cont. in #749
