### ISSUE TITLE
Password Fetch external commands

### ISSUE THREAD

**Issue by trmendes** [pimutils/vdirsyncer#742]
Before you submit bug reports: https://vdirsyncer.pimutils.org/en/stable/contributing.html

Things to include in your bugreport:

vdirsyncer, version 0.16.4
Python 3.6.5
archlinux

I use [posteo](https://www.posteo.de) as my caldav/carddav server and [pass](https://www.passwordstore.org/) as my password manager.

First I wasn't able to connect to posteo using vdirsyncer. My issue with posteo and vdirsync is this one #603

Same config file.

But when I change my password fetch command from

password.fetch =  ["command", "pass", "email/posteo"]

to

password.fetch = ["prompt", "Posteo password: "]

it started to work :o

**Comment by WhyNotHugo** [comment]
Do you have gpg-agent running and your key unlocked (for `pass` to work)?

Also, can you provide the full output of running vdirsyncer? Thanks!

**Comment by trmendes** [comment]
@WhyNotHugo I have it. pass works fine. I use it with mutt any many other apss here in the same way.

But I might be doing something wrong when it comes to vdirsyncer. Is that he right way to configure it?

password.fetch = ["command", "pass", "email/posteo"]

I think this might be the problem I have 'cause I get a "Username or password does not match"

```
debug: Using 1 maximal workers.
debug: Fetching value for password.fetch with command strategy.
Discovering collections for pair posteo_contacts
posteo_contacts_local:
debug: PROPFIND https://posteo.de:8443/
debug: {'User-Agent': 'vdirsyncer/0.16.4', 'Content-Type': 'application/xml; charset=UTF-8', 'Depth': '1'}
debug: 
debug:     <d:propfind xmlns:d="DAV:">
debug:         <d:prop>
debug:             <d:resourcetype />
debug:         </d:prop>
debug:     </d:propfind>
debug:     
debug: Sending request...
debug: 401
debug: {'Date': 'Sun, 03 Jun 2018 22:23:31 GMT', 'Server': 'Apache', 'X-Powered-By': 'PHP/5.4.35-0+deb7u2', 'WWW-Authenticate': 'Basic realm="SabreDAV"', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/xml; charset=utf-8'}
debug: <?xml version="1.0" encoding="utf-8"?>
debug: <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
debug:   <s:exception>Sabre_DAV_Exception_NotAuthenticated</s:exception>
debug:   <s:message>Username or password does not match</s:message>
debug: </d:error>
debug: Given URL is not a homeset URL
debug: PROPFIND https://posteo.de:8443/
debug: {'User-Agent': 'vdirsyncer/0.16.4', 'Content-Type': 'application/xml; charset=UTF-8', 'Depth': '0'}
debug: 
debug:         <d:propfind xmlns:d="DAV:">
debug:             <d:prop>
debug:                 <d:current-user-principal />
debug:             </d:prop>
debug:         </d:propfind>
debug:         
```

**Comment by untitaker** [comment]
What does `pass email/posteo` even output? Does it maybe include more than one line?

**Comment by trmendes** [comment]
The password only

**Comment by trmendes** [comment]
Sorry. I was wrong. It does contain more then 1 line there. Changed to one line only and it is working with vdirsyncer now!

**Comment by WhyNotHugo** [comment]
I guess that it's safe to close this?

**Comment by Iambecomeroot** [comment]
The way I solved this without deleting all the metadata from my password store files was to add an extension `first-line.bash` in `~/.password-store/.extensions` which contains simply:
```bash
pass show "$@" | head -n 1
```
