### ISSUE TITLE
Include documentation for Baikal

### ISSUE THREAD

**Issue by Lindenk** [pimutils/vdirsyncer#743]
Currently the online documentation says only this about Baikal:

```
Baikal
Vdirsyncer is continuously tested against the latest version of Baikal.

Baikal up to 0.2.7 also uses an old version of SabreDAV, with the same issue as ownCloud, see issue #160. This issue is fixed in later versions.
```

A test configuration would be appreciated since a simple 'dav.domain.com' doesn't seem to be working for the url.

**Comment by untitaker** [comment]
Baikal is effectively unmaintained nowadays and I therefore can't continue to support it.

IIRC `http://dav.domain.com` works provided you have well-known URIs set up as per its docs.
