### ISSUE TITLE
[google-calendar] Failed to download event (because of escaping?)

### ISSUE THREAD

**Issue by Mange** [pimutils/vdirsyncer#745]
```
› vdirsyncer --version
vdirsyncer, version 0.16.4
› python --version
Python 3.6.5
```

Running on Arch Linux, syncing to Google Calendar via CalDAV.

---

I get sync errors for a single entry in the calendar. It looks like it has to do with the automatic URL escaping of `href`s.

## Error

I've tried to extract relevant lines out of the `-vdebug` output; it contains thousands and thousands of lines.

```
debug:  <D:response xmlns:carddav="urn:ietf:params:xml:ns:carddav" xmlns:cm="http://cal.me.com/_namespace/" xmlns:md="urn:mobileme:davservi
ces">
debug:   <D:href>/caldav/v2/magnus.bergmark%40gmail.com/events/2012-08-07+08%3A42_320847479%40napp01.ics</D:href>
debug:   <D:propstat>
debug:    <D:status>HTTP/1.1 200 OK</D:status>
debug:    <D:prop>
debug:     <D:getcontenttype>text/calendar; component=vevent</D:getcontenttype>
debug:     <D:getetag>"63480004950"</D:getetag>
debug:     <D:resourcetype/>
debug:    </D:prop>
debug:   </D:propstat>
debug:  </D:response>

debug: Normalized URL from '/caldav/v2/magnus.bergmark%40gmail.com/events/2012-08-07+08%3A42_320847479%40napp01.ics' to '/caldav/v2/magnus.bergmark@gmail.com/events/2012-08-07%2B08:42_320847479@napp01.ics'

debug: Already normalized: '/caldav/v2/magnus.bergmark@gmail.com/events/2012-08-07%2B08:42_320847479@napp01.ics'

debug: <D:href>/caldav/v2/magnus.bergmark@gmail.com/events/2012-08-07%2B08:42_320847479@napp01.ics</D:href>
debug:  <D:response xmlns:carddav="urn:ietf:params:xml:ns:carddav" xmlns:cm="http://cal.me.com/_namespace/" xmlns:md="urn:mobileme:davservi
ces">
debug:   <D:href>/caldav/v2/magnus.bergmark@gmail.com/events/2012-08-07%2B08:42_320847479@napp01.ics</D:href>
debug:   <D:status>HTTP/1.1 404 Not Found</D:status>
debug:  </D:response>
debug: </D:multistatus>
```

## Debugging

I suspected that the problem had to do with the normalization of the `href` so I tried to patch the code at runtime to check.

```python
def _normalize_href(base, href):
    '''Normalize the href to be a path only relative to hostname and
    schema.'''
    orig_href = href
    if not href:
        raise ValueError(href)

    x = urlparse.urljoin(base, href)
    x = urlparse.urlsplit(x).path

    # Encoding issues:
    # - https://github.com/owncloud/contacts/issues/581
    # - https://github.com/Kozea/Radicale/issues/298
    old_x = None
    while old_x is None or x != old_x:
        if _contains_quoted_reserved_chars(x):
            break
        old_x = x
        x = urlparse.unquote(x)

    x = urlparse.quote(x, '/@%:')


    # PATCH HERE
    if orig_href == '/caldav/v2/magnus.bergmark%40gmail.com/events/2012-08-07+08%3A42_320847479%40napp01.ics':
        dav_logger.debug('Oh boy, here we go!')
        return orig_href
    # PATCH HERE

    if orig_href == x:
        dav_logger.debug('Already normalized: {!r}'.format(x))
    else:
        dav_logger.debug('Normalized URL from {!r} to {!r}'
                         .format(orig_href, x))

    return x

```

With this change in place the sync finished successfully.

## Escaping changes

* `2012-08-07+08%3A42_320847479%40napp01.ics` (Original)
* `2012-08-07%2B08:42_320847479@napp01.ics` (Escaped)

The `+` was changed to `%2B`, the already escaped `%3A` was unescaped into `:`, and the already escaped `%40` got unescaped to `@`.

I changed the debug code above to not return `orig_href`, but a string with only one out of the three changes applied. It does not matter which one I do (`+` -> `%2B`, `%3A` -> `:`, `%40` -> `@`), it started to fail again.

So it seems like this `href` that is returned from the Google CalDAV API must not be changed at all or their server will not find it.

Is there something else I can provide you or help with?

**Comment by untitaker** [comment]
I believe I fixed this in master. You can use master with the `vdirsyncer-git` package, which is right now broken. I'll fix it.

**Comment by untitaker** [comment]
the `vdirsyncer-git` package is now working again, please try it

**Comment by Mange** [comment]
I installed it but now it started spewing hundreds and hundreds of errors. I had to abort it when it started to look like it was duplicating all of my calendar data. :grimacing: 

```
error: Unknown error occurred for calendar/swedish@holiday.calendar.google.com: 403 Client Error: Forbidden for url: https://apidata.googleusercontent.com/caldav/v2/swedish%40holiday.calendar.google.com/events/20170101_60o30dj46so30c1g60o30dr564%40google.com.ics
error: Use `-vdebug` to see the full traceback.
Copying (updating) item 20170106_60o30dj474o30c1g60o30dr564@google.com to calendar_remote/swedish@holiday.calendar.google.com
error: Unknown error occurred for calendar/cln2ssrncli6isr84dk6ur39chgnig37e9nnas1eeon66obccln68obi5pjmurr7dhiisorfdk@virtual: 403 Client Error: Forbidden for url: https://apidata.googleusercontent.com/caldav/v2/cln2ssrncli6isr84dk6ur39chgnig37e9nnas1eeon66obccln68obi5pjmurr7dhiisorfdk%40virtual/events/20170101_60o30dj46so30c1g60o30dr564%40google.com.ics
error: Use `-vdebug` to see the full traceback.
```

I'm not sure what to do here. Is it safe to run again with `-vdebug`? Did something change that I need to adjust in my config?

**Comment by untitaker** [comment]
I would clear the status and local data, re-discover and sync to be on the safe side. I didn't change anything at all (note that it doesn't appear to duplicate data, as it says "updating" instead of "uploading"), but it's the safest way.

**Comment by Mange** [comment]
Since I was actually just using `vdirsyncer` to have an offline read-only copy of my contacts and calendars, I deleted all local files and added `read_only = true` to all the remote storages and started over.

After discovering and creating all the calendars and contact books, and a successful `metasync`, all my `sync` calls fails with errors like these:

```error: calendar/jmlfp6peclohl55alf923krl94@group.calendar.google.com: Storage "calendar_local/jmlfp6peclohl55alf923krl94@group.calendar.google.com" was completely emptied. If you want to delete ALL entries on BOTH sides, then use `vdirsyncer sync --force-delete calendar/jmlfp6peclohl55alf923krl94@group.calendar.google.com`. Otherwise delete the files for calendar/jmlfp6peclohl55alf923krl94@group.calendar.google.com in your status directory.
error: 11 out of 17 tasks failed.
```

**Comment by untitaker** [comment]
You need to delete the status data as well, concretely the files ending with `.items`.

**Comment by Mange** [comment]
Aha, I see. Now it is purring like a kitten.

Thank you! :heart:

**Comment by untitaker** [comment]
Cool. FWIW @Mange it's unlikely that this version of vdirsyncer will be released anytime soon as a few packagers said the way I package my Rust dependencies is not acceptable to them.

**Comment by Mange** [comment]
Oh, I see. Let me know if I can help out with that.

I generally try to replace as much as possible[1] on my machine with Rust-based software so I'm happy to hear you have Rust dependencies now. 😆

[1]: First I try to find Free, then Keyboard-focused/Vim-bindings, then Rust-based. It's not the most important factor, but it helps selecting alternatives.
