### ISSUE TITLE
test_open_graphical_browser fails with python 3.7

### ISSUE THREAD

**Issue by dvzrv** [pimutils/vdirsyncer#754]
* vdirsyncer 0.16.6
* Python 3.7
* Arch Linux

I'm currently doing rebuilds for Python 3.7 (for the Arch Linux package) and this test fails:

```
=================================== FAILURES ===================================
_________________________ test_open_graphical_browser __________________________
tests/system/utils/test_main.py:69: in test_open_graphical_browser
    iter(webbrowser._tryorder)
E   TypeError: 'NoneType' object is not iterable
```

This might be related:
https://bugs.python.org/issue34019

I can probably disable that test for now, yeah?

**Comment by untitaker** [comment]
It's likely that google storage will be broken on Python 3.7. Will fix this evening

**Comment by untitaker** [comment]
0.16.7 is out, sorry for the wait!
