### ISSUE TITLE
Thanks to the wonders of vdirsync: Floating events.

### ISSUE THREAD

**Issue by sciurius** [pimutils/vdirsyncer#755]
As an old DateBk5 user (Pimlico, Palm Pilot) I was used to, and loved, floating events.

A floating event is a basically an ordinary event that is scheduled on a specific date(time). When the event time is passed, the event moves to the next day. So it is 'stuck' on today's date until it is deactivated (checked off).

Using vdirsync this turned out to be very easy to implement. In the vdir, all events are in separate .ics files, and bunches of files are easy to examine and process. So I use a special marker (a hook arrow, ↪) in front of the event summary to designate it as a floating event. A nightly cron task investigates the events in the vdir and, if necessary, updates the event date. Vdirsync will take care that everything is synched back to the CalDAV server. To deactivating, just remove the special marker from the subject. A piece of cake.

So thank you very much for vdir and vdirsync!

The code for the floating events is on GitHub: https://github.com/sciurius/vdirfloat .

**Comment by sciurius** [comment]
Assuming you mean a daily recurring event, this will be visible on every day, cluttering the calendar (in particualr the week and month views). A floating event is visible on today only.
Floating events are more related to todo items with start and (optional) end times. When the start time is reached, it appears on the daily agenda and sticks on today until dealt with, or until the end time is reached. That could have been an alternative way of implementing this.

**Comment by untitaker** [comment]
Ok, makes sense I guess :) I prefer to use a todolist though :dagger: 

Thanks for the feedback
