### ISSUE TITLE
Syncing Facebook calendar

### ISSUE THREAD

**Issue by ellypsis** [pimutils/vdirsyncer#766]
Hi,
I want to sync my facebook calendar to a caldav calendar on my baïkal.
To do that, I found vdirsyncer and use it in a script to do that.
First, I tried to sync my facebook calendar with a local .ics file. It seems to work, but I don't have any .ics file in local.
Spec:
- vdirsyncer 0.16.7-2
- python 3.7.0
- archlinux
My config file : 
```
[general]
status_path = "~/.vdirsyncer/status/"

[pair facebook_calendar]
a = "facebook_local"
b = "facebook_remote"
collections = ["from b"]

[storage facebook_local]
type = "filesystem"
path = "~/.vdirsyncer/"
fileext = ".ics"

[storage facebook_remote]
type = "http"
read_only = true
url = "https://www.facebook.com/ical/u.php?uid=xxxxxxxxxxxxxxxxxxx&key=xxxxxxxxxxxxxxxx"
```
Return : 
```
mathieu > vdirsyncer -vdebug sync facebook_calendar
debug: Using 1 maximal workers.
```
What did I miss?

**Comment by ellypsis** [comment]
Hi,
Does someone already tried to do the same?

**Comment by sheijk** [comment]
Had a similar issue. What seems to have fixed this for me was setting "collections = null" in the pair section and the running "vdirsyncer discover; vdirsyncer sync"

**Comment by ellypsis** [comment]
@sheijk thanks a lot, it's working now.
I'm now able to sync my facebook calendar with my baikal calendar.
Closing issue.
