### ISSUE TITLE
Mistake in tutorial "Running as a systemd.timer"?

### ISSUE THREAD

**Issue by scruloose** [pimutils/vdirsyncer#792]
The [Running as a systemd.timer](https://vdirsyncer.pimutils.org/en/stable/tutorials/systemd-timer.html) tutorial suggests running the command `systemctl --user edit vdirsyncer` to make configuration changes. However, that command defaults to overriding the .service file, and the configuration options suggested in the tutorial are timer-specific. Unless I'm missing something, the instructions as written will result in a broken service configuration, and the correct command would be `systemctl --user edit vdirsyncer.timer`.

**ETA** (this may be a Debian-specific quirk, per [systemd issue 1621](https://github.com/systemd/systemd/issues/1621), but it might be worth mentioning in that tutorial): On my machine with systemd v241 as configured by the installer, the command `journalctl --user -u vdirsyncer` does not return any entries. The command `journalctl --user-unit vdirsyncer` shows vdirsyncer's output as expected. I did have to add my user to the systemd-journal group first, but fortunately journalctl's error message clearly indicated that fact.

*  vdirsyncer version
0.16.7
* operating system
Debian Buster

**Comment by WhyNotHugo** [comment]
You're quite right, thanks!
