### ISSUE TITLE
Get rid of perform_health_check

### ISSUE THREAD

**Issue by dotlambda** [pimutils/vdirsyncer#793]
Hypothesis has dropped support for the `perform_health_check` setting in 4.0.0: https://github.com/HypothesisWorks/hypothesis/blob/hypothesis-python-4.0.0/hypothesis-python/docs/changes.rst#settings. Therefore, the tests can't be run if you're on a recent version of hypothesis.

**Comment by WhyNotHugo** [comment]
Fixed via a26d3bb58cc7989e8befee41a517b0f02c3b9b9f
