### ISSUE TITLE
Google OAuth for DAV

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#8]
https://developers.google.com/google-apps/calendar/auth

Apparently we have to register the client at Google, not sure how we would keep the keys secret (if any) in an opensource project.

**Comment by vaskas** [comment]
Is the default token really needed? Looking at https://github.com/insanum/gcalcli/blob/master/gcalcli#L642, you just need to call `OAuth2WebServerFlow` from `oauth2client.client` to do the browser dance.

**Comment by untitaker** [comment]
Yes, one has to call it with client-id and -secret. I myself don't have any incentive to work on this though.

**Comment by untitaker** [comment]
Somebody mailed me in private and hinted that adding OAuth support to this is now easier since remoteStorage support is now merged into master, which already uses OAuth.

* First of all, OAuth can't even be described as a proper standard. Many things can be described "OAuth-compatible", and I suspect that Google's OAuth implementation is vastly more complex than the one remoteStorage prescribes.

  Concretely, remoteStorage requires us to implement what is called the "implicit grant". flow. Basically you acquire one `access_token`, and that token will be used for any further authentication at all times.

  However, other variants of OAuth may require us to acquire a token to request another token that may be rotated every n days. For reasons I haven't looked into, this enhances security in case any credentials are stolen, but it's obviously harder to implement.

  It also means that if we implement OAuth for Google, this form of OAuth probably can't be reused for other services that require OAuth too, since no two OAuth implementations look alike.

* Google's CalDAV implementation is allegedly *okay*, while CardDAV seems to be abysmal. See http://evertpot.com/google-carddav-issues/ (already posted above).

* As already outlined above, we'd have to register vdirsyncer as an application with Google, and then provide *another token* to Google to identify ourselves as that application. We have a problem here: Should we let the user "play developer" and register their own application, and then let vdirsyncer "impersonate" that application? Or should we ship with a default token?

    * If the user registers their own application, using vdirsyncer with Google becomes somewhat hard to use.

    * If we ship with default token, anybody can easily steal that token and use it in their own apps.

  I think we should ship with a default token registered by me or whoever would maintain Google OAuth support.

Personally I won't be implementing this. I really don't care about supporting vendor-specific auth flows this complex.
