### ISSUE TITLE
Systemd timer: GPG passphrase not prompted

### ISSUE THREAD

**Issue by f-dj** [pimutils/vdirsyncer#807]
vdirsyncer version: 0.16.7
python version: 3.8.0
OS: Manjaro/i3

Another user created [a post regarding this issue on unix.stackexchange.com](https://unix.stackexchange.com/questions/546758/pass-password-prompt-from-systemd-user-unit).

When using the systemd timer, the gpg passphrase is not prompted. The service therefore fails until the gpg key is accessed manually and the passphrase provided. 

If I remember correctly, this works on Manjaro with xfce4. 

Relevant lines from `.config/vdirsyncer/config`
```
username.fetch = ["command", "~/.get-user.sh"]
password.fetch = ["command", "~/.get-pw.sh"]
```

`~/get-pw.sh`
```
#!/bin/sh

pass "<PW_DIR>" | head -1'
```

**Comment by WhyNotHugo** [comment]
If this is a systemd timer, how do you expect to see the prompt? There's no interactive console there.


--
Hugo Osvaldo Barrera

**Comment by f-dj** [comment]
Well, I am pretty sure it worked on xfce4. Why wouldn't there be no interactive console for a systemd USER service? May be a gpg related issue though, I am not sure.

**Comment by WhyNotHugo** [comment]
For the prompt to be visible on your dekstop, you need to import your desktop environment variables into systemd-user.

This means, generally, importing `WAYLAND_DISPLAY` and/or `DISPLAY` into systemd. The general advise is to do this when your compositor/DE starts up.

For i3/sway, I have this at the end of [my config file](https://github.com/WhyNotHugo/dotfiles/blob/master/home/.config/sway/config#L90-L91):

    exec "systemctl --user import-environment; systemctl --user start graphical-session.target"

For other desktops, you'll need to look into their documentation on best practices for systemd integration, but it's very likely running `systemctl --user import-environment` on startup.

Closing, but lemme know if you've leftover questions.

**Comment by f-dj** [comment]
`display :0` in gpg-agent.conf solved this for me. I forgot about this open issue, sorry for not closing. Thanks for your help anyway.

**Comment by WhyNotHugo** [comment]
> display :0 in gpg-agent.conf solved this for me. I forgot about this open issue, sorry for not closing. Thanks for your help anyway.

This should cover 99% of the cases -- only countercases being if you ever use a different VT, or switch to wayland.
