### ISSUE TITLE
Exception when running on vboxsf filesystem

### ISSUE THREAD

**Issue by dmorlitz** [pimutils/vdirsyncer#813]
I am currently trying to run vdirsyncer inside of a VirtualBox virtual machine.  The directory that I want to store my contacts in is actually on the VirtualBox host and made available to the virtual machine as a filesystem of type vboxsf.  In this configuration, vdirsyncer does not work because it runs into an exception when trying to move the temporary VCF file to the final VCF file.

Background on my system:
vdirsyncer 0.16.2 (I just installed it today using the script on the vdirsyncer web-site)
Python version 2.7.17
Python3 version 3.6.9
OS - Ubuntu 18.04 with all latest updates

When I use directories that reside on an ext4 filesystem vdirsyncer works perfectly.  My preference is to run on the vboxsf shared filesystem because that is how I can get updates onto my backup devices and external storage.

I am running vdirsyncer as the user that owns the directory and is a member of the vboxsf group.  All files are owned by my user ID and my primary group with file permissions set to 775.

I assume that moving the temporary file is either using some type of linking or trying to set file permissions that are not valid on this type of filesystem.  I am not sure why a simple mv or cp is not used - as those work perfectly on this filesystem type.

I am doing a very simply 1-way synchronize from Google Contacts to a local directory.  My vdirsyncer.conf file:
= = = = = = = = =
[general]
status_path = "/vboxsf/vdirsyncer/status"

[storage googlecontacts]
type = "google_contacts"
token_file = "/vboxsf/vdirsyncer/valid.google.token"
client_id = "<valid client id>.apps.googleusercontent.com"
client_secret = "<valid secret>"
read_only = "true"

[storage vcf]
type = "filesystem"
path = "/vboxsf/vdirsyncer/contacts"
fileext = ".vcf"

[pair david_google]
a = "googlecontacts"
b = "vcf"
collections = ["from a"]
conflict_resolution = "a wins"
= = = = = = = = =

Output of 1 entry trying to sync with -vdebug enabled:
= = = = = = = = =
Copying (uploading) item fe6366909f50f83 to vcf/default
error: Unknown error occured for google/default: [Errno 1] Operation not permitted: '/vboxsf/vdirsyncer/default/tmpvqbmrf0r' -> '/vboxsf/vdirsyncer/contacts/default/fe6366909f50f83.vcf'
error: Use `-vdebug` to see the full traceback.
debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/cli/utils.py", line 73, in handle_cli_error
debug:     raise e
debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/sync.py", line 578, in sync
debug:     partial_sync
debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/sync.py", line 602, in run
debug:     self._run_impl(a, b)
debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/sync.py", line 629, in _run_impl
debug:     href, etag = self.dest.storage.upload(self.item)
debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/storage/base.py", line 15, in inner
debug:     return f(self, *args, **kwargs)
debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/storage/filesystem.py", line 126, in upload
debug:     fpath, etag = self._upload_impl(item, href)
debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/storage/filesystem.py", line 149, in _upload_impl
debug:     return fpath, get_etag_from_file(f)
debug:   File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
debug:     next(self.gen)
debug:   File "/home/dmorlitz/.local/lib/python3.6/site-packages/atomicwrites/__init__.py", line 159, in _open
debug:     self.commit(f)
debug:   File "/home/dmorlitz/.local/lib/python3.6/site-packages/atomicwrites/__init__.py", line 194, in commit
debug:     move_atomic(f.name, self._path)
debug:   File "/home/dmorlitz/.local/lib/python3.6/site-packages/atomicwrites/__init__.py", line 105, in move_atomic
debug:     return _move_atomic(src, dst)
debug:   File "/home/dmorlitz/.local/lib/python3.6/site-packages/atomicwrites/__init__.py", line 53, in _move_atomic
debug:     os.link(src, dst)
error: 1 out of 2 tasks failed.
= = = = = = = = =

**Comment by WhyNotHugo** [comment]
The issue is because the filesystem you're using does not support hardlinks. Not sure if this is a limitation of vboxfs, or of the actual underlying filesystem you're mounting.

We use [atomicwrites](https://pypi.org/project/atomicwrites/) to make sure writing files is atomic (and at no point you have a half-copied file). My suggestion would be to just sync into a normal filesystem, and then `rsync` the files over to you `vboxfs` filesystem.

If you want to dig deeper into this, it's actually a atomicwrites bug, so please follow up there, and see if it's possible to support filesystems with no support for linking, but this is not something we can fix on the vdirsyncer side.
