### ISSUE TITLE
Please release a version with stated Python 3.7 support

### ISSUE THREAD

**Issue by equaeghe** [pimutils/vdirsyncer#819]
* Your vdirsyncer version: _0.16.7 _
* Your Python version: _moving from 3.6 to 3.7_
* Your operating system: Gentoo Linux
---
Gentoo is moving from 3.6 to 3.7 as the default Python. vdirsyncer 0.16.7 states support up to and including Python 3.6:
https://github.com/pimutils/vdirsyncer/blob/7a92aa20b1910eb5cc3c451a9a2fa62e76c80141/setup.py#L126-L129
Unless vdirsyncer is indeed incompatible with Python 3.7, please release a version with Python 3.7 added here. Then downstream (Gentoo) can ‘allow’ this Python version as well.

(Of course, in case vdirsyncer is compatible with Python 3.8 as well, please add that version too.)

If there are known issues with Python 3.7 encountered by users, please refer to them in this issue, so that we can get an overview. Please do not describe unreported compatibility issues here, add them as a separate issue first.

Users that run vdirsyncer with Python 3.7+, please add a +1/thumbs up to this post. Users that run it with Python 3.8, please additionally add a Hooray cone. This allows us to get the impression of compatibility in practice.

**Comment by WhyNotHugo** [comment]
I've been using vdirsyncer with Python 3.8 for ages now. I'll update CI to run with Python 3.7 and 3.8, if all tests pass, I guess we can officially support these.

**Comment by WhyNotHugo** [comment]
Hmm... master/0.17 seems quite broken, and it's slightly beyond me to fix it.

Maybe a point release for 0.16 might make more sense.

**Comment by equaeghe** [comment]
> Maybe a point release for 0.16 might make more sense.

Yes, that would be ideal!

**Comment by WhyNotHugo** [comment]
0.16.8 has been release. It support Python 3.5 thru 3.8.
