### ISSUE TITLE
Please provide python 3.9 support

### ISSUE THREAD

**Issue by alvitg** [pimutils/vdirsyncer#847]
Vdirsyncer emits error on MacOS Catalina as well as on Void Linux being compiled against Python 3.9.

Example -vdebug output on Linux:

debug: PROPFIND https://carddav.yandex.ru/addressbook/myname%40yandex.ru/addressbook/
debug: {'User-Agent': 'vdirsyncer/0.16.8', 'Content-Type': 'application/xml; charset=UTF-8', 'Depth': '1'}
debug: b'<?xml version="1.0" encoding="utf-8" ?>\n            <D:propfind xmlns:D="DAV:">\n                <D:prop>\n                    <D:resourcetype/>\n                    <D:getcontenttype/>\n                    <D:getetag/>\n   
...
<D:propstat><D:prop><D:getetag>"2495-2727"</D:getetag><D:getcontenttype>text/x-vcard</D:getcontenttype><D:resourcetype/></D:prop><status xmlns="DAV:">HTTP/1.1 200 OK</status></D:propstat></D:response></D:multistatus>'
debug: Normalized URL from '/addressbook/myname%40yandex.ru/addressbook/' to '/addressbook/myname@yandex.ru/addressbook/'
error: Unknown error occurred for avg_contacts/addressbook: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'
error: Use `-vdebug` to see the full traceback.
debug:   File "/usr/lib/python3.9/site-packages/vdirsyncer/cli/tasks.py", line 62, in sync_collection
debug:     sync.sync(
debug:   File "/usr/lib/python3.9/site-packages/vdirsyncer/sync/__init__.py", line 135, in sync
debug:     b_nonempty = b_info.prepare_new_status()
debug:   File "/usr/lib/python3.9/site-packages/vdirsyncer/sync/__init__.py", line 44, in prepare_new_status
debug:     for href, etag in self.storage.list():
debug:   File "/usr/lib/python3.9/site-packages/vdirsyncer/storage/dav.py", line 635, in list
debug:     for href, etag, _prop in rv:
debug:   File "/usr/lib/python3.9/site-packages/vdirsyncer/storage/dav.py", line 591, in _parse_prop_responses
debug:     props = _merge_xml(props)
debug:   File "/usr/lib/python3.9/site-packages/vdirsyncer/storage/dav.py", line 123, in _merge_xml
debug:     rv.extend(item.getiterator())
error: 1 out of 2 tasks failed.

My config:

[general]
status_path = "~/.vdirsyncer/status/"

[pair avg_contacts]
a = "avg_contacts_local"
b = "avg_contacts_yandex"
collections = ["from a", "from b"]
metadata = ["displayname"]
conflict_resolution = "a wins"

[storage avg_contacts_local]
type = "filesystem"
path = "~/Documents/Contacts/"
fileext = ".vcf"

[storage avg_contacts_yandex]
type = "carddav"
url = "https://carddav.yandex.ru/"
username = "myname@yandex.ru"
password.fetch = ["command", "keyring", "get", "yandex", "myname@yandex.ru"]

**Comment by WhyNotHugo** [comment]
I'm without a laptop for about a week, but I'll try to address this after that.

--
Hugo Osvaldo Barrera

**Comment by tirkarthi** [comment]
This seems to have been fixed in https://github.com/pimutils/vdirsyncer/commit/7577fa21177442aacc2d86640ef28cebf1c4aaef

**Comment by alvitg** [comment]
> This seems to have been fixed in [7577fa2](https://github.com/pimutils/vdirsyncer/commit/7577fa21177442aacc2d86640ef28cebf1c4aaef)

Indeed, I've checked out the latest version [b5d4d3f] and the problem is not observed.

Thanks a lot!

Thus, the problem source are outdated versions in Homebrew, pip and Void Linux repositories.

**Comment by bitmeise** [comment]
> Thus, the problem sources are outdated versions in Homebrew, pip and Void Linux repositories.

And for this to change we need an official vdirsyncer release. The last one is from June 9th.

**Comment by WhyNotHugo** [comment]
I'll try to push a new release next week.  
I want to address Python 3.9 support first.

**Comment by dtrodrigues** [comment]
Homebrew's vdirsyncer now supports Python 3.9 by pulling in the needed commit: https://github.com/Homebrew/homebrew-core/pull/63467
