### ISSUE TITLE
Google group membership sync.

### ISSUE THREAD

**Issue by lockywolf** [pimutils/vdirsyncer#849]
This is more of a question than a bug report.

Google address book allows groupting contacts (or rather, attaching labels). However, I see no trace of such labels in .vcf files.

As an example, I created an almost empty vcard on my Android phone and put it into a special group `testgroup`. 

```BEGIN:VCARD
VERSION:3.0
N:;Test-contact-only-label;;;
FN:Test-contact-only-label
REV:2020-10-13T16:25:41Z
UID:7815a22d0e710ea9
END:VCARD
```

I do not see it in the card file, and `vdirsyncer metasync` doesn't seem to fetch groups either. I wonder whether this is a Google CardDAV API deficiency, or this support can be added? (Maybe in the form or a kind/member vCard type https://tools.ietf.org/html/rfc6350#section-6.1.4 ).

Exporting the data as one huge vcard does have a CATEGORIES: field.
![image](https://user-images.githubusercontent.com/2077025/95945746-bba62380-0e1d-11eb-8c8b-9d49941384ae.png)

P.S. "Starred" status is also not synchronised, but I guess this is completely Google-specific.

**Comment by etofi** [comment]
I have already opened a ticket for it (https://github.com/pimutils/vdirsyncer/issues/814) but this description is much better.

**Comment by WhyNotHugo** [comment]
Closing as duplicate.
