### ISSUE TITLE
convert VTODOS with due dates into calendar events, so google/outlook users can subscribe to nextcloud calendar

### ISSUE THREAD

**Issue by mstyp** [pimutils/vdirsyncer#853]
Before you submit bug reports: https://vdirsyncer.pimutils.org/en/stable/contributing.html

Things to include in your bugreport:

* Your vdirsyncer version
* If applicable, which server software (and which version) you're using
* Your Python version
* Your operating system
* Your config file
* Use `vdirsyncer -vdebug` for debug output. The output is sensitive, but
  please attach at least the last few lines before the error (if applicable),
  censored as necessary. This is almost always the most useful information.

**Comment by WhyNotHugo** [comment]
Converting TODOs to events would make them unreadable for todo-management apps, and only readable by calendar apps.

**Comment by mstyp** [comment]
> Converting TODOs to events would make them unreadable for todo-management apps, and only readable by calendar apps.

yes, thats what I want. um. like

tasks with dealines -> read only calendar events

**Comment by WhyNotHugo** [comment]
It seems that you need a script/program to convert your local VTODO entries into VEVENTS.

`vdirsyncer` just syncs between two collections.

**Comment by mstyp** [comment]
> It seems that you need a script/program to convert your local VTODO entries into VEVENTS.
> 

yes. how would I do that? I cant find any good walkthroughs or scrips or anything.

**Comment by WhyNotHugo** [comment]
> yes. how would I do that? I cant find any good walkthroughs or scrips or anything.

I meant to say "it seems that someone would need to write such a script". I don't know of any tool that does what you're looking for. Probably using https://icalendar.readthedocs.io/en/latest/ ?

Honestly, if you want something to show up on your calendar, you should probably create an event. Why are you creating tasks in a task manager if you actually want events to show up in a calendar?

**Comment by mstyp** [comment]
>I meant to say "it seems that someone would need to write such a script". I don't know of any tool that does what you're looking for. Probably using https://icalendar.readthedocs.io/en/latest/ ?

yeah fair nuff. I guess I'll need to start looking into how to make this myself. 

> Honestly, if you want something to show up on your calendar, you should probably create an event. Why are you creating tasks in a task manager if you actually want events to show up in a calendar?

Mostly because it would really screw with my workflow. These are not events, they are tasks with deadlines.

I dont want them on *my* calendar, I want them to show up as events on *other peoples* calendar, and because google and outlook dont accept VTODOS the way they accept VEVENTS, i need to figure out a way to make  it so the people who I work with, who refuse to use nextcloud, can see the tasks in the system that they do use.

**Comment by WhyNotHugo** [comment]
You might want to try printing the events with `todoman` (you can even print them all in `json` format), and the somehow feed this into khal.

A script that does that isn't probably terribly hard, but it'll require lots of patience testing.
