### ISSUE TITLE
vdirsyncer release tarball does not have contrib files

### ISSUE THREAD

**Issue by chenrui333** [pimutils/vdirsyncer#858]
Per this [build source change](https://github.com/Homebrew/homebrew-core/pull/67745), I found that the contrib files are not packaged into the pypi release artifact.

```
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - contrib/vdirsyncer.plist
```

**Comment by WhyNotHugo** [comment]
`contrib` will be included in the next release's tarballs.
