### ISSUE TITLE
Handling of RELATED field with google contacts

### ISSUE THREAD

**Issue by dinojr** [pimutils/vdirsyncer#867]
Google Contacts allows a "RELATIONSHIP"  field for a contact, which can be used to identify spouses, parents and children. Upon syncing with a vdir repository, these appear in the vcard as:
```
item1.X-ABRELATEDNAMES:name_of_the_child
item1.X-ABLabel:Child
```
whereas, according to the [RFC](https://tools.ietf.org/html/rfc6350#section-6.6.6), it should be something like:
```
RELATED;TYPE=child:urn:uuid:some_vcard_id
RELATED;TYPE=child;VALUE=text:name_of_the_child
```
It doesn't seem that the google contacts interface allows to input another vcard id like in the former, but only a text field like in the latter. vdirsyncer could however convert the item1.X-AB*** fields to the standard RELATED one ?

At the moment, khard doesn't seem to use the RELATED fields (see https://github.com/scheibler/khard/issues/273) but maybe other clients can.

* Your vdirsyncer version 0.16.7
* If applicable, which server software (and which version) you're using google contacts
* Your Python version 3.8.6
* Your operating system Ubuntu 20.10

**Comment by WhyNotHugo** [comment]
Looks like google generates a vcard entry that doesn't use the standard `RELATED;TYPE` field, but their own custom field instead. The real fix would be for Google to use the standard fields, but we all know how Google dislikes following standards.

I don't think it's a good idea to convert those. When syncing back to Google, you'd replace their custom entry with a standard one, which likely won't show up on their UI (can you try and see if `RELATED;TYPE` does show up on their UI?).

While it's possible to keep track of custom redefined fields, that's way out-of-scope for `vdirsyncer`, and sounds like a pain to maintain.

**Comment by dinojr** [comment]
> can you try and see if `RELATED;TYPE` does show up on their UI?)

You're right, it doesn't, and somehow leads to a duplicate vcard after a back and forth sync between vdir and google.
