### ISSUE TITLE
sync failing with public holidays

### ISSUE THREAD

**Issue by bill-lancaster** [pimutils/vdirsyncer#883]
vdirsyncer has been working so well for a long time I'd forgotten it was there!
In the past few days I noticed that sync was failing.

The problem is always with a public holiday event on the server.  Removing the event from the server results in an error with another public holiday event

vdirsyncer, version 0.16.7
Kubuntu 20.04

Config file:-
```dosini
[general]
status_path = "~/.vdirsyncer/status/"

[pair khal_sync]
a = "bill_calendar_local"
b = "bill_calendar_remote"
collections = ["from a", "from b"]

[storage bill_calendar_local]
type = "filesystem"
path = "~/.calendars/"
fileext = ".ics"

[storage bill_calendar_remote]
type = "caldav"
url = "https://caldav.one.com/calendars/users/bill-lancaster@brackenwood.one/calendar/"
username ="bill-lancaster@brackenwood.one"
password ="xxxxxxxx"

[storage local_storage_for_khard]
type = "filesystem"
fileext = "vcf"
path = "~//.contacts/"
```

```
Debug:-
error: Unknown error occured for khal_sync/calendar: /calendars/users/bill-lancaster@brackenwood.one/calendar/ca6af7456b0088abad9a69f9f620f5ac-2018-12-26-BoxingDay@gov.uk.ics
error: Use `-vdebug` to see the full traceback.
debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/cli/tasks.py", line 64, in sync_collection
debug:     sync.sync(
debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/sync/__init__.py", line 136, in sync
debug:     b_nonempty = b_info.prepare_new_status()
debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/sync/__init__.py", line 58, in prepare_new_status
debug:     for href, item, etag in (self.storage.get_multi(prefetch)
debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/storage/dav.py", line 505, in get_multi
debug:     raise exceptions.NotFoundError(href)
error: 1 out of 2 tasks failed.
```

Before you submit bug reports: https://vdirsyncer.pimutils.org/en/stable/contributing.html

Things to include in your bugreport:

* Your vdirsyncer version
* If applicable, which server software (and which version) you're using
* Your Python version
* Your operating system
* Your config file
* Use `vdirsyncer -vdebug` for debug output. The output is sensitive, but
  please attach at least the last few lines before the error (if applicable),
  censored as necessary. This is almost always the most useful information.

**Comment by bernhardreiter** [comment]
@bill-lancaster is this a test calender?

 Ss you seem to have given a working password in your report.

I suggest you remove it from https://github.com/pimutils/vdirsyncer/issues/883#issue-876174746 by editing it as soon as possible (unless it really is meant to be accessed by everybody).

**Comment by bernhardreiter** [comment]
The next steps of the analys would probably be to see what the other error message is you are getting when removing the event in question. And to give the event itself.

**Comment by bernhardreiter** [comment]
Also use `-vdebug` as indicated to get more details in the stacktrace.

**Comment by WhyNotHugo** [comment]
Indeed, please use `vdirsyncer -vdebug` so we can see what's going on in futher detail.

I suggest you change the password from above; the email has gone out to anyone watching this repository, so even deleting is not enough.

**Comment by bill-lancaster** [comment]
1) Have removed all the public holiday events in the server.  The event 2021-01-01-NewYearsDay shown in the output does not exist anywhere that I can find.
2) Ran :~$ vdirsyncer -vdebug sync, the last part of the output is shown below.

`VEML7M.ics'
debug: Already normalized: '/calendars/users/bill-lancaster@brackenwood.one/calendar/ZNSY19ZTAX8VSVJGW7NXSBRYPDIGAW090UVU.ics'
debug: Already normalized: '/calendars/users/bill-lancaster@brackenwood.one/calendar/ZSBLG34UTE1P39WX1QJQG6JY0IFT8ONQ52FP.ics'
error: Unknown error occured for khal_sync/calendar: /calendars/users/bill-lancaster@brackenwood.one/calendar/ca6af7456b0088abad9a69f9f620f5ac-2021-01-01-NewYearsDay@gov.uk.ics
error: Use `-vdebug` to see the full traceback.
debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/cli/tasks.py", line 64, in sync_collection
debug:     sync.sync(
debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/sync/__init__.py", line 136, in sync
debug:     b_nonempty = b_info.prepare_new_status()
debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/sync/__init__.py", line 58, in prepare_new_status
debug:     for href, item, etag in (self.storage.get_multi(prefetch)
debug:   File "/usr/lib/python3/dist-packages/vdirsyncer/storage/dav.py", line 505, in get_multi
debug:     raise exceptions.NotFoundError(href)
error: 1 out of 2 tasks failed.
`

**Comment by bill-lancaster** [comment]
Don't know if this helps, the .ics file mentioned in unknown error, ca6af7456b0088a..... does not exist locally (client).  Also every public holiday ics file has a URL value of ca6af7456b0088a....

**Comment by bill-lancaster** [comment]
Have now removed every ics file that contains a reference to 'ca6af7456b0088a....'
sync operations fails as before

**Comment by bill-lancaster** [comment]
Couldn't see any likely culprits on the server.
Exported the calendar and a search revealed an event containing the ca6a...etc reference in the url part.
Next I removed the file from the calendar folder.
VDIRSYNCER now syncs without a problem

**Comment by bill-lancaster** [comment]
Thanks for the help

**Comment by bernhardreiter** [comment]
@bill-lancaster good that you've solved the riddle (and gave feedback here, it may help others)!
