### ISSUE TITLE
Update Packagecloud to support modern Ubuntu/Debian versions

### ISSUE THREAD

**Issue by burnoutberni** [pimutils/vdirsyncer#884]
Hi! I recently installed vdirsyncer via [Packagecloud](https://packagecloud.io/pimutils/vdirsyncer) as recommended. I'm on Ubuntu 20.10 and everything works like a charm – until you try `apt update`.

The Packagecloud installer adds the following two lines to the sources.list, which is bad, because `vdirsyncer` hasn't been updated on Packagecloud in a while, so the latest packages supplied are for xenial and trusty. On update, `apt` throws a 404 error.

```
deb https://packagecloud.io/pimutils/vdirsyncer/ubuntu/ groovy main
deb-src https://packagecloud.io/pimutils/vdirsyncer/ubuntu/ groovy main
```

Could someone look into this? It seems like the same issue exists for Debian and possibly other packages provided via Packagecloud.

**Comment by WhyNotHugo** [comment]
Looks like the scripts that we had to push to packagecloud aged well, and I was able to push a new version for `ubuntu/groovy`.

This is 0.18a1. Can you try installing and see if it all works as intended for you?

**Comment by burnoutberni** [comment]
Looking good, thanks!
