### ISSUE TITLE
iCloud 403 Client Error when Contacts added to iCloud (not on deleting)

### ISSUE THREAD

**Issue by Bleala** [pimutils/vdirsyncer#931]
Hello there!

I'm having the following problem:
When i sync for example iCloud and Nextcloud everythings working fine, except when i'm adding a contant in Nextcloud and try to sync to iCloud, then i get "403 Client Error: Forbidden for url: https://p59-contacts.icloud.com:443/1002890283/carddavhome/card/e12fd36d-cc59-450b-acc3-21cd655c49f2.vcf"
Adding/removing in iCloud or removing in Nextcloud and syncing afterwards is working fine.

Things to include in your bugreport:

* Your vdirsyncer version = 0.16.7 with Ubuntu apt install & 0.18.0 installed with pip
* If applicable, which server software (and which version) you're using = Tried with Ubuntu 20.04
* Your Python version = 3.9.5
* Your operating system = Ubuntu 
* Your config file = 

[general]
status_path = "/vdirsyncer/status/"

[pair apple_nextcloud]
a = "nextcloud"
b = "apple"
#collections = ["card", "from b"]
collections = [["card", "kontakte", "card"]]
conflict_resolution = "b wins"
#collections = null

[storage nextcloud]
type = "carddav"
url = "https://xxx/remote.php/dav/addressbooks/users/user/kontakte/"
username = "xxx"
password = "xxx"

[storage apple]
type = "carddav"
url = "https://contacts.icloud.com/"
username = "xxx"
password = "xxx"

* Use `vdirsyncer -vdebug` for debug output. The output is sensitive, but
  please attach at least the last few lines before the error (if applicable),
  censored as necessary. This is almost always the most useful information.

Somehow this command does not work :(
Get following error: Error: Missing command.

Does anyone has an idea what the problem could be?

**Comment by GosuJunk** [comment]
I have the exact same issue today, how did you fix it ? It seems like the app-specific password access is limited.

When running a PUT directly to icloud.com, I get 'account is restricted' response:

curl -X PUT "https://p151-contacts.icloud.com/1360121923/carddavhome/card/TEST-UID.vcf" \
     -H "User-Agent: vdirsyncer/0.19.2" \
     -H "Content-Type: text/vcard" \
     -H "If-None-Match: *" \
     -u "My_apple_ID:app-specific-password" \
     --data-binary /vdirsyncer/.contacts/icloud/card/TEST-UID.vcf
     
>> account is restricted
