### ISSUE TITLE
Is it possible to configure more than one Google Calendar?

### ISSUE THREAD

**Issue by diego-rapoport** [pimutils/vdirsyncer#949]
* Your vdirsyncer version
0.18
* If applicable, which server software (and which version) you're using
Google
* Your Python version
3.9
* Your operating system
Archlabs

I just want to know if I can configure two different google calendars at the same time, from different accounts, and if it is possible, how do I configure it?

**Comment by Tonus1** [comment]
Sure you can.

```
# CALDAV
[pair first_calendar]
a = "first_calendar_local"
b = "first_calendar_remote"
collections = ["from a", "from b"]
conflict_resolution = "b wins"

# Calendars also have a color property
metadata = ["displayname", "color"]

[storage first_calendar_local]
type = "filesystem"
path = "~/Calendars-first/"
fileext = ".ics"

[storage first_calendar_remote]
type = "caldav"
url = ""
username = "user"
password.fetch = ["command", "pass", "show", "first_calendar"]

# CALDAV
[pair second_calendar]
a = "second_calendar_local"
b = "second_calendar_remote"
collections = ["from a", "from b"]
conflict_resolution = "b wins"

# Calendars also have a color property
metadata = ["displayname", "color"]

[storage academic_calendar_local]
type = "filesystem"
path = "~/Calendars-second/"
fileext = ".ics"

[storage second_calendar_remote]
type = "caldav"
url = ""
username = "user"
password.fetch = ["command", "pass", "show", "second_calendar"]
```

Will edit for gmail specifics.

**Comment by diego-rapoport** [comment]
Another question: Do I have to create another local calendar to pair with the second google_calendar? Because I tried with the same and it didn't work.

I checked out the homepage, but there's nothing about that specifically and trying to do with the information available I wasn't able to do make it.

**Comment by Tonus1** [comment]
There's a link on the homepage for documentation.
Local storage have to be present for each account.

**Comment by diego-rapoport** [comment]
Thank you very much!
