### ISSUE TITLE
Still discovering former collection/server

### ISSUE THREAD

**Issue by philmassart** [pimutils/vdirsyncer#957]
Hello, 
After deciding to change caldav server, I changed the settings of the server in the config file, removing the old one (located on my NAS) and adding the new settings.
I also removed the status folder, and the local calendars, to generate a new one using discover. 
Unfortunately, when launching a discover, vdirsyncer still looks for the collections on the old server.

I guess those settings are stored elsewhere, but I don't know where.

I installed vdirsyncer on Arch Linux, version version 0.18.1.dev0+g3191886.d20211204

Any idea to start a "fresh" sync from the new settings?

Thanks in advance

**Comment by dilyanpalauzov** [comment]
You can do a `grep -r [old-server-name]` in the directories, used by vdirsyncer, to see where references to it are still stored.

**Comment by philmassart** [comment]
Even while deleting de config folder (and the status), it must be located elsewhere. Perhaps in the cache of the python site-package...

**Comment by dilyanpalauzov** [comment]
> Even while deleting de config folder

Do you mean by “config folder” the files in the VDIRSYNCER_CONFIG environment variable,  ~/.vdirsyncer/config and 
$XDG_CONFIG_HOME/vdirsyncer/config, which is normally ~/.config/vdirsyncer/config?

**Comment by philmassart** [comment]
Yes;  in my case, ~/.config/vdirsyncer/config

**Comment by philmassart** [comment]
I started from a saved system (timeshift) before installing vdirsyncer and all is working as expected now.
Problem must be out of vdirsyncer. 
Sorry for the noise
