### ISSUE TITLE
Question/Feature request: Change file names

### ISSUE THREAD

**Issue by fdw** [pimutils/vdirsyncer#979]
I'm using `vdirsyncer` also as a tool to backup calendars and vcards. While it works fine for that, the results are not ideal: I have folders full of cryptically names events or people. Would it be possible to define the file name (for example "title" or "date")? Or is that a bad idea for some reason that I can't see yet?

**Comment by WhyNotHugo** [comment]
The names match `UID`s (unique identifiers), and they're the only property guaranteed to be unique. Titles or dates may not be unique.

Generally, it's not expected that people interact with these files directly, but rather use a tool like `khal` or `todoman`.

If you _do_ want to look through backups, I suggest using a search tool like [`ag`](https://github.com/ggreer/the_silver_searcher).

**Comment by fdw** [comment]
That makes sense. Thank you very much! 🙂
