### ISSUE TITLE
Restart=on-failure in systemd service is unnecessary

### ISSUE THREAD

**Issue by rEnr3n** [pimutils/vdirsyncer#998]
OS: Arch Linux
```
$ vdirsyncer --version
vdirsyncer, version 0.18.1.dev0+g3191886.d20211204
```

Wouldn't it make sense to remove `Restart=on-failure` on vdirsyncer.service? It's going to be restarted by the timer anyway. Having `Restart=on-failure` would keep resyncing when one of the remotes is unreachable causing a bit of a grind on disk.

**Comment by WhyNotHugo** [comment]
I guess just retrying once would be good enough?

**Comment by rEnr3n** [comment]
That would be fine too.

**Comment by WhyNotHugo** [comment]
PRs welcome.

**Comment by rEnr3n** [comment]
Do I need to write tests for this? I don't know how to write one.

**Comment by WhyNotHugo** [comment]
No, we don't ship tests for systemd unit files.
